// Code generated by cmd/recomp from pokeemerald_modern.elf. DO NOT EDIT.
package apprentice

import g "dbut.dev/sapphire/gba"

var regs0 = []reg{
	{0x0800A5E0, 188, BufferApprenticeChallengeText},
	{0x0800A69C, 10, Apprentice_ScriptContext_Enable},
	{0x0800A6A8, 28, ResetApprenticeStruct},
	{0x0800A6C4, 148, ResetAllApprenticeData},
	{0x0800A758, 24, GivenApprenticeLvlMode},
	{0x0800A770, 100, SetApprenticeId},
	{0x0800A7D4, 32, SetPlayersApprenticeLvlMode},
	{0x0800A7F4, 148, ShuffleApprenticeSpecies},
	{0x0800A888, 96, GetMonIdForQuestion},
	{0x0800A8E8, 472, SetRandomQuestionData},
	{0x0800AAC0, 496, GetRandomAlternateMove},
	{0x0800ACB0, 72, TrySetMove},
	{0x0800ACF8, 152, GetLatestLearnedMoves},
	{0x0800AD90, 236, GetDefaultMove},
	{0x0800AE7C, 296, SaveApprenticeParty},
	{0x0800AFA4, 556, CreateApprenticeMenu},
	{0x0800B1D0, 108, Task_ChooseAnswer},
	{0x0800B23C, 86, CreateAndShowWindow},
	{0x0800B294, 24, RemoveAndHideWindow},
	{0x0800B2AC, 60, CreateChooseAnswerTask},
	{0x0800B2E8, 28, CallApprenticeFunction},
	{0x0800B304, 72, Script_ResetPlayerApprentice},
	{0x0800B34C, 32, Script_GivenApprenticeLvlMode},
	{0x0800B36C, 40, Script_SetApprenticeLvlMode},
	{0x0800B394, 10, Script_SetApprenticeId},
	{0x0800B3A0, 10, Script_SetRandomQuestionData},
	{0x0800B3AC, 40, IncrementQuestionsAnswered},
	{0x0800B3D4, 28, GetNumApprenticePartyMonsAssigned},
	{0x0800B3F0, 44, IsFinalQuestion},
	{0x0800B41C, 20, Script_CreateApprenticeMenu},
	{0x0800B430, 84, Task_WaitForPrintingMessage},
	{0x0800B484, 328, PrintApprenticeMessage},
	{0x0800B5CC, 34, Script_PrintApprenticeMessage},
	{0x0800B5F0, 76, ApprenticeGetQuestion},
	{0x0800B63C, 60, SetApprenticePartyMon},
	{0x0800B678, 64, SetApprenticeMonMove},
	{0x0800B6B8, 376, InitQuestionData},
	{0x0800B830, 24, FreeQuestionData},
	{0x0800B848, 364, ApprenticeBufferString},
	{0x0800B9B4, 40, SetLeadApprenticeMon},
	{0x0800B9DC, 10, Script_ApprenticeOpenBagMenu},
	{0x0800B9E8, 180, TrySetApprenticeHeldItem},
	{0x0800BA9C, 184, ShiftSavedApprentices},
	{0x0800BB54, 144, SaveApprentice},
	{0x0800BBE4, 112, SetSavedApprenticeTrainerGfxId},
	{0x0800BC54, 108, SetPlayerApprenticeTrainerGfxId},
	{0x0800BCC0, 12, GetShouldCheckApprenticeGone},
	{0x0800BCCC, 12, GetShouldApprenticeLeave},
	{0x0800BCD8, 80, GetApprenticeNameInLanguage},
	{0x0800BD28, 28, Task_SwitchToFollowupFuncAfterButtonPress},
	{0x0800BD44, 68, Task_ExecuteFuncAfterButtonPress},
	{0x0800BD88, 40, ExecuteFuncAfterButtonPress},
	{0x0800BDB0, 32, ExecuteFollowupFuncAfterButtonPress},
	{0x0800BDD0, 4, stub_0800BDD0},
}

// 0x0800A5E0
func BufferApprenticeChallengeText(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB5F0)
	c.Thumb(0x464F)
	c.Thumb(0x46D6)
	c.Thumb(0x4646)
	c.R[15] = 0x0800A5EC
	c.Thumb(0x4A27)
	c.Thumb(0xB5C0)
	c.Thumb(0x0607)
	c.Thumb(0x0E3B)
	c.Thumb(0x0D3F)
	c.Thumb(0x469A)
	c.Thumb(0x4690)
	c.Thumb(0x18FB)
	c.Thumb(0x6812)
	c.Thumb(0x009B)
	c.Thumb(0x18D3)
	c.Thumb(0x33DE)
	c.Thumb(0x7818)
	c.Thumb(0x4691)
	c.Thumb(0x2400)
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_0800A626
	}
	c.Thumb(0x2609)
L_0800A60C:
	c.NT(24)
	c.Thumb(0x210A)
	c.Thumb(0x0005)
	c.R[14] = 0x0800A615
	c.NCallT(0x081E1070)
	if c.U != 0 {
		if c.U != 0x0800A615 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x3401)
	c.Thumb(0x0600)
	c.Thumb(0x0624)
	c.Thumb(0x0E00)
	c.Thumb(0x0E24)
	c.Thumb(0x42AE)
	if c.Cond(0x2) {
		goto L_0800A626
	}
	c.Thumb(0x2C04)
	if c.Cond(0x1) {
		goto L_0800A60C
	}
L_0800A626:
	c.NT(88)
	c.Thumb(0x4457)
	c.Thumb(0x00BF)
	c.Thumb(0x0039)
	c.R[15] = 0x0800A630
	c.Thumb(0x4D17)
	c.Thumb(0x3115)
	c.Thumb(0x31FF)
	c.Thumb(0x4449)
	c.Thumb(0x0028)
	c.R[14] = 0x0800A63B
	c.NCallT(0x081B4238)
	if c.U != 0 {
		if c.U != 0x0800A63B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x19DB)
	c.Thumb(0x331C)
	c.Thumb(0x33FF)
	c.Thumb(0x0028)
	c.Thumb(0x7819)
	c.R[14] = 0x0800A64D
	c.NCallT(0x081B4B14)
	if c.U != 0 {
		if c.U != 0x0800A64D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x19DB)
	c.Thumb(0x33DE)
	c.Thumb(0x7819)
	c.Thumb(0x2201)
	c.Thumb(0x0023)
	c.R[15] = 0x0800A65E
	c.Thumb(0x480D)
	c.R[14] = 0x0800A661
	c.NCallT(0x081B4360)
	if c.U != 0 {
		if c.U != 0x0800A661 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x19DB)
	c.Thumb(0x33DC)
	c.Thumb(0x781B)
	c.R[15] = 0x0800A66E
	c.Thumb(0x4A0A)
	c.Thumb(0x06DB)
	c.Thumb(0x0E5B)
	c.Thumb(0x5899)
	c.R[15] = 0x0800A676
	c.Thumb(0x4809)
	c.R[14] = 0x0800A679
	c.NCallT(0x081B4728)
	if c.U != 0 {
		if c.U != 0x0800A679 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBCE0)
	c.Thumb(0x46BA)
	c.Thumb(0x46B1)
	c.Thumb(0x46A8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A69C
func Apprentice_ScriptContext_Enable(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0xB500)
	c.R[14] = 0x0800A6A3
	c.NCallT(0x081A381C)
	if c.U != 0 {
		if c.U != 0x0800A6A3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A6A8
func ResetApprenticeStruct(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0x2301)
	c.Thumb(0x2238)
	c.Thumb(0x425B)
	c.Thumb(0x6283)
	c.Thumb(0x62C3)
	c.Thumb(0x6303)
	c.Thumb(0x5483)
	c.Thumb(0x7803)
	c.Thumb(0x3A19)
	c.Thumb(0x4393)
	c.Thumb(0x2210)
	c.Thumb(0x4313)
	c.Thumb(0x7003)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A6C4
func ResetAllApprenticeData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(60)
	c.Thumb(0xB5F0)
	c.R[15] = 0x0800A6CA
	c.Thumb(0x4B22)
	c.Thumb(0x4646)
	c.Thumb(0x46D6)
	c.Thumb(0x464F)
	c.Thumb(0x681B)
	c.Thumb(0x001A)
	c.Thumb(0x2118)
	c.Thumb(0x4699)
	c.Thumb(0xB5C0)
	c.Thumb(0x32B1)
	c.Thumb(0x7853)
	c.Thumb(0x438B)
	c.Thumb(0x7053)
	c.R[15] = 0x0800A6E4
	c.Thumb(0x4B1C)
	c.Thumb(0x781B)
	c.Thumb(0x469A)
	c.Thumb(0x464B)
	c.Thumb(0x1D59)
	c.Thumb(0x2310)
	c.Thumb(0x4698)
	c.Thumb(0x2360)
	c.Thumb(0x464E)
	c.Thumb(0x2501)
	c.Thumb(0x2000)
	c.Thumb(0x469C)
	c.Thumb(0x2400)
	c.Thumb(0x36DD)
	c.Thumb(0x31FF)
	c.Thumb(0x426D)
L_0800A700:
	c.NT(76)
	c.Thumb(0x271F)
	c.Thumb(0x0102)
	c.Thumb(0x1812)
	c.Thumb(0x0092)
	c.Thumb(0x600D)
	c.Thumb(0x604D)
	c.Thumb(0x608D)
	c.Thumb(0x444A)
	c.Thumb(0x32DC)
	c.Thumb(0x7813)
	c.Thumb(0x43BB)
	c.Thumb(0x4647)
	c.Thumb(0x433B)
	c.Thumb(0x4667)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x43BB)
	c.Thumb(0x740D)
	c.Thumb(0x7013)
	c.Thumb(0x4653)
	c.Thumb(0x3001)
	c.Thumb(0x7074)
	c.Thumb(0x7034)
	c.Thumb(0x60CC)
	c.Thumb(0x75CB)
	c.Thumb(0x618C)
	c.Thumb(0x3644)
	c.Thumb(0x3144)
	c.Thumb(0x2804)
	if c.Cond(0x1) {
		goto L_0800A700
	}
	c.R[14] = 0x0800A741
	Script_ResetPlayerApprentice(c)
	if c.U != 0 {
		if c.U != 0x0800A741 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBCE0)
	c.Thumb(0x46BA)
	c.Thumb(0x46B1)
	c.Thumb(0x46A8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A758
func GivenApprenticeLvlMode(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.R[15] = 0x0800A75C
	c.Thumb(0x4B04)
	c.Thumb(0x681A)
	c.Thumb(0x23B1)
	c.Thumb(0x2003)
	c.Thumb(0x5CD3)
	c.Thumb(0x4018)
	c.Thumb(0x1E43)
	c.Thumb(0x4198)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A770
func SetApprenticeId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.Thumb(0xB5F0)
	c.Thumb(0x46C6)
	c.Thumb(0x23DE)
	c.Thumb(0xB500)
	c.R[15] = 0x0800A77C
	c.Thumb(0x4C14)
	c.Thumb(0x6822)
	c.Thumb(0x5CD3)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0800A7A6
	}
	c.Thumb(0x270F)
	c.Thumb(0x26B0)
	c.Thumb(0x25DC)
L_0800A788:
	c.NT(18)
	c.R[14] = 0x0800A78D
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A78D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6823)
	c.Thumb(0x4038)
	c.Thumb(0x5598)
	c.Thumb(0x5D5B)
	c.Thumb(0x06DB)
	c.Thumb(0x0EDB)
	c.Thumb(0x4283)
	if c.Cond(0x0) {
		goto L_0800A788
	}
L_0800A79C:
	c.NT(10)
	c.Thumb(0xBC80)
	c.Thumb(0x46B8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800A7A6:
	c.NT(10)
	c.R[15] = 0x0800A7AA
	c.Thumb(0x4B0A)
	c.Thumb(0x2707)
	c.Thumb(0x4698)
	c.Thumb(0x26B0)
	c.Thumb(0x25DC)
L_0800A7B0:
	c.NT(24)
	c.R[14] = 0x0800A7B5
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A7B5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4642)
	c.Thumb(0x4038)
	c.Thumb(0x6823)
	c.Thumb(0x5C12)
	c.Thumb(0x559A)
	c.Thumb(0x5D5B)
	c.Thumb(0x06DB)
	c.Thumb(0x0EDB)
	c.Thumb(0x4293)
	if c.Cond(0x0) {
		goto L_0800A7B0
	}
	goto L_0800A79C
}

// 0x0800A7D4
func SetPlayersApprenticeLvlMode(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.R[15] = 0x0800A7D8
	c.Thumb(0x4B06)
	c.Thumb(0x6819)
	c.Thumb(0x2303)
	c.Thumb(0x22B1)
	c.Thumb(0xB510)
	c.Thumb(0x001C)
	c.Thumb(0x4003)
	c.Thumb(0x5C88)
	c.Thumb(0x43A0)
	c.Thumb(0x4318)
	c.Thumb(0x5488)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A7F4
func ShuffleApprenticeSpecies(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.Thumb(0xB5F0)
	c.Thumb(0x46C6)
	c.Thumb(0xB500)
	c.Thumb(0xB083)
	c.Thumb(0x466D)
	c.Thumb(0x466A)
	c.Thumb(0x2300)
L_0800A802:
	c.NT(16)
	c.Thumb(0x7013)
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x3201)
	c.Thumb(0x2B0A)
	if c.Cond(0x1) {
		goto L_0800A802
	}
	c.Thumb(0x2632)
L_0800A812:
	c.NT(106)
	c.R[14] = 0x0800A817
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A817 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0004)
	c.R[14] = 0x0800A81D
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A81D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x210A)
	c.Thumb(0x4680)
	c.Thumb(0x0020)
	c.R[14] = 0x0800A827
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A827 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x210A)
	c.Thumb(0x0404)
	c.Thumb(0x4640)
	c.R[14] = 0x0800A831
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A831 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0400)
	c.Thumb(0x0C00)
	c.Thumb(0x5C2B)
	c.Thumb(0x0C24)
	c.Thumb(0x5D2F)
	c.Thumb(0x3E01)
	c.Thumb(0x552B)
	c.Thumb(0x0633)
	c.Thumb(0x542F)
	c.Thumb(0x0E1E)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800A812
	}
	c.Thumb(0x220F)
	c.R[15] = 0x0800A84E
	c.Thumb(0x4B0E)
	c.Thumb(0x7828)
	c.Thumb(0x6819)
	c.Thumb(0x786B)
	c.Thumb(0x0100)
	c.Thumb(0x4013)
	c.Thumb(0x4303)
	c.Thumb(0x20B4)
	c.Thumb(0x540B)
	c.Thumb(0x78EB)
	c.Thumb(0x78A8)
	c.Thumb(0x4013)
	c.Thumb(0x0100)
	c.Thumb(0x4303)
	c.Thumb(0x20B5)
	c.Thumb(0x540B)
	c.Thumb(0x792B)
	c.Thumb(0x7968)
	c.Thumb(0x011B)
	c.Thumb(0x4002)
	c.Thumb(0x4313)
	c.Thumb(0x22B6)
	c.Thumb(0x548B)
	c.Thumb(0xB003)
	c.Thumb(0xBC80)
	c.Thumb(0x46B8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800A888
func GetMonIdForQuestion(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(16)
	c.Thumb(0x0600)
	c.Thumb(0xB530)
	c.Thumb(0x0E03)
	c.Thumb(0x2B02)
	if c.Cond(0x0) {
		goto L_0800A8A8
	}
	c.Thumb(0x2000)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_0800A89E
	}
L_0800A898:
	c.NT(6)
	c.Thumb(0xBC30)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800A89E:
	c.NT(10)
	c.Thumb(0x7813)
	c.Thumb(0x5CC8)
	c.Thumb(0x3301)
	c.Thumb(0x7013)
	goto L_0800A898
L_0800A8A8:
	c.NT(2)
	c.R[15] = 0x0800A8AC
	c.Thumb(0x4C0E)
L_0800A8AA:
	c.NT(26)
	c.R[14] = 0x0800A8AF
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A8AF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2103)
	c.R[14] = 0x0800A8B5
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A8B5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0400)
	c.Thumb(0x0C05)
	c.Thumb(0x0B82)
	c.Thumb(0x6821)
	c.Thumb(0x1952)
	c.Thumb(0x0052)
	c.Thumb(0x1853)
	c.Thumb(0x310A)
	c.Thumb(0x1889)
	c.Thumb(0x2200)
L_0800A8C8:
	c.NT(12)
	c.Thumb(0x8858)
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_0800A8D4
	}
	c.Thumb(0x3201)
	c.Thumb(0x0612)
	c.Thumb(0x0E12)
L_0800A8D4:
	c.NT(16)
	c.Thumb(0x3302)
	c.Thumb(0x4299)
	if c.Cond(0x1) {
		goto L_0800A8C8
	}
	c.Thumb(0x2A03)
	if c.Cond(0x8) {
		goto L_0800A8AA
	}
	c.Thumb(0x0628)
	c.Thumb(0x0E00)
	goto L_0800A898
}

// 0x0800A8E8
func SetRandomQuestionData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0xB5F0)
	c.Thumb(0x464E)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x4645)
	c.Thumb(0x2380)
	c.Thumb(0xB5E0)
	c.Thumb(0x260A)
	c.Thumb(0xB08B)
	c.Thumb(0x005B)
	c.Thumb(0xAA06)
	c.Thumb(0x8093)
	c.Thumb(0x3BFE)
	c.Thumb(0x7193)
L_0800A904:
	c.NT(68)
	c.R[14] = 0x0800A909
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A909 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0004)
	c.R[14] = 0x0800A90F
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A90F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2103)
	c.Thumb(0x0007)
	c.Thumb(0x0020)
	c.R[14] = 0x0800A919
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A919 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0404)
	c.Thumb(0xAB07)
	c.Thumb(0x0C24)
	c.Thumb(0x2103)
	c.Thumb(0x0038)
	c.Thumb(0x5D1D)
	c.R[14] = 0x0800A929
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A929 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0400)
	c.Thumb(0x0C00)
	c.Thumb(0xAB07)
	c.Thumb(0x5C1B)
	c.Thumb(0xAA07)
	c.Thumb(0x3E01)
	c.Thumb(0x5513)
	c.Thumb(0x0633)
	c.Thumb(0x5415)
	c.Thumb(0x0E1E)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800A904
	}
	c.R[15] = 0x0800A944
	c.Thumb(0x4B5B)
	c.Thumb(0x9308)
	c.R[15] = 0x0800A948
	c.Thumb(0x4B5B)
	c.Thumb(0x9309)
	c.Thumb(0x2303)
	c.Thumb(0x2532)
	c.Thumb(0xAE08)
	c.Thumb(0x8133)
L_0800A950:
	c.NT(88)
	c.R[14] = 0x0800A955
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A955 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0004)
	c.R[14] = 0x0800A95B
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800A95B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x210A)
	c.Thumb(0x4680)
	c.Thumb(0x0020)
	c.R[14] = 0x0800A965
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A965 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x210A)
	c.Thumb(0x0404)
	c.Thumb(0x4640)
	c.R[14] = 0x0800A96F
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800A96F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0400)
	c.Thumb(0x0C00)
	c.Thumb(0x5C33)
	c.Thumb(0x0C24)
	c.Thumb(0x5D37)
	c.Thumb(0x3D01)
	c.Thumb(0x5533)
	c.Thumb(0x062B)
	c.Thumb(0x5437)
	c.Thumb(0x0E1D)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800A950
	}
	c.Thumb(0x2030)
	c.R[14] = 0x0800A98D
	c.NCallT(0x081292A4)
	if c.U != 0 {
		if c.U != 0x0800A98D {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x0800A990
	c.Thumb(0x4B4A)
	c.Thumb(0x220F)
	c.Thumb(0x6018)
	c.Thumb(0x2104)
	c.Thumb(0x7005)
	c.Thumb(0x3020)
	c.Thumb(0x4698)
	c.R[14] = 0x0800A99F
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x0800A99F {
			return
		}
		c.U = 0
	}
	c.Thumb(0xAB06)
	c.Thumb(0x70DD)
	c.Thumb(0x2300)
	c.Thumb(0x001C)
	c.R[15] = 0x0800A9AA
	c.Thumb(0x4B45)
	c.Thumb(0x469B)
	c.Thumb(0x2303)
	c.Thumb(0x4699)
	c.Thumb(0x4643)
	c.Thumb(0x0035)
	c.Thumb(0x9300)
L_0800A9B4:
	c.NT(76)
	c.Thumb(0x0026)
	c.Thumb(0x465B)
	c.Thumb(0x362E)
	c.Thumb(0x681A)
	c.Thumb(0x4649)
	c.Thumb(0x00B3)
	c.Thumb(0x4648)
	c.Thumb(0x469A)
	c.Thumb(0x782F)
	c.Thumb(0x5C9B)
	c.Thumb(0x4039)
	c.Thumb(0x4383)
	c.Thumb(0x430B)
	c.Thumb(0x4651)
	c.Thumb(0x548B)
	c.Thumb(0x2F03)
	if c.Cond(0x0) {
		goto L_0800AA02
	}
	c.Thumb(0xAB06)
	c.Thumb(0x1CDA)
	c.Thumb(0xA907)
	c.Thumb(0x0038)
	c.R[14] = 0x0800A9E3
	GetMonIdForQuestion(c)
	if c.U != 0 {
		if c.U != 0x0800A9E3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x464A)
	c.Thumb(0x465B)
	c.Thumb(0x4002)
	c.Thumb(0x6819)
	c.Thumb(0x0093)
	c.Thumb(0x469C)
	c.Thumb(0x4653)
	c.Thumb(0x200C)
	c.Thumb(0x5C5B)
	c.Thumb(0x4383)
	c.Thumb(0x4660)
	c.Thumb(0x4303)
	c.Thumb(0x4650)
	c.Thumb(0x5443)
	c.Thumb(0x2F02)
	if c.Cond(0x0) {
		goto L_0800AA2C
	}
L_0800AA02:
	c.NT(40)
	c.Thumb(0x3401)
	c.Thumb(0x3501)
	c.Thumb(0x2C09)
	if c.Cond(0x1) {
		goto L_0800A9B4
	}
	c.Thumb(0x9B00)
	c.Thumb(0x4698)
	c.Thumb(0x6818)
	c.R[14] = 0x0800AA15
	c.NCallT(0x081292E8)
	if c.U != 0 {
		if c.U != 0x0800AA15 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x4642)
	c.Thumb(0x6013)
	c.Thumb(0xB00B)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800AA2C:
	c.NT(22)
	c.Thumb(0x2103)
	c.Thumb(0x4663)
	c.Thumb(0x4494)
	c.Thumb(0x9403)
	c.Thumb(0x468A)
	c.Thumb(0x4664)
	c.Thumb(0x9502)
	c.Thumb(0x9301)
	c.Thumb(0x9204)
	c.Thumb(0x9D00)
	c.Thumb(0x9605)
L_0800AA42:
	c.NT(16)
	c.R[14] = 0x0800AA47
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800AA47 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4657)
	c.Thumb(0x2300)
	c.Thumb(0x682E)
	c.Thumb(0x7831)
	c.Thumb(0x4680)
	c.Thumb(0x4007)
	c.Thumb(0x1930)
L_0800AA54:
	c.NT(20)
	c.Thumb(0x18C2)
	c.Thumb(0x3220)
	c.Thumb(0x7812)
	c.Thumb(0x42BA)
	if c.Cond(0x0) {
		goto L_0800AA68
	}
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x428B)
	if c.Cond(0x9) {
		goto L_0800AA54
	}
L_0800AA68:
	c.NT(70)
	c.Thumb(0x1C4A)
	c.Thumb(0x429A)
	if c.Cond(0x1) {
		goto L_0800AA42
	}
	c.Thumb(0x46B4)
	c.Thumb(0x9A04)
	c.Thumb(0x9B01)
	c.Thumb(0x189B)
	c.Thumb(0x4463)
	c.Thumb(0x185B)
	c.Thumb(0x3320)
	c.Thumb(0x701F)
	c.Thumb(0x465B)
	c.Thumb(0x681B)
	c.Thumb(0x4642)
	c.Thumb(0x469A)
	c.Thumb(0x2303)
	c.Thumb(0x4013)
	c.Thumb(0x011A)
	c.Thumb(0x4653)
	c.Thumb(0x2130)
	c.Thumb(0x9E05)
	c.Thumb(0x00B6)
	c.Thumb(0x5CF3)
	c.Thumb(0x438B)
	c.Thumb(0x4313)
	c.Thumb(0x4652)
	c.Thumb(0x54B3)
	c.Thumb(0x071B)
	c.Thumb(0x0F98)
	c.Thumb(0x9D02)
	c.Thumb(0x9C03)
	c.R[14] = 0x0800AAAB
	GetRandomAlternateMove(c)
	if c.U != 0 {
		if c.U != 0x0800AAAB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4456)
	c.Thumb(0x8070)
	goto L_0800AA02
}

// 0x0800AAC0
func GetRandomAlternateMove(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(60)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x464E)
	c.Thumb(0x4645)
	c.Thumb(0xB5E0)
	c.Thumb(0x0600)
	c.R[15] = 0x0800AAD2
	c.Thumb(0x4B72)
	c.Thumb(0x0E01)
	c.Thumb(0xB087)
	c.Thumb(0x2000)
	c.Thumb(0x9104)
	c.Thumb(0x681A)
	c.Thumb(0x2902)
	if c.Cond(0x8) {
		goto L_0800AAFC
	}
	c.Thumb(0x1853)
	c.Thumb(0x33B4)
	c.Thumb(0x0008)
	c.Thumb(0x7819)
	c.Thumb(0x23B2)
	c.Thumb(0x5CD3)
	c.Thumb(0x075B)
	c.Thumb(0x0F5B)
	c.Thumb(0x4103)
	c.Thumb(0x2004)
	c.Thumb(0x009B)
	c.Thumb(0x4003)
	c.Thumb(0x4119)
	c.Thumb(0x300B)
	c.Thumb(0x4008)
L_0800AAFC:
	c.NT(58)
	c.Thumb(0x23B0)
	c.Thumb(0x5CD4)
	c.Thumb(0x3B84)
	c.Thumb(0x4363)
	c.Thumb(0x181B)
	c.R[15] = 0x0800AB0A
	c.Thumb(0x4965)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x5A5E)
	c.R[15] = 0x0800AB12
	c.Thumb(0x4B64)
	c.Thumb(0x00B1)
	c.Thumb(0x58CB)
	c.Thumb(0x4699)
	c.Thumb(0x23B1)
	c.Thumb(0x5CD2)
	c.Thumb(0x3BAE)
	c.Thumb(0x4013)
	c.Thumb(0x3B01)
	c.Thumb(0x1E5A)
	c.Thumb(0x4193)
	c.Thumb(0x220A)
	c.Thumb(0x425B)
	c.Thumb(0x401A)
	c.Thumb(0x464B)
	c.R[15] = 0x0800AB30
	c.Thumb(0x495D)
	c.Thumb(0x881B)
	c.Thumb(0x428B)
	if c.Cond(0x1) {
		goto L_0800AB36
	}
	goto L_0800AC92
L_0800AB36:
	c.NT(24)
	c.Thumb(0x1E50)
	c.Thumb(0x4182)
	c.Thumb(0x20A0)
	c.Thumb(0x4252)
	c.Thumb(0x0140)
	c.Thumb(0x4002)
	c.Thumb(0x20C8)
	c.Thumb(0x01C0)
	c.Thumb(0x1812)
	c.Thumb(0x2500)
	c.Thumb(0x4648)
	goto L_0800AB5C
L_0800AB4E:
	c.NT(14)
	c.Thumb(0x3501)
	c.Thumb(0x062B)
	c.Thumb(0x0E1D)
	c.Thumb(0x0DDB)
	c.Thumb(0x5A1B)
	c.Thumb(0x428B)
	if c.Cond(0x0) {
		goto L_0800AB64
	}
L_0800AB5C:
	c.NT(8)
	c.Thumb(0x0A5B)
	c.Thumb(0x025B)
	c.Thumb(0x4293)
	if c.Cond(0xD) {
		goto L_0800AB4E
	}
L_0800AB64:
	c.NT(2)
	c.Thumb(0x4681)
L_0800AB66:
	c.NT(20)
	c.Thumb(0x1F2B)
	c.Thumb(0x469B)
	c.Thumb(0x061B)
	c.Thumb(0x0DDB)
	c.Thumb(0x444B)
	c.Thumb(0x9300)
	c.Thumb(0x1C2B)
	c.Thumb(0x2D03)
	if c.Cond(0x8) {
		goto L_0800AB7A
	}
	c.Thumb(0x2304)
L_0800AB7A:
	c.NT(38)
	c.Thumb(0x3B04)
	c.Thumb(0x061B)
	c.Thumb(0x9A04)
	c.Thumb(0x0E1F)
	c.Thumb(0x0DDB)
	c.Thumb(0x444B)
	c.Thumb(0x4698)
	c.Thumb(0x0093)
	c.Thumb(0x9306)
	c.Thumb(0x189B)
	c.Thumb(0x005B)
	c.Thumb(0x9303)
	c.Thumb(0x2300)
	c.Thumb(0x469A)
	c.Thumb(0x9301)
	c.R[15] = 0x0800AB9C
	c.Thumb(0x4B43)
	c.Thumb(0x9302)
	c.R[15] = 0x0800ABA0
	c.Thumb(0x4B43)
	c.Thumb(0x9305)
L_0800ABA0:
	c.NT(24)
	c.R[14] = 0x0800ABA5
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800ABA5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2301)
	c.Thumb(0x4383)
	if c.Cond(0x1) {
		goto L_0800ABBC
	}
	c.Thumb(0x4653)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800ABBC
	}
	c.Thumb(0x2D04)
	if c.Cond(0x8) {
		goto L_0800AC60
	}
	c.R[14] = 0x0800ABB9
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800ABB9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2301)
	c.Thumb(0x469A)
L_0800ABBC:
	c.NT(40)
	c.R[14] = 0x0800ABC1
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800ABC1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x213A)
	c.R[14] = 0x0800ABC7
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x0800ABC7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0404)
	c.Thumb(0x0C24)
	c.Thumb(0x0021)
	c.Thumb(0x0030)
	c.R[14] = 0x0800ABD3
	c.NCallT(0x081814DC)
	if c.U != 0 {
		if c.U != 0x0800ABD3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_0800ABBC
	}
	c.Thumb(0x3422)
	c.Thumb(0x34FF)
	c.Thumb(0x0420)
	c.Thumb(0x0C00)
	c.R[14] = 0x0800ABE3
	c.NCallT(0x0814B5D0)
	if c.U != 0 {
		if c.U != 0x0800ABE3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0004)
	c.Thumb(0x42AF)
	if c.Cond(0x2) {
		goto L_0800AC02
	}
	c.Thumb(0x4641)
	c.Thumb(0x003B)
L_0800ABEC:
	c.NT(22)
	c.Thumb(0x880A)
	c.Thumb(0x05D2)
	c.Thumb(0x0DD2)
	c.Thumb(0x4290)
	if c.Cond(0x0) {
		goto L_0800ABBC
	}
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x3102)
	c.Thumb(0x42AB)
	if c.Cond(0x3) {
		goto L_0800ABEC
	}
L_0800AC02:
	c.NT(14)
	c.Thumb(0x9B02)
	c.Thumb(0x6818)
	c.Thumb(0x0001)
	c.Thumb(0x9A03)
	c.Thumb(0x310A)
	c.Thumb(0x1883)
	c.Thumb(0x1889)
L_0800AC10:
	c.NT(56)
	c.Thumb(0x885A)
	c.Thumb(0x42A2)
	if c.Cond(0x0) {
		goto L_0800ABA0
	}
	c.Thumb(0x3302)
	c.Thumb(0x4299)
	if c.Cond(0x1) {
		goto L_0800AC10
	}
	c.Thumb(0x9B06)
	c.Thumb(0x9904)
	c.Thumb(0x7802)
	c.Thumb(0x185B)
	c.Thumb(0x189B)
	c.Thumb(0x005B)
	c.Thumb(0x18C3)
	c.Thumb(0x805C)
	c.Thumb(0x9B05)
	c.Thumb(0x5D1B)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800AC48
	}
	c.Thumb(0x9B01)
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x9301)
	c.Thumb(0x2B05)
	if c.Cond(0x1) {
		goto L_0800ABA0
	}
	c.Thumb(0x9B02)
	c.Thumb(0x6818)
	c.Thumb(0x7802)
L_0800AC48:
	c.NT(24)
	c.Thumb(0x3201)
	c.Thumb(0x7002)
	c.Thumb(0x0020)
	c.Thumb(0xB007)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800AC60:
	c.NT(20)
	c.R[14] = 0x0800AC65
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x0800AC65 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4659)
	c.R[14] = 0x0800AC6B
	c.NCallT(0x082E4FD0)
	if c.U != 0 {
		if c.U != 0x0800AC6B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x464B)
	c.Thumb(0x2204)
	c.Thumb(0x0040)
	c.Thumb(0x5AC4)
	c.Thumb(0x9900)
	c.Thumb(0x05E4)
	c.Thumb(0x0DE4)
L_0800AC78:
	c.NT(26)
	c.Thumb(0x880B)
	c.Thumb(0x05DB)
	c.Thumb(0x0DDB)
	c.Thumb(0x429C)
	if c.Cond(0x0) {
		goto L_0800AC60
	}
	c.Thumb(0x3A01)
	c.Thumb(0x0613)
	c.Thumb(0x0E1A)
	c.Thumb(0x3102)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800AC78
	}
	c.Thumb(0x469A)
	goto L_0800AC02
L_0800AC92:
	c.NT(4)
	c.Thumb(0x2500)
	goto L_0800AB66
}

// 0x0800ACB0
func TrySetMove(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0x0600)
	c.Thumb(0x0E03)
	c.Thumb(0x469C)
	c.R[15] = 0x0800ACBA
	c.Thumb(0x4B0F)
	c.Thumb(0xB530)
	c.Thumb(0x681D)
	c.Thumb(0x4663)
	c.Thumb(0x002C)
	c.Thumb(0x0D80)
	c.Thumb(0x040A)
	c.Thumb(0x18C1)
	c.Thumb(0x0049)
	c.Thumb(0x340A)
	c.Thumb(0x0C12)
	c.Thumb(0x186B)
	c.Thumb(0x1864)
L_0800ACD0:
	c.NT(26)
	c.Thumb(0x8859)
	c.Thumb(0x4291)
	if c.Cond(0x0) {
		goto L_0800ACF0
	}
	c.Thumb(0x3302)
	c.Thumb(0x42A3)
	if c.Cond(0x1) {
		goto L_0800ACD0
	}
	c.Thumb(0x782B)
	c.Thumb(0x4460)
	c.Thumb(0x18C0)
	c.Thumb(0x0040)
	c.Thumb(0x182D)
	c.Thumb(0x2001)
	c.Thumb(0x806A)
L_0800ACEA:
	c.NT(6)
	c.Thumb(0xBC30)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800ACF0:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_0800ACEA
}

// 0x0800ACF8
func GetLatestLearnedMoves(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(64)
	c.R[15] = 0x0800ACFC
	c.Thumb(0x4B22)
	c.Thumb(0x681A)
	c.Thumb(0x23B1)
	c.Thumb(0x5CD3)
	c.Thumb(0x2203)
	c.Thumb(0x401A)
	c.Thumb(0x3A01)
	c.Thumb(0x1E53)
	c.Thumb(0x419A)
	c.Thumb(0x230A)
	c.Thumb(0xB530)
	c.Thumb(0x0404)
	c.Thumb(0x4250)
	c.Thumb(0x4018)
	c.R[15] = 0x0800AD18
	c.Thumb(0x4B1C)
	c.Thumb(0x0BA4)
	c.Thumb(0x58E4)
	c.R[15] = 0x0800AD1E
	c.Thumb(0x4D1C)
	c.Thumb(0x8823)
	c.Thumb(0x42AB)
	if c.Cond(0x0) {
		goto L_0800AD7A
	}
	c.Thumb(0x1E42)
	c.Thumb(0x4190)
	c.Thumb(0x22A0)
	c.Thumb(0x4240)
	c.Thumb(0x0152)
	c.Thumb(0x4010)
	c.Thumb(0x22C8)
	c.Thumb(0x01D2)
	c.Thumb(0x1880)
	c.Thumb(0x2200)
	goto L_0800AD46
L_0800AD38:
	c.NT(14)
	c.Thumb(0x3201)
	c.Thumb(0x0613)
	c.Thumb(0x0E1A)
	c.Thumb(0x0DDB)
	c.Thumb(0x5B1B)
	c.Thumb(0x42AB)
	if c.Cond(0x0) {
		goto L_0800AD4E
	}
L_0800AD46:
	c.NT(8)
	c.Thumb(0x0A5B)
	c.Thumb(0x025B)
	c.Thumb(0x4283)
	if c.Cond(0xD) {
		goto L_0800AD38
	}
L_0800AD4E:
	c.NT(10)
	c.Thumb(0x2A00)
	if c.Cond(0x0) {
		goto L_0800AD7A
	}
	c.Thumb(0x1C15)
	c.Thumb(0x2A04)
	if c.Cond(0x8) {
		goto L_0800AD80
	}
L_0800AD58:
	c.NT(12)
	c.Thumb(0x2000)
	c.Thumb(0x062D)
	c.Thumb(0x0052)
	c.Thumb(0x3C02)
	c.Thumb(0x0E2D)
	c.Thumb(0x1912)
L_0800AD64:
	c.NT(22)
	c.Thumb(0x8813)
	c.Thumb(0x05DB)
	c.Thumb(0x0044)
	c.Thumb(0x0DDB)
	c.Thumb(0x3001)
	c.Thumb(0x530B)
	c.Thumb(0x0603)
	c.Thumb(0x3A02)
	c.Thumb(0x0E1B)
	c.Thumb(0x429D)
	if c.Cond(0x8) {
		goto L_0800AD64
	}
L_0800AD7A:
	c.NT(6)
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800AD80:
	c.NT(4)
	c.Thumb(0x2504)
	goto L_0800AD58
}

// 0x0800AD90
func GetDefaultMove(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB5F0)
	c.Thumb(0x4647)
	c.Thumb(0x46CE)
	c.Thumb(0x0600)
	c.Thumb(0x0E03)
	c.Thumb(0x0612)
	c.Thumb(0x4698)
	c.Thumb(0x0E13)
	c.Thumb(0x4699)
	c.R[15] = 0x0800ADA6
	c.Thumb(0x4B34)
	c.Thumb(0xB580)
	c.Thumb(0x681F)
	c.Thumb(0x23B1)
	c.Thumb(0x0609)
	c.Thumb(0x0E08)
	c.Thumb(0x5CF9)
	c.Thumb(0x0689)
	c.Thumb(0xB082)
	c.Thumb(0x0F0E)
	c.Thumb(0x2E02)
	if c.Cond(0x9) {
		goto L_0800AE4A
	}
	c.Thumb(0x2400)
L_0800ADBC:
	c.NT(44)
	c.Thumb(0x0023)
	c.Thumb(0x332E)
	c.Thumb(0x009B)
	c.Thumb(0x5DDB)
	c.Thumb(0x079B)
	if c.Cond(0x0) {
		goto L_0800AE4E
	}
	c.Thumb(0x3401)
	c.Thumb(0x2C09)
	if c.Cond(0x1) {
		goto L_0800ADBC
	}
	c.Thumb(0x23B0)
	c.Thumb(0x5CF9)
	c.Thumb(0x3B84)
	c.Thumb(0x434B)
	c.Thumb(0x181B)
	c.R[15] = 0x0800ADDC
	c.Thumb(0x4A27)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x4669)
	c.Thumb(0x5A98)
	c.Thumb(0x466D)
	c.R[14] = 0x0800ADE9
	GetLatestLearnedMoves(c)
	if c.U != 0 {
		if c.U != 0x0800ADE9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2409)
L_0800ADEA:
	c.NT(10)
	c.Thumb(0x0038)
	c.Thumb(0x2300)
	c.Thumb(0x3E03)
	c.Thumb(0x30BA)
	goto L_0800AE00
L_0800ADF4:
	c.NT(12)
	c.Thumb(0x3301)
	c.Thumb(0x061A)
	c.Thumb(0x3004)
	c.Thumb(0x0E12)
	c.Thumb(0x42A2)
	if c.Cond(0x2) {
		goto L_0800AE36
	}
L_0800AE00:
	c.NT(54)
	c.Thumb(0x429E)
	if c.Cond(0xD) {
		goto L_0800AE36
	}
	c.Thumb(0x001A)
	c.Thumb(0x322E)
	c.Thumb(0x0092)
	c.Thumb(0x5DD1)
	c.Thumb(0x078A)
	c.Thumb(0x0F92)
	c.Thumb(0x2A02)
	if c.Cond(0x1) {
		goto L_0800ADF4
	}
	c.Thumb(0x070A)
	c.Thumb(0x0F92)
	c.Thumb(0x4542)
	if c.Cond(0x1) {
		goto L_0800ADF4
	}
	c.Thumb(0x098A)
	if c.Cond(0x0) {
		goto L_0800ADF4
	}
	c.Thumb(0x068A)
	c.Thumb(0x0F92)
	c.Thumb(0x8801)
	c.Thumb(0x0052)
	c.Thumb(0x3301)
	c.Thumb(0x52A9)
	c.Thumb(0x061A)
	c.Thumb(0x3004)
	c.Thumb(0x0E12)
	c.Thumb(0x42A2)
	if c.Cond(0x3) {
		goto L_0800AE00
	}
L_0800AE36:
	c.NT(6)
	c.Thumb(0x464B)
	c.Thumb(0x005B)
	c.Thumb(0x5AE8)
L_0800AE3C:
	c.NT(14)
	c.Thumb(0xB002)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800AE4A:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_0800AE3C
L_0800AE4E:
	c.NT(34)
	c.Thumb(0x23B0)
	c.Thumb(0x5CF9)
	c.Thumb(0x3B84)
	c.Thumb(0x434B)
	c.Thumb(0x181B)
	c.R[15] = 0x0800AE5C
	c.Thumb(0x4A07)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x0624)
	c.Thumb(0x4669)
	c.Thumb(0x5A98)
	c.Thumb(0x0E24)
	c.Thumb(0x466D)
	c.R[14] = 0x0800AE6D
	GetLatestLearnedMoves(c)
	if c.U != 0 {
		if c.U != 0x0800AE6D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2C00)
	if c.Cond(0x1) {
		goto L_0800ADEA
	}
	goto L_0800AE36
}

// 0x0800AE7C
func SaveApprenticeParty(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(34)
	c.Thumb(0xB5F0)
	c.Thumb(0x464E)
	c.Thumb(0x4645)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.R[15] = 0x0800AE8A
	c.Thumb(0x4B45)
	c.Thumb(0x681C)
	c.Thumb(0xB5E0)
	c.Thumb(0x0025)
	c.Thumb(0x35E0)
	c.Thumb(0x002B)
	c.Thumb(0x2200)
	c.Thumb(0x0606)
	c.Thumb(0x1D61)
	c.Thumb(0xB083)
	c.Thumb(0x0E36)
	c.Thumb(0x31FF)
L_0800AE9E:
	c.NT(70)
	c.Thumb(0x601A)
	c.Thumb(0x605A)
	c.Thumb(0x609A)
	c.Thumb(0x330C)
	c.Thumb(0x428B)
	if c.Cond(0x1) {
		goto L_0800AE9E
	}
	c.Thumb(0x23B1)
	c.Thumb(0x466F)
	c.Thumb(0x5CE0)
	c.Thumb(0x0980)
	c.Thumb(0x0083)
	c.Thumb(0x2103)
	c.Thumb(0x50FD)
	c.Thumb(0x3001)
	c.R[14] = 0x0800AEBF
	c.NCallT(0x082E4FD0)
	if c.U != 0 {
		if c.U != 0x0800AEBF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0022)
	c.Thumb(0x0083)
	c.Thumb(0x32EC)
	c.Thumb(0x50FA)
	c.Thumb(0x2103)
	c.Thumb(0x3001)
	c.R[14] = 0x0800AECF
	c.NCallT(0x082E4FD0)
	if c.U != 0 {
		if c.U != 0x0800AECF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0023)
	c.Thumb(0x0080)
	c.Thumb(0x33F8)
	c.Thumb(0x503B)
	c.R[15] = 0x0800AEDA
	c.Thumb(0x4B32)
	c.Thumb(0x469B)
	c.Thumb(0x23B4)
	c.Thumb(0x469C)
	c.Thumb(0x44A4)
	c.Thumb(0x46B2)
	c.Thumb(0x46E8)
	c.Thumb(0x46E1)
	c.Thumb(0x2600)
L_0800AEE8:
	c.NT(76)
	c.Thumb(0x4643)
	c.Thumb(0xCB02)
	c.Thumb(0x4698)
	c.Thumb(0x23B0)
	c.Thumb(0x5CE0)
	c.Thumb(0x464B)
	c.Thumb(0x5D9A)
	c.Thumb(0x23B2)
	c.Thumb(0x5CE3)
	c.Thumb(0x075B)
	c.Thumb(0x0F5B)
	c.Thumb(0x4133)
	c.Thumb(0x2504)
	c.Thumb(0x009B)
	c.Thumb(0x402B)
	c.Thumb(0x411A)
	c.Thumb(0x230F)
	c.Thumb(0x4013)
	c.Thumb(0x222C)
	c.Thumb(0x4342)
	c.Thumb(0x18D2)
	c.Thumb(0x465B)
	c.Thumb(0x321A)
	c.Thumb(0x0052)
	c.Thumb(0x5A98)
	c.Thumb(0x3601)
	c.Thumb(0x8008)
	c.Thumb(0x3102)
	c.R[14] = 0x0800AF25
	GetLatestLearnedMoves(c)
	if c.U != 0 {
		if c.U != 0x0800AF25 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2E03)
	if c.Cond(0x1) {
		goto L_0800AEE8
	}
	c.Thumb(0x4656)
	c.Thumb(0x2E00)
	if c.Cond(0x0) {
		goto L_0800AF72
	}
	c.Thumb(0x0020)
	c.Thumb(0x2100)
	c.Thumb(0x30BA)
	goto L_0800AF46
L_0800AF36:
	c.NT(4)
	c.Thumb(0x2A02)
	if c.Cond(0x0) {
		goto L_0800AF84
	}
L_0800AF3A:
	c.NT(12)
	c.Thumb(0x3101)
	c.Thumb(0x060B)
	c.Thumb(0x3004)
	c.Thumb(0x0E1B)
	c.Thumb(0x429E)
	if c.Cond(0x9) {
		goto L_0800AF72
	}
L_0800AF46:
	c.NT(44)
	c.Thumb(0x000B)
	c.Thumb(0x332E)
	c.Thumb(0x009B)
	c.Thumb(0x5D1B)
	c.Thumb(0x079A)
	c.Thumb(0x071D)
	c.Thumb(0x0F92)
	c.Thumb(0x0FAD)
	c.Thumb(0x2A01)
	if c.Cond(0x1) {
		goto L_0800AF36
	}
	c.Thumb(0x099B)
	if c.Cond(0x0) {
		goto L_0800AF3A
	}
	c.Thumb(0x00AD)
	c.Thumb(0x8802)
	c.Thumb(0x597B)
	c.Thumb(0x3101)
	c.Thumb(0x815A)
	c.Thumb(0x060B)
	c.Thumb(0x3004)
	c.Thumb(0x0E1B)
	c.Thumb(0x429E)
	if c.Cond(0x8) {
		goto L_0800AF46
	}
L_0800AF72:
	c.NT(18)
	c.Thumb(0xB003)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800AF84:
	c.NT(22)
	c.Thumb(0x099A)
	if c.Cond(0x0) {
		goto L_0800AF3A
	}
	c.Thumb(0x00AD)
	c.Thumb(0x069B)
	c.Thumb(0x597D)
	c.Thumb(0x0F9B)
	c.Thumb(0x8802)
	c.Thumb(0x005B)
	c.Thumb(0x18EB)
	c.Thumb(0x805A)
	goto L_0800AF3A
}

// 0x0800AFA4
func CreateApprenticeMenu(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	var jt uint32
	c.NT(30)
	c.Thumb(0xB5F0)
	c.Thumb(0x4645)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x464E)
	c.Thumb(0xB5E0)
	c.Thumb(0x0605)
	c.Thumb(0xB087)
	c.Thumb(0x0E2D)
	c.Thumb(0x2D06)
	if c.Cond(0x8) {
		goto L_0800B076
	}
	c.R[15] = 0x0800AFBE
	c.Thumb(0x4A77)
	c.Thumb(0x00AB)
	c.Thumb(0x58D3)
	jt = c.R[3] &^ 1
	goto Ldispatch
L_0800AFC2:
	c.NT(4)
	c.R[15] = 0x0800AFC6
	c.Thumb(0x4A76)
	c.R[15] = 0x0800AFC8
	c.Thumb(0x4B76)
L_0800AFC6:
	c.NT(24)
	c.Thumb(0x9305)
	c.Thumb(0x2302)
	c.Thumb(0x9303)
	c.Thumb(0x3302)
	c.Thumb(0x469B)
	c.Thumb(0x3304)
	c.Thumb(0x469A)
	c.Thumb(0x330A)
	c.Thumb(0x4699)
	c.Thumb(0x2502)
	c.Thumb(0x9204)
	c.Thumb(0xAE04)
L_0800AFDE:
	c.NT(8)
	c.Thumb(0x2300)
	c.Thumb(0x0037)
	c.Thumb(0x4698)
	c.Thumb(0x2400)
L_0800AFE6:
	c.NT(14)
	c.Thumb(0x2200)
	c.Thumb(0x2001)
	c.Thumb(0x6839)
	c.R[14] = 0x0800AFF1
	c.NCallT(0x081B6BBC)
	if c.U != 0 {
		if c.U != 0x0800AFF1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4580)
	if c.Cond(0xA) {
		goto L_0800AFF6
	}
	c.Thumb(0x4680)
L_0800AFF6:
	c.NT(46)
	c.Thumb(0x3401)
	c.Thumb(0x0624)
	c.Thumb(0x0E24)
	c.Thumb(0x3704)
	c.Thumb(0x42A5)
	if c.Cond(0x1) {
		goto L_0800AFE6
	}
	c.Thumb(0x4640)
	c.R[14] = 0x0800B009
	c.NCallT(0x081A2D44)
	if c.U != 0 {
		if c.U != 0x0800B009 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x25FF)
	c.Thumb(0x4028)
	c.Thumb(0x0007)
	c.Thumb(0x0001)
	c.Thumb(0x4648)
	c.R[14] = 0x0800B017
	c.NCallT(0x081A2D60)
	if c.U != 0 {
		if c.U != 0x0800B017 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x003A)
	c.Thumb(0x465B)
	c.Thumb(0x4651)
	c.Thumb(0x4028)
	c.R[14] = 0x0800B023
	CreateAndShowWindow(c)
	if c.U != 0 {
		if c.U != 0x0800B023 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x0007)
	c.Thumb(0x2500)
	c.R[14] = 0x0800B02D
	c.NCallT(0x0812EF78)
	if c.U != 0 {
		if c.U != 0x0800B02D {
			return
		}
		c.U = 0
	}
L_0800B02C:
	c.NT(68)
	c.Thumb(0x2300)
	c.Thumb(0xCE04)
	c.Thumb(0x9302)
	c.Thumb(0x33FF)
	c.Thumb(0x9301)
	c.Thumb(0x012B)
	c.Thumb(0x3301)
	c.Thumb(0x9300)
	c.Thumb(0x2101)
	c.Thumb(0x2308)
	c.Thumb(0x0038)
	c.Thumb(0x3501)
	c.R[14] = 0x0800B049
	c.NCallT(0x081B5464)
	if c.U != 0 {
		if c.U != 0x0800B049 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x062B)
	c.Thumb(0x0E1B)
	c.Thumb(0x429C)
	if c.Cond(0x8) {
		goto L_0800B02C
	}
	c.Thumb(0x2200)
	c.Thumb(0x9903)
	c.Thumb(0x0038)
	c.R[14] = 0x0800B05B
	c.NCallT(0x08130DD4)
	if c.U != 0 {
		if c.U != 0x0800B05B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2150)
	c.R[15] = 0x0800B060
	c.Thumb(0x4851)
	c.R[14] = 0x0800B063
	c.NCallT(0x081B4C48)
	if c.U != 0 {
		if c.U != 0x0800B063 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0083)
	c.Thumb(0x1818)
	c.Thumb(0x00C0)
	c.Thumb(0x0002)
	c.Thumb(0x2101)
	c.R[15] = 0x0800B070
	c.Thumb(0x4B4E)
	c.Thumb(0x3210)
	c.Thumb(0x5099)
	c.Thumb(0x181B)
	c.Thumb(0x829F)
L_0800B076:
	c.NT(18)
	c.Thumb(0xB007)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B088:
	c.NT(30)
	c.R[15] = 0x0800B08C
	c.Thumb(0x4B48)
	c.Thumb(0x9304)
	c.R[15] = 0x0800B090
	c.Thumb(0x4B48)
	c.Thumb(0x9305)
	c.Thumb(0x2302)
	c.Thumb(0x9303)
	c.Thumb(0x3302)
	c.Thumb(0x469B)
	c.Thumb(0x3304)
	c.Thumb(0x469A)
	c.Thumb(0x330C)
	c.Thumb(0xAE04)
	c.Thumb(0x4699)
	c.Thumb(0x2502)
	goto L_0800AFDE
L_0800B0A6:
	c.NT(6)
	c.R[15] = 0x0800B0AA
	c.Thumb(0x4A43)
	c.R[15] = 0x0800B0AC
	c.Thumb(0x4B43)
	goto L_0800AFC6
L_0800B0AC:
	c.NT(44)
	c.R[15] = 0x0800B0B0
	c.Thumb(0x4D43)
	c.Thumb(0x46AA)
	c.Thumb(0x25B4)
	c.R[15] = 0x0800B0B6
	c.Thumb(0x4B43)
	c.Thumb(0x6819)
	c.Thumb(0x23B2)
	c.Thumb(0x46A9)
	c.Thumb(0x5CC8)
	c.Thumb(0x3B02)
	c.Thumb(0x5CCB)
	c.Thumb(0x4489)
	c.R[15] = 0x0800B0C6
	c.Thumb(0x4940)
	c.Thumb(0x4688)
	c.Thumb(0x2104)
	c.Thumb(0xAE04)
	c.Thumb(0x0034)
	c.Thumb(0x2200)
	c.Thumb(0x468C)
	c.Thumb(0x3D88)
	c.Thumb(0x435D)
	c.Thumb(0x0740)
	c.Thumb(0x0F40)
L_0800B0D8:
	c.NT(66)
	c.Thumb(0x0007)
	c.Thumb(0x464B)
	c.Thumb(0x4117)
	c.Thumb(0x4661)
	c.Thumb(0x5C9B)
	c.Thumb(0x00BF)
	c.Thumb(0x400F)
	c.Thumb(0x413B)
	c.Thumb(0x210F)
	c.Thumb(0x400B)
	c.Thumb(0x4651)
	c.Thumb(0x18EB)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x5ACF)
	c.Thumb(0x00BB)
	c.Thumb(0x19DB)
	c.Thumb(0x005B)
	c.Thumb(0x19DB)
	c.Thumb(0x4443)
	c.Thumb(0x3201)
	c.Thumb(0xC408)
	c.Thumb(0x2A03)
	if c.Cond(0x1) {
		goto L_0800B0D8
	}
	c.Thumb(0x2303)
	c.Thumb(0x9303)
	c.Thumb(0x3303)
	c.Thumb(0x469B)
	c.Thumb(0x469A)
	c.Thumb(0x330C)
	c.Thumb(0x4699)
	c.Thumb(0x2503)
	goto L_0800AFDE
L_0800B11A:
	c.NT(70)
	c.R[15] = 0x0800B11E
	c.Thumb(0x4B29)
	c.Thumb(0x681A)
	c.Thumb(0x23B1)
	c.Thumb(0x5CD3)
	c.Thumb(0x069B)
	c.Thumb(0x0F1B)
	c.Thumb(0x2B02)
	if c.Cond(0x8) {
		goto L_0800B076
	}
	c.R[15] = 0x0800B12E
	c.Thumb(0x4B27)
	c.Thumb(0x6818)
	c.Thumb(0x8842)
	c.Thumb(0x0093)
	c.Thumb(0x189B)
	c.R[15] = 0x0800B138
	c.Thumb(0x4923)
	c.Thumb(0x005B)
	c.Thumb(0x189B)
	c.Thumb(0x8802)
	c.Thumb(0x185B)
	c.Thumb(0x9305)
	c.Thumb(0x0093)
	c.Thumb(0x189B)
	c.Thumb(0x005B)
	c.Thumb(0x189B)
	c.Thumb(0x185B)
	c.Thumb(0x9304)
	c.Thumb(0x2302)
	c.Thumb(0x9303)
	c.Thumb(0x3302)
	c.Thumb(0x469B)
	c.Thumb(0x3304)
	c.Thumb(0x469A)
	c.Thumb(0x330A)
	c.Thumb(0xAE04)
	c.Thumb(0x4699)
	goto L_0800AFDE
L_0800B160:
	c.NT(56)
	c.R[15] = 0x0800B164
	c.Thumb(0x4B19)
	c.Thumb(0x6818)
	c.Thumb(0x8882)
	c.Thumb(0x0053)
	c.Thumb(0x189B)
	c.R[15] = 0x0800B16E
	c.Thumb(0x4918)
	c.Thumb(0x009B)
	c.Thumb(0x189B)
	c.Thumb(0x185B)
	c.Thumb(0x9304)
	c.Thumb(0x88C2)
	c.Thumb(0x0053)
	c.Thumb(0x189B)
	c.Thumb(0x009B)
	c.Thumb(0x189B)
	c.Thumb(0x185B)
	c.Thumb(0x9305)
	c.Thumb(0x2302)
	c.Thumb(0x9303)
	c.Thumb(0x3302)
	c.Thumb(0x469B)
	c.Thumb(0x3304)
	c.Thumb(0x469A)
	c.Thumb(0x3309)
	c.Thumb(0xAE04)
	c.Thumb(0x4699)
	c.Thumb(0x2502)
	goto L_0800AFDE
Ldispatch:
	switch jt {
	case 0x0800AFC2:
		goto L_0800AFC2
	case 0x0800B076:
		goto L_0800B076
	case 0x0800B088:
		goto L_0800B088
	case 0x0800B0A6:
		goto L_0800B0A6
	case 0x0800B0AC:
		goto L_0800B0AC
	case 0x0800B11A:
		goto L_0800B11A
	case 0x0800B160:
		goto L_0800B160
	default:
		t := jt | 1
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallT(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B1D0
func Task_ChooseAnswer(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(26)
	c.Thumb(0x0600)
	c.Thumb(0xB530)
	c.Thumb(0x0E05)
	c.Thumb(0x0D84)
	c.R[15] = 0x0800B1DC
	c.Thumb(0x4B16)
	c.Thumb(0x1964)
	c.Thumb(0x00E4)
	c.Thumb(0x18E4)
	c.Thumb(0x220A)
	c.Thumb(0x5EA3)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800B21C
	}
	c.R[14] = 0x0800B1ED
	c.NCallT(0x0812FDD4)
	if c.U != 0 {
		if c.U != 0x0800B1ED {
			return
		}
		c.U = 0
	}
L_0800B1EC:
	c.NT(12)
	c.Thumb(0x1C83)
	if c.Cond(0x0) {
		goto L_0800B216
	}
	c.Thumb(0x1C43)
	if c.Cond(0x0) {
		goto L_0800B222
	}
	c.Thumb(0x0400)
	c.Thumb(0x0C00)
L_0800B1F8:
	c.NT(22)
	c.R[15] = 0x0800B1FC
	c.Thumb(0x4B0F)
	c.Thumb(0x7B24)
	c.Thumb(0x8018)
	c.Thumb(0x2101)
	c.Thumb(0x0020)
	c.R[14] = 0x0800B207
	c.NCallT(0x0812F860)
	if c.U != 0 {
		if c.U != 0x0800B207 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0020)
	c.R[14] = 0x0800B20D
	c.NCallT(0x081DF994)
	if c.U != 0 {
		if c.U != 0x0800B20D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0028)
	c.R[14] = 0x0800B213
	c.NCallT(0x081B4D48)
	if c.U != 0 {
		if c.U != 0x0800B213 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0800B217
	c.NCallT(0x081A381C)
	if c.U != 0 {
		if c.U != 0x0800B217 {
			return
		}
		c.U = 0
	}
L_0800B216:
	c.NT(6)
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B21C:
	c.NT(4)
	c.R[14] = 0x0800B221
	c.NCallT(0x0812FD64)
	if c.U != 0 {
		if c.U != 0x0800B221 {
			return
		}
		c.U = 0
	}
	goto L_0800B1EC
L_0800B222:
	c.NT(16)
	c.Thumb(0x2208)
	c.Thumb(0x5EA3)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800B216
	}
	c.Thumb(0x3006)
	c.R[14] = 0x0800B231
	c.NCallT(0x081AFA18)
	if c.U != 0 {
		if c.U != 0x0800B231 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x207F)
	goto L_0800B1F8
}

// 0x0800B23C
func CreateAndShowWindow(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(78)
	c.Thumb(0x061B)
	c.Thumb(0xB530)
	c.Thumb(0x0E1D)
	c.Thumb(0x2380)
	c.Thumb(0x0609)
	c.Thumb(0x045B)
	c.Thumb(0x18C9)
	c.Thumb(0x0600)
	c.Thumb(0x18C0)
	c.Thumb(0x0E0B)
	c.Thumb(0x2164)
	c.Thumb(0xB086)
	c.Thumb(0x0612)
	c.Thumb(0x9103)
	c.Thumb(0x0E14)
	c.Thumb(0x3955)
	c.Thumb(0x0E02)
	c.Thumb(0x9102)
	c.Thumb(0x9501)
	c.Thumb(0x2100)
	c.Thumb(0x9400)
	c.Thumb(0xA804)
	c.R[14] = 0x0800B26D
	c.NCallT(0x0813029C)
	if c.U != 0 {
		if c.U != 0x0800B26D {
			return
		}
		c.U = 0
	}
	c.Thumb(0xA804)
	c.R[14] = 0x0800B273
	c.NCallT(0x081DF7C4)
	if c.U != 0 {
		if c.U != 0x0800B273 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x25FF)
	c.Thumb(0x4005)
	c.Thumb(0x0004)
	c.Thumb(0x0028)
	c.R[14] = 0x0800B27F
	c.NCallT(0x081DFB8C)
	if c.U != 0 {
		if c.U != 0x0800B27F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0028)
	c.Thumb(0x2103)
	c.R[14] = 0x0800B287
	c.NCallT(0x081DFA9C)
	if c.U != 0 {
		if c.U != 0x0800B287 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0620)
	c.Thumb(0x0E00)
	c.Thumb(0xB006)
	c.Thumb(0xBC30)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B294
func RemoveAndHideWindow(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(20)
	c.Thumb(0xB510)
	c.Thumb(0x0604)
	c.Thumb(0x2101)
	c.Thumb(0x0E20)
	c.R[14] = 0x0800B2A1
	c.NCallT(0x0812F860)
	if c.U != 0 {
		if c.U != 0x0800B2A1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0E20)
	c.R[14] = 0x0800B2A7
	c.NCallT(0x081DF994)
	if c.U != 0 {
		if c.U != 0x0800B2A7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B2AC
func CreateChooseAnswerTask(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(50)
	c.Thumb(0x0600)
	c.Thumb(0x0609)
	c.Thumb(0xB570)
	c.Thumb(0x0612)
	c.Thumb(0x0E06)
	c.Thumb(0x0E0D)
	c.R[15] = 0x0800B2BC
	c.Thumb(0x4809)
	c.Thumb(0x2150)
	c.Thumb(0x0E14)
	c.R[14] = 0x0800B2C3
	c.NCallT(0x081B4C48)
	if c.U != 0 {
		if c.U != 0x0800B2C3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0082)
	c.R[15] = 0x0800B2C8
	c.Thumb(0x4B07)
	c.Thumb(0x1812)
	c.Thumb(0x00D2)
	c.Thumb(0x189B)
	c.Thumb(0x2203)
	c.Thumb(0x42AA)
	c.Thumb(0x4192)
	c.Thumb(0x4252)
	c.Thumb(0x821E)
	c.Thumb(0x825A)
	c.Thumb(0x829C)
	c.Thumb(0xBC70)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B2E8
func CallApprenticeFunction(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.R[15] = 0x0800B2EC
	c.Thumb(0x4A04)
	c.Thumb(0xB500)
	c.Thumb(0x8812)
	c.R[15] = 0x0800B2F2
	c.Thumb(0x4B04)
	c.Thumb(0x0092)
	c.Thumb(0x58D3)
	c.R[14] = 0x0800B2F9
	stub_0800BDD0(c)
	if c.U != 0 {
		if c.U != 0x0800B2F9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B304
func Script_ResetPlayerApprentice(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(40)
	c.Thumb(0xB510)
	c.R[14] = 0x0800B30B
	SetApprenticeId(c)
	if c.U != 0 {
		if c.U != 0x0800B30B {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x0800B30E
	c.Thumb(0x4B0F)
	c.Thumb(0x681C)
	c.Thumb(0x2200)
	c.Thumb(0x23B1)
	c.Thumb(0x0021)
	c.Thumb(0x2007)
	c.Thumb(0x54E2)
	c.Thumb(0x31B1)
	c.Thumb(0x784B)
	c.Thumb(0x4383)
	c.Thumb(0x704B)
	c.Thumb(0x23B4)
	c.Thumb(0x52E2)
	c.Thumb(0x3302)
	c.Thumb(0x54E2)
	c.Thumb(0x2000)
	c.Thumb(0x2300)
	c.Thumb(0x3109)
L_0800B32E:
	c.NT(24)
	c.Thumb(0x001A)
	c.Thumb(0x322E)
	c.Thumb(0x0092)
	c.Thumb(0x3301)
	c.Thumb(0x5510)
	c.Thumb(0x8008)
	c.Thumb(0x3104)
	c.Thumb(0x2B09)
	if c.Cond(0x1) {
		goto L_0800B32E
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B34C
func Script_GivenApprenticeLvlMode(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.R[15] = 0x0800B350
	c.Thumb(0x4B05)
	c.Thumb(0x6819)
	c.Thumb(0x23B1)
	c.Thumb(0x5CC9)
	c.Thumb(0x3BAE)
	c.Thumb(0x400B)
	c.Thumb(0x1E59)
	c.Thumb(0x418B)
	c.R[15] = 0x0800B360
	c.Thumb(0x4A02)
	c.Thumb(0x8013)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B36C
func Script_SetApprenticeLvlMode(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.R[15] = 0x0800B370
	c.Thumb(0x4B07)
	c.Thumb(0x6818)
	c.R[15] = 0x0800B374
	c.Thumb(0x4B07)
	c.Thumb(0x881A)
	c.Thumb(0x2303)
	c.Thumb(0x21B1)
	c.Thumb(0xB510)
	c.Thumb(0x001C)
	c.Thumb(0x401A)
	c.Thumb(0x5C43)
	c.Thumb(0x43A3)
	c.Thumb(0x4313)
	c.Thumb(0x5443)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B394
func Script_SetApprenticeId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0xB500)
	c.R[14] = 0x0800B39B
	SetApprenticeId(c)
	if c.U != 0 {
		if c.U != 0x0800B39B {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B3A0
func Script_SetRandomQuestionData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0xB500)
	c.R[14] = 0x0800B3A7
	SetRandomQuestionData(c)
	if c.U != 0 {
		if c.U != 0x0800B3A7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B3AC
func IncrementQuestionsAnswered(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(34)
	c.Thumb(0x20B1)
	c.Thumb(0x220F)
	c.R[15] = 0x0800B3B4
	c.Thumb(0x4B07)
	c.Thumb(0x681B)
	c.Thumb(0x469C)
	c.Thumb(0x5C1B)
	c.Thumb(0x0699)
	c.Thumb(0x0F09)
	c.Thumb(0x3101)
	c.Thumb(0x400A)
	c.Thumb(0x213C)
	c.Thumb(0x0092)
	c.Thumb(0x438B)
	c.Thumb(0x4313)
	c.Thumb(0x4662)
	c.Thumb(0x5413)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B3D4
func GetNumApprenticePartyMonsAssigned(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.R[15] = 0x0800B3D8
	c.Thumb(0x4B04)
	c.Thumb(0x6819)
	c.Thumb(0x23B1)
	c.Thumb(0x5CCB)
	c.R[15] = 0x0800B3E0
	c.Thumb(0x4A03)
	c.Thumb(0x069B)
	c.Thumb(0x0F1B)
	c.Thumb(0x8013)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B3F0
func IsFinalQuestion(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.R[15] = 0x0800B3F4
	c.Thumb(0x4B08)
	c.Thumb(0x6819)
	c.Thumb(0x23B1)
	c.Thumb(0x5CCB)
	c.Thumb(0x069B)
	c.Thumb(0x0F1B)
	c.Thumb(0x2200)
	c.Thumb(0x2B03)
	if c.Cond(0x4) {
		goto L_0800B40E
	}
	c.Thumb(0x332B)
	c.Thumb(0x009B)
	c.Thumb(0x5C5A)
	c.Thumb(0x0792)
	c.Thumb(0x4253)
	c.Thumb(0x415A)
L_0800B40E:
	c.NT(6)
	c.R[15] = 0x0800B412
	c.Thumb(0x4B02)
	c.Thumb(0x801A)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B41C
func Script_CreateApprenticeMenu(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0xB500)
	c.R[15] = 0x0800B422
	c.Thumb(0x4B03)
	c.Thumb(0x7818)
	c.R[14] = 0x0800B427
	CreateApprenticeMenu(c)
	if c.U != 0 {
		if c.U != 0x0800B427 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B430
func Task_WaitForPrintingMessage(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0xB510)
	c.Thumb(0x0600)
	c.Thumb(0x0E04)
	c.R[14] = 0x0800B43B
	c.NCallT(0x0812E910)
	if c.U != 0 {
		if c.U != 0x0800B43B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_0800B444
	}
L_0800B43E:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B444:
	c.NT(38)
	c.Thumb(0x0020)
	c.R[14] = 0x0800B44B
	c.NCallT(0x081B4D48)
	if c.U != 0 {
		if c.U != 0x0800B44B {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x0800B44E
	c.Thumb(0x4B0A)
	c.Thumb(0x881B)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0800B46E
	}
	c.Thumb(0x2101)
	c.R[15] = 0x0800B458
	c.Thumb(0x4808)
	c.R[14] = 0x0800B45B
	c.NCallT(0x081B4C48)
	if c.U != 0 {
		if c.U != 0x0800B45B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0082)
	c.R[15] = 0x0800B460
	c.Thumb(0x4B07)
	c.Thumb(0x1812)
	c.Thumb(0x00D2)
	c.Thumb(0x189B)
	c.R[15] = 0x0800B468
	c.Thumb(0x4A06)
	c.Thumb(0x811A)
	c.Thumb(0x0C12)
	c.Thumb(0x815A)
	goto L_0800B43E
L_0800B46E:
	c.NT(4)
	c.R[14] = 0x0800B473
	c.NCallT(0x081A381C)
	if c.U != 0 {
		if c.U != 0x0800B473 {
			return
		}
		c.U = 0
	}
	goto L_0800B43E
}

// 0x0800B484
func PrintApprenticeMessage(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	var jt uint32
	c.NT(12)
	c.R[15] = 0x0800B488
	c.Thumb(0x4B46)
	c.Thumb(0x881B)
	c.Thumb(0xB500)
	c.Thumb(0x2B10)
	if c.Cond(0x9) {
		goto L_0800B490
	}
	goto L_0800B59A
L_0800B490:
	c.NT(8)
	c.R[15] = 0x0800B494
	c.Thumb(0x4A44)
	c.Thumb(0x009B)
	c.Thumb(0x58D3)
	jt = c.R[3] &^ 1
	goto Ldispatch
L_0800B498:
	c.NT(2)
	c.R[15] = 0x0800B49C
	c.Thumb(0x4B43)
L_0800B49A:
	c.NT(14)
	c.R[15] = 0x0800B49E
	c.Thumb(0x4A44)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C8A)
	c.Thumb(0x00D2)
	c.Thumb(0x189B)
	c.Thumb(0x6859)
L_0800B4A8:
	c.NT(14)
	c.R[15] = 0x0800B4AC
	c.Thumb(0x4841)
	c.R[14] = 0x0800B4AF
	c.NCallT(0x081B4728)
	if c.U != 0 {
		if c.U != 0x0800B4AF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2001)
	c.R[14] = 0x0800B4B5
	c.NCallT(0x0812E988)
	if c.U != 0 {
		if c.U != 0x0800B4B5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2101)
	c.R[15] = 0x0800B4BA
	c.Thumb(0x483F)
	c.R[14] = 0x0800B4BD
	c.NCallT(0x081B4C48)
	if c.U != 0 {
		if c.U != 0x0800B4BD {
			return
		}
		c.U = 0
	}
L_0800B4BC:
	c.NT(4)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B4C0:
	c.NT(22)
	c.R[15] = 0x0800B4C4
	c.Thumb(0x4A3A)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C89)
	c.Thumb(0x008A)
	c.Thumb(0x1852)
	c.R[15] = 0x0800B4D0
	c.Thumb(0x4B3A)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x6919)
	goto L_0800B4A8
L_0800B4D6:
	c.NT(16)
	c.R[15] = 0x0800B4DA
	c.Thumb(0x4A35)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C8A)
	c.R[15] = 0x0800B4E2
	c.Thumb(0x4B37)
	c.Thumb(0x0112)
	c.Thumb(0x58D1)
	goto L_0800B4A8
L_0800B4E6:
	c.NT(18)
	c.R[15] = 0x0800B4EA
	c.Thumb(0x4A31)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C8A)
	c.R[15] = 0x0800B4F2
	c.Thumb(0x4B33)
	c.Thumb(0x0112)
	c.Thumb(0x189B)
	c.Thumb(0x6859)
	goto L_0800B4A8
L_0800B4F8:
	c.NT(18)
	c.R[15] = 0x0800B4FC
	c.Thumb(0x4A2C)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C8A)
	c.R[15] = 0x0800B504
	c.Thumb(0x4B2E)
	c.Thumb(0x0112)
	c.Thumb(0x189B)
	c.Thumb(0x6899)
	goto L_0800B4A8
L_0800B50A:
	c.NT(18)
	c.R[15] = 0x0800B50E
	c.Thumb(0x4A28)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C8A)
	c.R[15] = 0x0800B516
	c.Thumb(0x4B2A)
	c.Thumb(0x0112)
	c.Thumb(0x189B)
	c.Thumb(0x68D9)
	goto L_0800B4A8
L_0800B51C:
	c.NT(2)
	c.R[15] = 0x0800B520
	c.Thumb(0x4B28)
L_0800B51E:
	c.NT(14)
	c.R[15] = 0x0800B522
	c.Thumb(0x4A23)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C8A)
	c.Thumb(0x00D2)
	c.Thumb(0x58D1)
	goto L_0800B4A8
L_0800B52C:
	c.NT(4)
	c.R[15] = 0x0800B530
	c.Thumb(0x4B24)
	goto L_0800B49A
L_0800B530:
	c.NT(4)
	c.R[15] = 0x0800B534
	c.Thumb(0x4B24)
	goto L_0800B51E
L_0800B534:
	c.NT(4)
	c.R[15] = 0x0800B538
	c.Thumb(0x4B23)
	goto L_0800B49A
L_0800B538:
	c.NT(4)
	c.R[15] = 0x0800B53C
	c.Thumb(0x4B23)
	goto L_0800B51E
L_0800B53C:
	c.NT(4)
	c.R[15] = 0x0800B540
	c.Thumb(0x4B22)
	goto L_0800B49A
L_0800B540:
	c.NT(20)
	c.R[15] = 0x0800B544
	c.Thumb(0x4B1A)
	c.Thumb(0x6819)
	c.Thumb(0x23B0)
	c.Thumb(0x5CC9)
	c.Thumb(0x008B)
	c.Thumb(0x185B)
	c.R[15] = 0x0800B550
	c.Thumb(0x4A1A)
	c.Thumb(0x009B)
	c.Thumb(0x5899)
	goto L_0800B4A8
L_0800B554:
	c.NT(4)
	c.R[15] = 0x0800B558
	c.Thumb(0x4B14)
	goto L_0800B51E
L_0800B558:
	c.NT(22)
	c.R[15] = 0x0800B55C
	c.Thumb(0x4A14)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C89)
	c.Thumb(0x008A)
	c.Thumb(0x1852)
	c.R[15] = 0x0800B568
	c.Thumb(0x4B14)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x68D9)
	goto L_0800B4A8
L_0800B56E:
	c.NT(22)
	c.R[15] = 0x0800B572
	c.Thumb(0x4A0F)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C89)
	c.Thumb(0x008A)
	c.Thumb(0x1852)
	c.R[15] = 0x0800B57E
	c.Thumb(0x4B0F)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x6859)
	goto L_0800B4A8
L_0800B584:
	c.NT(22)
	c.R[15] = 0x0800B588
	c.Thumb(0x4A09)
	c.Thumb(0x6811)
	c.Thumb(0x22B0)
	c.Thumb(0x5C89)
	c.Thumb(0x008A)
	c.Thumb(0x1852)
	c.R[15] = 0x0800B594
	c.Thumb(0x4B09)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x6899)
	goto L_0800B4A8
L_0800B59A:
	c.NT(4)
	c.R[14] = 0x0800B59F
	c.NCallT(0x081A381C)
	if c.U != 0 {
		if c.U != 0x0800B59F {
			return
		}
		c.U = 0
	}
	goto L_0800B4BC
Ldispatch:
	switch jt {
	case 0x0800B498:
		goto L_0800B498
	case 0x0800B4C0:
		goto L_0800B4C0
	case 0x0800B4D6:
		goto L_0800B4D6
	case 0x0800B4E6:
		goto L_0800B4E6
	case 0x0800B4F8:
		goto L_0800B4F8
	case 0x0800B50A:
		goto L_0800B50A
	case 0x0800B51C:
		goto L_0800B51C
	case 0x0800B52C:
		goto L_0800B52C
	case 0x0800B530:
		goto L_0800B530
	case 0x0800B534:
		goto L_0800B534
	case 0x0800B538:
		goto L_0800B538
	case 0x0800B53C:
		goto L_0800B53C
	case 0x0800B540:
		goto L_0800B540
	case 0x0800B554:
		goto L_0800B554
	case 0x0800B558:
		goto L_0800B558
	case 0x0800B56E:
		goto L_0800B56E
	case 0x0800B584:
		goto L_0800B584
	default:
		t := jt | 1
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallT(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B5CC
func Script_PrintApprenticeMessage(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.Thumb(0xB500)
	c.R[14] = 0x0800B5D3
	c.NCallT(0x081A3708)
	if c.U != 0 {
		if c.U != 0x0800B5D3 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0800B5D7
	c.NCallT(0x080E4FFC)
	if c.U != 0 {
		if c.U != 0x0800B5D7 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0800B5DB
	c.NCallT(0x080F5514)
	if c.U != 0 {
		if c.U != 0x0800B5DB {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0800B5DF
	c.NCallT(0x080F5B48)
	if c.U != 0 {
		if c.U != 0x0800B5DF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2101)
	c.Thumb(0x2000)
	c.R[14] = 0x0800B5E7
	c.NCallT(0x0812EAFC)
	if c.U != 0 {
		if c.U != 0x0800B5E7 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0800B5EB
	PrintApprenticeMessage(c)
	if c.U != 0 {
		if c.U != 0x0800B5EB {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B5F0
func ApprenticeGetQuestion(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.R[15] = 0x0800B5F4
	c.Thumb(0x4B10)
	c.Thumb(0x6819)
	c.Thumb(0x23B1)
	c.Thumb(0x5CCB)
	c.Thumb(0x069B)
	c.Thumb(0x2202)
	c.Thumb(0x0F1B)
	c.Thumb(0x2B02)
	if c.Cond(0x9) {
		goto L_0800B608
	}
	c.Thumb(0x3203)
	c.Thumb(0x2B0B)
	if c.Cond(0x9) {
		goto L_0800B60E
	}
L_0800B608:
	c.NT(6)
	c.R[15] = 0x0800B60C
	c.Thumb(0x4B0B)
	c.Thumb(0x801A)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B60E:
	c.NT(28)
	c.Thumb(0x332B)
	c.Thumb(0x009B)
	c.Thumb(0x5C5A)
	c.Thumb(0x0792)
	c.Thumb(0x0F92)
	c.Thumb(0x2A02)
	if c.Cond(0x0) {
		goto L_0800B62A
	}
	c.Thumb(0x2A03)
	if c.Cond(0x0) {
		goto L_0800B62E
	}
	c.Thumb(0x3A01)
	c.Thumb(0x1E53)
	c.Thumb(0x419A)
	c.Thumb(0x3204)
	goto L_0800B608
L_0800B62A:
	c.NT(4)
	c.Thumb(0x2203)
	goto L_0800B608
L_0800B62E:
	c.NT(4)
	c.Thumb(0x2201)
	goto L_0800B608
}

// 0x0800B63C
func SetApprenticePartyMon(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.R[15] = 0x0800B640
	c.Thumb(0x4B0B)
	c.Thumb(0x881B)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0800B668
	}
	c.R[15] = 0x0800B648
	c.Thumb(0x4B0A)
	c.Thumb(0x681A)
	c.R[15] = 0x0800B64C
	c.Thumb(0x4B0A)
	c.Thumb(0x7819)
	c.Thumb(0x2301)
	c.Thumb(0x408B)
	c.Thumb(0x21B2)
	c.Thumb(0x2007)
	c.Thumb(0x5C51)
	c.Thumb(0x0749)
	c.Thumb(0x0F49)
	c.Thumb(0x32B1)
	c.Thumb(0x430B)
	c.Thumb(0x7851)
	c.Thumb(0x4003)
	c.Thumb(0x4381)
	c.Thumb(0x430B)
	c.Thumb(0x7053)
L_0800B668:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B678
func SetApprenticeMonMove(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(46)
	c.R[15] = 0x0800B67C
	c.Thumb(0x4B0D)
	c.Thumb(0x681A)
	c.Thumb(0x23B1)
	c.Thumb(0x5CD3)
	c.Thumb(0x069B)
	c.Thumb(0x0F1B)
	c.Thumb(0x2B02)
	if c.Cond(0x9) {
		goto L_0800B6A6
	}
	c.Thumb(0x3B03)
	c.R[15] = 0x0800B68E
	c.Thumb(0x490A)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x332E)
	c.Thumb(0x8809)
	c.Thumb(0x009B)
	c.Thumb(0x5C98)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_0800B6A8
	}
	c.Thumb(0x213F)
	c.Thumb(0x4001)
	c.Thumb(0x2040)
	c.Thumb(0x4301)
	c.Thumb(0x5499)
L_0800B6A6:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B6A8:
	c.NT(8)
	c.Thumb(0x213F)
	c.Thumb(0x4001)
	c.Thumb(0x5499)
	goto L_0800B6A6
}

// 0x0800B6B8
func InitQuestionData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.Thumb(0xB570)
	c.Thumb(0x46C6)
	c.Thumb(0x2300)
	c.Thumb(0xB500)
	c.R[15] = 0x0800B6C4
	c.Thumb(0x4C57)
	c.Thumb(0x6821)
	c.Thumb(0xB081)
L_0800B6C6:
	c.NT(14)
	c.Thumb(0x001A)
	c.Thumb(0x322E)
	c.Thumb(0x0092)
	c.Thumb(0x5C52)
	c.Thumb(0x0792)
	if c.Cond(0x1) {
		goto L_0800B6D4
	}
	goto L_0800B7B8
L_0800B6D4:
	c.NT(8)
	c.Thumb(0x3301)
	c.Thumb(0x2B09)
	if c.Cond(0x1) {
		goto L_0800B6C6
	}
	c.Thumb(0x001D)
L_0800B6DC:
	c.NT(26)
	c.Thumb(0x2008)
	c.R[14] = 0x0800B6E3
	c.NCallT(0x081292A4)
	if c.U != 0 {
		if c.U != 0x0800B6E3 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x0800B6E6
	c.Thumb(0x4B50)
	c.Thumb(0x6018)
	c.R[15] = 0x0800B6EA
	c.Thumb(0x4B50)
	c.Thumb(0x881B)
	c.Thumb(0x4684)
	c.Thumb(0x2B02)
	if c.Cond(0x0) {
		goto L_0800B77C
	}
	c.Thumb(0x2B03)
	if c.Cond(0x0) {
		goto L_0800B704
	}
	c.Thumb(0x2B04)
	if c.Cond(0x0) {
		goto L_0800B7BE
	}
L_0800B6F8:
	c.NT(12)
	c.Thumb(0xB001)
	c.Thumb(0xBC40)
	c.Thumb(0x46B0)
	c.Thumb(0xBC70)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B704:
	c.NT(118)
	c.Thumb(0x6824)
	c.Thumb(0x33AE)
	c.Thumb(0x5CE2)
	c.Thumb(0x0692)
	c.Thumb(0x0F12)
	c.Thumb(0x2A02)
	if c.Cond(0x9) {
		goto L_0800B6F8
	}
	c.Thumb(0x1CAB)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x4293)
	if c.Cond(0x3) {
		goto L_0800B6F8
	}
	c.Thumb(0x322B)
	c.Thumb(0x0093)
	c.Thumb(0x5D1A)
	c.Thumb(0x001E)
	c.Thumb(0x0793)
	c.Thumb(0x0F9B)
	c.Thumb(0x2B02)
	if c.Cond(0x1) {
		goto L_0800B6F8
	}
	c.Thumb(0x0712)
	c.Thumb(0x0F90)
	c.Thumb(0x1823)
	c.Thumb(0x33B4)
	c.Thumb(0x7819)
	c.Thumb(0x23B2)
	c.Thumb(0x5CE3)
	c.Thumb(0x075B)
	c.Thumb(0x0F5B)
	c.Thumb(0x4103)
	c.Thumb(0x2201)
	c.Thumb(0x4013)
	c.Thumb(0x009B)
	c.Thumb(0x4119)
	c.Thumb(0x230F)
	c.Thumb(0x4019)
	c.Thumb(0x33A1)
	c.Thumb(0x5CE3)
	c.Thumb(0x001D)
	c.Thumb(0x232C)
	c.Thumb(0x435D)
	c.Thumb(0x186B)
	c.R[15] = 0x0800B75C
	c.Thumb(0x4A34)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x5A9B)
	c.Thumb(0x4662)
	c.Thumb(0x8013)
	c.Thumb(0x9200)
	c.Thumb(0x5DA2)
	c.Thumb(0x0692)
	c.Thumb(0x0F92)
	c.R[14] = 0x0800B771
	GetDefaultMove(c)
	if c.U != 0 {
		if c.U != 0x0800B771 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x19A4)
	c.Thumb(0x9A00)
	c.Thumb(0x8863)
	c.Thumb(0x8090)
	c.Thumb(0x80D3)
	goto L_0800B6F8
L_0800B77C:
	c.NT(60)
	c.Thumb(0x6822)
	c.Thumb(0x33AF)
	c.Thumb(0x5CD3)
	c.Thumb(0x069B)
	c.Thumb(0x0F1B)
	c.Thumb(0x2B02)
	if c.Cond(0x8) {
		goto L_0800B6F8
	}
	c.Thumb(0x18D3)
	c.Thumb(0x33B4)
	c.Thumb(0x7818)
	c.Thumb(0x23B0)
	c.Thumb(0x5CD4)
	c.Thumb(0x3B84)
	c.Thumb(0x4363)
	c.Thumb(0x4664)
	c.Thumb(0x0902)
	c.Thumb(0x189A)
	c.R[15] = 0x0800B7A2
	c.Thumb(0x4923)
	c.Thumb(0x321A)
	c.Thumb(0x0052)
	c.Thumb(0x5A52)
	c.Thumb(0x8062)
	c.Thumb(0x220F)
	c.Thumb(0x4002)
	c.Thumb(0x189B)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x5A5B)
	c.Thumb(0x8023)
	goto L_0800B6F8
L_0800B7B8:
	c.NT(6)
	c.Thumb(0x061B)
	c.Thumb(0x0E1D)
	goto L_0800B6DC
L_0800B7BE:
	c.NT(26)
	c.Thumb(0x6821)
	c.Thumb(0x33AD)
	c.Thumb(0x5CCA)
	c.Thumb(0x0692)
	c.Thumb(0x0F12)
	c.Thumb(0x2A02)
	if c.Cond(0x9) {
		goto L_0800B6F8
	}
	c.Thumb(0x1CAB)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x4293)
	if c.Cond(0x2) {
		goto L_0800B7D8
	}
	goto L_0800B6F8
L_0800B7D8:
	c.NT(16)
	c.Thumb(0x322B)
	c.Thumb(0x0092)
	c.Thumb(0x5C52)
	c.Thumb(0x0793)
	c.Thumb(0x0F9B)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_0800B7E8
	}
	goto L_0800B6F8
L_0800B7E8:
	c.NT(54)
	c.Thumb(0x0712)
	c.Thumb(0x0F92)
	c.Thumb(0x1888)
	c.Thumb(0x30B4)
	c.Thumb(0x7804)
	c.Thumb(0x20B2)
	c.Thumb(0x5C08)
	c.Thumb(0x0740)
	c.Thumb(0x0F40)
	c.Thumb(0x4110)
	c.Thumb(0x4003)
	c.Thumb(0x20B0)
	c.Thumb(0x009B)
	c.Thumb(0x411C)
	c.Thumb(0x232C)
	c.Thumb(0x5C08)
	c.Thumb(0x210F)
	c.Thumb(0x4343)
	c.Thumb(0x4021)
	c.Thumb(0x185B)
	c.R[15] = 0x0800B814
	c.Thumb(0x4A06)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x5A9B)
	c.Thumb(0x4662)
	c.Thumb(0x8013)
	goto L_0800B6F8
}

// 0x0800B830
func FreeQuestionData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.Thumb(0xB510)
	c.R[15] = 0x0800B836
	c.Thumb(0x4C04)
	c.Thumb(0x6820)
	c.R[14] = 0x0800B83B
	c.NCallT(0x081292E8)
	if c.U != 0 {
		if c.U != 0x0800B83B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x6023)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B848
func ApprenticeBufferString(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	var jt uint32
	c.NT(36)
	c.Thumb(0xB510)
	c.R[15] = 0x0800B84E
	c.Thumb(0x4B4D)
	c.Thumb(0x881B)
	c.Thumb(0xB084)
	c.Thumb(0x2B02)
	if c.Cond(0x8) {
		goto L_0800B884
	}
	c.R[15] = 0x0800B858
	c.Thumb(0x4A4B)
	c.Thumb(0x009B)
	c.Thumb(0x589B)
	c.Thumb(0x001C)
	c.R[15] = 0x0800B860
	c.Thumb(0x4B4A)
	c.Thumb(0x881B)
	c.Thumb(0x2B09)
	if c.Cond(0x8) {
		goto L_0800B884
	}
	c.R[15] = 0x0800B868
	c.Thumb(0x4A49)
	c.Thumb(0x009B)
	c.Thumb(0x58D3)
	jt = c.R[3] &^ 1
	goto Ldispatch
L_0800B86C:
	c.NT(6)
	c.R[15] = 0x0800B870
	c.Thumb(0x4B48)
	c.Thumb(0x681B)
	c.Thumb(0x881B)
L_0800B872:
	c.NT(16)
	c.Thumb(0x0099)
	c.Thumb(0x18C9)
	c.Thumb(0x0049)
	c.Thumb(0x18C9)
	c.R[15] = 0x0800B87E
	c.Thumb(0x4B46)
	c.Thumb(0x0020)
	c.Thumb(0x18C9)
	c.R[14] = 0x0800B885
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B885 {
			return
		}
		c.U = 0
	}
L_0800B884:
	c.NT(8)
	c.Thumb(0xB004)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800B88C:
	c.NT(8)
	c.R[15] = 0x0800B890
	c.Thumb(0x4B40)
	c.Thumb(0x681B)
	c.Thumb(0x885B)
	goto L_0800B872
L_0800B894:
	c.NT(50)
	c.R[15] = 0x0800B898
	c.Thumb(0x4B40)
	c.Thumb(0x6819)
	c.Thumb(0x23B1)
	c.Thumb(0x5CCB)
	c.Thumb(0x223F)
	c.Thumb(0x0018)
	c.Thumb(0x4390)
	c.Thumb(0x28C0)
	if c.Cond(0x0) {
		goto L_0800B970
	}
	c.Thumb(0x099A)
	c.Thumb(0x188B)
	c.Thumb(0x33B4)
	c.Thumb(0x7818)
	c.Thumb(0x23B2)
	c.Thumb(0x5CCB)
	c.Thumb(0x075B)
	c.Thumb(0x0F5B)
	c.Thumb(0x4113)
	c.Thumb(0x2204)
	c.Thumb(0x009B)
	c.Thumb(0x4013)
	c.Thumb(0x4118)
	c.Thumb(0x0003)
	c.Thumb(0x200F)
	c.Thumb(0x4018)
L_0800B8C6:
	c.NT(20)
	c.Thumb(0x23B0)
	c.Thumb(0x5CC9)
	c.Thumb(0x3B84)
	c.Thumb(0x434B)
	c.Thumb(0x181B)
	c.R[15] = 0x0800B8D4
	c.Thumb(0x4A32)
	c.Thumb(0x331A)
	c.Thumb(0x005B)
	c.Thumb(0x5A9B)
	goto L_0800B872
L_0800B8DA:
	c.NT(24)
	c.R[15] = 0x0800B8DE
	c.Thumb(0x4B2F)
	c.Thumb(0x681A)
	c.Thumb(0x23B1)
	c.Thumb(0x5CD2)
	c.Thumb(0x3BAE)
	c.Thumb(0x4013)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_0800B974
	}
	c.Thumb(0x0020)
	c.R[15] = 0x0800B8F0
	c.Thumb(0x492C)
	c.R[14] = 0x0800B8F3
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B8F3 {
			return
		}
		c.U = 0
	}
	goto L_0800B884
L_0800B8F4:
	c.NT(18)
	c.R[15] = 0x0800B8F8
	c.Thumb(0x4B28)
	c.Thumb(0x6818)
	c.Thumb(0x3005)
	c.Thumb(0x30FF)
	c.R[14] = 0x0800B901
	c.NCallT(0x0808B690)
	if c.U != 0 {
		if c.U != 0x0800B901 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0020)
	c.R[15] = 0x0800B906
	c.Thumb(0x4928)
	c.R[14] = 0x0800B909
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B909 {
			return
		}
		c.U = 0
	}
	goto L_0800B884
L_0800B90A:
	c.NT(30)
	c.R[15] = 0x0800B90E
	c.Thumb(0x4B23)
	c.Thumb(0x681A)
	c.Thumb(0x23B0)
	c.Thumb(0x2158)
	c.Thumb(0x5CD3)
	c.Thumb(0x4359)
	c.R[15] = 0x0800B91A
	c.Thumb(0x4B24)
	c.Thumb(0x4668)
	c.Thumb(0x18C9)
	c.Thumb(0x2202)
	c.R[14] = 0x0800B923
	c.NCallT(0x0810FEF8)
	if c.U != 0 {
		if c.U != 0x0800B923 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4669)
	c.Thumb(0x0020)
	c.R[14] = 0x0800B92B
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B92B {
			return
		}
		c.U = 0
	}
	goto L_0800B884
L_0800B92C:
	c.NT(30)
	c.R[15] = 0x0800B930
	c.Thumb(0x4B1A)
	c.Thumb(0x681A)
	c.Thumb(0x23B1)
	c.Thumb(0x5CD3)
	c.Thumb(0x069B)
	c.Thumb(0x0F1B)
	c.Thumb(0x332B)
	c.Thumb(0x009B)
	c.Thumb(0x18D2)
	c.Thumb(0x8850)
	c.R[14] = 0x0800B945
	c.NCallT(0x0811A7A0)
	if c.U != 0 {
		if c.U != 0x0800B945 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0001)
	c.Thumb(0x0020)
	c.R[14] = 0x0800B94D
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B94D {
			return
		}
		c.U = 0
	}
	goto L_0800B884
L_0800B94E:
	c.NT(6)
	c.R[15] = 0x0800B952
	c.Thumb(0x4B10)
	c.Thumb(0x681B)
	c.Thumb(0x88DB)
L_0800B954:
	c.NT(18)
	c.Thumb(0x0059)
	c.Thumb(0x18C9)
	c.Thumb(0x0089)
	c.Thumb(0x18C9)
	c.R[15] = 0x0800B960
	c.Thumb(0x4B13)
	c.Thumb(0x0020)
	c.Thumb(0x18C9)
	c.R[14] = 0x0800B967
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B967 {
			return
		}
		c.U = 0
	}
	goto L_0800B884
L_0800B968:
	c.NT(8)
	c.R[15] = 0x0800B96C
	c.Thumb(0x4B09)
	c.Thumb(0x681B)
	c.Thumb(0x889B)
	goto L_0800B954
L_0800B970:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_0800B8C6
L_0800B974:
	c.NT(8)
	c.Thumb(0x0020)
	c.R[15] = 0x0800B97A
	c.Thumb(0x490E)
	c.R[14] = 0x0800B97D
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800B97D {
			return
		}
		c.U = 0
	}
	goto L_0800B884
Ldispatch:
	switch jt {
	case 0x0800B86C:
		goto L_0800B86C
	case 0x0800B88C:
		goto L_0800B88C
	case 0x0800B894:
		goto L_0800B894
	case 0x0800B8DA:
		goto L_0800B8DA
	case 0x0800B8F4:
		goto L_0800B8F4
	case 0x0800B90A:
		goto L_0800B90A
	case 0x0800B92C:
		goto L_0800B92C
	case 0x0800B94E:
		goto L_0800B94E
	case 0x0800B968:
		goto L_0800B968
	default:
		t := jt | 1
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallT(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B9B4
func SetLeadApprenticeMon(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0x21B1)
	c.R[15] = 0x0800B9BA
	c.Thumb(0x4B07)
	c.Thumb(0x6818)
	c.R[15] = 0x0800B9BE
	c.Thumb(0x4B07)
	c.Thumb(0x881A)
	c.Thumb(0x5C43)
	c.Thumb(0xB510)
	c.Thumb(0x001C)
	c.Thumb(0x233F)
	c.Thumb(0x0192)
	c.Thumb(0x4023)
	c.Thumb(0x4313)
	c.Thumb(0x5443)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B9DC
func Script_ApprenticeOpenBagMenu(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0xB500)
	c.R[14] = 0x0800B9E3
	c.NCallT(0x08114264)
	if c.U != 0 {
		if c.U != 0x0800B9E3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800B9E8
func TrySetApprenticeHeldItem(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(20)
	c.R[15] = 0x0800B9EC
	c.Thumb(0x4B29)
	c.Thumb(0xB5F0)
	c.Thumb(0x681D)
	c.Thumb(0x23B1)
	c.Thumb(0x5CE8)
	c.Thumb(0x0680)
	c.Thumb(0x0F00)
	c.Thumb(0x2802)
	if c.Cond(0x9) {
		goto L_0800BA62
	}
	c.Thumb(0x2300)
L_0800B9FC:
	c.NT(26)
	c.Thumb(0x001A)
	c.Thumb(0x322E)
	c.Thumb(0x0092)
	c.Thumb(0x5D52)
	c.Thumb(0x0792)
	if c.Cond(0x0) {
		goto L_0800BA68
	}
	c.Thumb(0x3301)
	c.Thumb(0x2B09)
	if c.Cond(0x1) {
		goto L_0800B9FC
	}
	c.Thumb(0x2609)
	c.R[15] = 0x0800BA14
	c.Thumb(0x4B20)
	c.Thumb(0x881F)
	c.Thumb(0x3803)
L_0800BA16:
	c.NT(8)
	c.Thumb(0x002C)
	c.Thumb(0x2300)
	c.Thumb(0x34BA)
	goto L_0800BA44
L_0800BA1E:
	c.NT(26)
	c.Thumb(0x001A)
	c.Thumb(0x322E)
	c.Thumb(0x0092)
	c.Thumb(0x5D51)
	c.Thumb(0x078A)
	c.Thumb(0x0F92)
	c.Thumb(0x2A01)
	if c.Cond(0x1) {
		goto L_0800BA38
	}
	c.Thumb(0x0989)
	if c.Cond(0x0) {
		goto L_0800BA38
	}
	c.Thumb(0x8822)
	c.Thumb(0x42BA)
	if c.Cond(0x0) {
		goto L_0800BA78
	}
L_0800BA38:
	c.NT(12)
	c.Thumb(0x3301)
	c.Thumb(0x061A)
	c.Thumb(0x3404)
	c.Thumb(0x0E12)
	c.Thumb(0x4296)
	if c.Cond(0x9) {
		goto L_0800BA48
	}
L_0800BA44:
	c.NT(4)
	c.Thumb(0x4283)
	if c.Cond(0xB) {
		goto L_0800BA1E
	}
L_0800BA48:
	c.NT(26)
	c.Thumb(0x233F)
	c.Thumb(0x302E)
	c.Thumb(0x0080)
	c.Thumb(0x5D42)
	c.Thumb(0x4013)
	c.Thumb(0x2240)
	c.Thumb(0x4313)
	c.Thumb(0x2201)
	c.Thumb(0x5543)
	c.R[15] = 0x0800BA5E
	c.Thumb(0x4B0F)
	c.Thumb(0x1828)
	c.Thumb(0x8047)
	c.Thumb(0x801A)
L_0800BA62:
	c.NT(6)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800BA68:
	c.NT(16)
	c.R[15] = 0x0800BA6C
	c.Thumb(0x4A0A)
	c.Thumb(0x061B)
	c.Thumb(0x8817)
	c.Thumb(0x0E1E)
	c.Thumb(0x3803)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_0800BA16
	}
	goto L_0800BA48
L_0800BA78:
	c.NT(24)
	c.Thumb(0x233F)
	c.Thumb(0x302E)
	c.Thumb(0x0080)
	c.Thumb(0x5D42)
	c.Thumb(0x4013)
	c.Thumb(0x2200)
	c.Thumb(0x5543)
	c.R[15] = 0x0800BA8A
	c.Thumb(0x4B04)
	c.Thumb(0x1828)
	c.Thumb(0x8047)
	c.Thumb(0x801A)
	goto L_0800BA62
}

// 0x0800BA9C
func ShiftSavedApprentices(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(64)
	c.Thumb(0xB5F0)
	c.Thumb(0x46CE)
	c.Thumb(0x4647)
	c.Thumb(0x238A)
	c.Thumb(0xB580)
	c.R[15] = 0x0800BAAA
	c.Thumb(0x4E29)
	c.Thumb(0x6831)
	c.Thumb(0x005B)
	c.Thumb(0x5CCB)
	c.Thumb(0x2BFF)
	if c.Cond(0x0) {
		goto L_0800BB20
	}
	c.Thumb(0x23AC)
	c.Thumb(0x005B)
	c.Thumb(0x5CCB)
	c.Thumb(0x2BFF)
	if c.Cond(0x0) {
		goto L_0800BB3E
	}
	c.Thumb(0x23CE)
	c.Thumb(0x005B)
	c.Thumb(0x5CCB)
	c.Thumb(0x2BFF)
	if c.Cond(0x0) {
		goto L_0800BB42
	}
	c.Thumb(0x23F0)
	c.Thumb(0x005B)
	c.Thumb(0x5CCB)
	c.Thumb(0x2BFF)
	if c.Cond(0x0) {
		goto L_0800BB46
	}
	c.Thumb(0x2301)
	c.Thumb(0x425B)
	c.Thumb(0x4699)
	c.R[15] = 0x0800BADA
	c.Thumb(0x4B1E)
	c.Thumb(0x2501)
	c.Thumb(0x4698)
L_0800BADC:
	c.NT(28)
	c.Thumb(0x012C)
	c.Thumb(0x1964)
	c.Thumb(0x00A4)
	c.Thumb(0x0020)
	c.Thumb(0x3011)
	c.Thumb(0x30FF)
	c.Thumb(0x1808)
	c.R[14] = 0x0800BAEF
	c.NCallT(0x0813D0BC)
	if c.U != 0 {
		if c.U != 0x0800BAEF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0007)
	c.Thumb(0x6830)
	c.Thumb(0x300A)
	c.R[14] = 0x0800BAF9
	c.NCallT(0x0813D0BC)
	if c.U != 0 {
		if c.U != 0x0800BAF9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4287)
	if c.Cond(0x0) {
		goto L_0800BB2C
	}
L_0800BAFC:
	c.NT(10)
	c.Thumb(0x3501)
	c.Thumb(0x2D04)
	if c.Cond(0x0) {
		goto L_0800BB06
	}
	c.Thumb(0x6831)
	goto L_0800BADC
L_0800BB06:
	c.NT(8)
	c.Thumb(0x464B)
	c.Thumb(0x2B00)
	if c.Cond(0xD) {
		goto L_0800BB20
	}
	c.Thumb(0x6831)
L_0800BB0E:
	c.NT(16)
	c.Thumb(0x0118)
	c.Thumb(0x18C0)
	c.Thumb(0x0080)
	c.Thumb(0x1808)
	c.Thumb(0x2244)
	c.Thumb(0x30DC)
	c.Thumb(0x31DC)
	c.R[14] = 0x0800BB21
	c.NCallT(0x082E6960)
	if c.U != 0 {
		if c.U != 0x0800BB21 {
			return
		}
		c.U = 0
	}
L_0800BB20:
	c.NT(12)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800BB2C:
	c.NT(18)
	c.Thumb(0x6833)
	c.Thumb(0x191B)
	c.Thumb(0x33DE)
	c.Thumb(0x781B)
	c.Thumb(0x4598)
	if c.Cond(0xD) {
		goto L_0800BAFC
	}
	c.Thumb(0x46A9)
	c.Thumb(0x4698)
	goto L_0800BAFC
L_0800BB3E:
	c.NT(4)
	c.Thumb(0x2301)
	goto L_0800BB0E
L_0800BB42:
	c.NT(4)
	c.Thumb(0x2302)
	goto L_0800BB0E
L_0800BB46:
	c.NT(4)
	c.Thumb(0x2303)
	goto L_0800BB0E
}

// 0x0800BB54
func SaveApprentice(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(38)
	c.Thumb(0x22B0)
	c.Thumb(0xB530)
	c.Thumb(0x23B1)
	c.R[15] = 0x0800BB5E
	c.Thumb(0x4D20)
	c.Thumb(0x682C)
	c.Thumb(0x21DC)
	c.Thumb(0x5CA0)
	c.Thumb(0x3A91)
	c.Thumb(0x4002)
	c.Thumb(0x207F)
	c.Thumb(0x5CE3)
	c.Thumb(0x079B)
	c.Thumb(0x0E5B)
	c.Thumb(0x4313)
	c.Thumb(0x5C62)
	c.Thumb(0x4382)
	c.Thumb(0x4313)
	c.Thumb(0x5463)
	c.Thumb(0x2300)
L_0800BB7A:
	c.NT(22)
	c.Thumb(0x0018)
	c.Thumb(0x332E)
	c.Thumb(0x009B)
	c.Thumb(0x5D1B)
	c.Thumb(0x079B)
	if c.Cond(0x0) {
		goto L_0800BBD6
	}
	c.Thumb(0x1C43)
	c.Thumb(0x2808)
	if c.Cond(0x1) {
		goto L_0800BB7A
	}
	c.Thumb(0x2309)
	c.Thumb(0x3001)
L_0800BB90:
	c.NT(16)
	c.Thumb(0x22DD)
	c.Thumb(0x54A3)
	c.Thumb(0x3201)
	c.Thumb(0x5CA3)
	c.Thumb(0x2BFF)
	if c.Cond(0x0) {
		goto L_0800BBA0
	}
	c.Thumb(0x3301)
	c.Thumb(0x54A3)
L_0800BBA0:
	c.NT(48)
	c.R[14] = 0x0800BBA5
	SaveApprenticeParty(c)
	if c.U != 0 {
		if c.U != 0x0800BBA5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x89A3)
	c.Thumb(0x8962)
	c.Thumb(0x041B)
	c.Thumb(0x4313)
	c.Thumb(0x0020)
	c.Thumb(0x2288)
	c.Thumb(0x3015)
	c.Thumb(0x0052)
	c.Thumb(0x50A3)
	c.Thumb(0x0021)
	c.Thumb(0x30FF)
	c.R[14] = 0x0800BBBF
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x0800BBBF {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x0800BBC2
	c.Thumb(0x4B08)
	c.Thumb(0x781A)
	c.Thumb(0x231C)
	c.Thumb(0x6828)
	c.Thumb(0x33FF)
	c.Thumb(0x54C2)
	c.Thumb(0x30DC)
	c.R[14] = 0x0800BBD1
	c.NCallT(0x0808D844)
	if c.U != 0 {
		if c.U != 0x0800BBD1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800BBD6:
	c.NT(6)
	c.Thumb(0x0603)
	c.Thumb(0x0E1B)
	goto L_0800BB90
}

// 0x0800BBE4
func SetSavedApprenticeTrainerGfxId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.R[15] = 0x0800BBE8
	c.Thumb(0x4B14)
	c.Thumb(0x681A)
	c.Thumb(0x23DC)
	c.Thumb(0x5CD3)
	c.Thumb(0x2258)
	c.Thumb(0x06DB)
	c.Thumb(0x0EDB)
	c.Thumb(0x4353)
	c.R[15] = 0x0800BBF8
	c.Thumb(0x4A11)
	c.Thumb(0xB500)
	c.Thumb(0x5C99)
	c.R[15] = 0x0800BBFE
	c.Thumb(0x4811)
	c.Thumb(0x2300)
	goto L_0800BC06
L_0800BC00:
	c.NT(6)
	c.Thumb(0x3301)
	c.Thumb(0x2B1E)
	if c.Cond(0x0) {
		goto L_0800BC1A
	}
L_0800BC06:
	c.NT(14)
	c.Thumb(0x5CC2)
	c.Thumb(0x428A)
	if c.Cond(0x1) {
		goto L_0800BC00
	}
	c.R[15] = 0x0800BC10
	c.Thumb(0x4A0D)
	c.R[15] = 0x0800BC12
	c.Thumb(0x480E)
	c.Thumb(0x5CD1)
	c.R[14] = 0x0800BC17
	c.NCallT(0x080D7300)
	if c.U != 0 {
		if c.U != 0x0800BC17 {
			return
		}
		c.U = 0
	}
L_0800BC16:
	c.NT(4)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800BC1A:
	c.NT(6)
	c.Thumb(0x2300)
	c.R[15] = 0x0800BC20
	c.Thumb(0x480B)
	goto L_0800BC26
L_0800BC20:
	c.NT(6)
	c.Thumb(0x3301)
	c.Thumb(0x2B14)
	if c.Cond(0x0) {
		goto L_0800BC16
	}
L_0800BC26:
	c.NT(16)
	c.Thumb(0x5CC2)
	c.Thumb(0x428A)
	if c.Cond(0x1) {
		goto L_0800BC20
	}
	c.R[15] = 0x0800BC30
	c.Thumb(0x4A08)
	c.R[15] = 0x0800BC32
	c.Thumb(0x4806)
	c.Thumb(0x5CD1)
	c.R[14] = 0x0800BC37
	c.NCallT(0x080D7300)
	if c.U != 0 {
		if c.U != 0x0800BC37 {
			return
		}
		c.U = 0
	}
	goto L_0800BC16
}

// 0x0800BC54
func SetPlayerApprenticeTrainerGfxId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.R[15] = 0x0800BC58
	c.Thumb(0x4B13)
	c.Thumb(0x681A)
	c.Thumb(0x23B0)
	c.Thumb(0xB500)
	c.Thumb(0x5CD2)
	c.Thumb(0x3B58)
	c.Thumb(0x4353)
	c.R[15] = 0x0800BC66
	c.Thumb(0x4A11)
	c.R[15] = 0x0800BC68
	c.Thumb(0x4811)
	c.Thumb(0x5C99)
	c.Thumb(0x2300)
	goto L_0800BC72
L_0800BC6C:
	c.NT(6)
	c.Thumb(0x3301)
	c.Thumb(0x2B1E)
	if c.Cond(0x0) {
		goto L_0800BC86
	}
L_0800BC72:
	c.NT(14)
	c.Thumb(0x5CC2)
	c.Thumb(0x428A)
	if c.Cond(0x1) {
		goto L_0800BC6C
	}
	c.R[15] = 0x0800BC7C
	c.Thumb(0x4A0D)
	c.R[15] = 0x0800BC7E
	c.Thumb(0x480E)
	c.Thumb(0x5CD1)
	c.R[14] = 0x0800BC83
	c.NCallT(0x080D7300)
	if c.U != 0 {
		if c.U != 0x0800BC83 {
			return
		}
		c.U = 0
	}
L_0800BC82:
	c.NT(4)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800BC86:
	c.NT(6)
	c.Thumb(0x2300)
	c.R[15] = 0x0800BC8C
	c.Thumb(0x480B)
	goto L_0800BC92
L_0800BC8C:
	c.NT(6)
	c.Thumb(0x3301)
	c.Thumb(0x2B14)
	if c.Cond(0x0) {
		goto L_0800BC82
	}
L_0800BC92:
	c.NT(16)
	c.Thumb(0x5CC2)
	c.Thumb(0x428A)
	if c.Cond(0x1) {
		goto L_0800BC8C
	}
	c.R[15] = 0x0800BC9C
	c.Thumb(0x4A08)
	c.R[15] = 0x0800BC9E
	c.Thumb(0x4806)
	c.Thumb(0x5CD1)
	c.R[14] = 0x0800BCA3
	c.NCallT(0x080D7300)
	if c.U != 0 {
		if c.U != 0x0800BCA3 {
			return
		}
		c.U = 0
	}
	goto L_0800BC82
}

// 0x0800BCC0
func GetShouldCheckApprenticeGone(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0x2201)
	c.R[15] = 0x0800BCC6
	c.Thumb(0x4B01)
	c.Thumb(0x801A)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BCCC
func GetShouldApprenticeLeave(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0x2201)
	c.R[15] = 0x0800BCD2
	c.Thumb(0x4B01)
	c.Thumb(0x801A)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BCD8
func GetApprenticeNameInLanguage(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	var jt uint32
	c.NT(16)
	c.Thumb(0x2358)
	c.Thumb(0x4343)
	c.Thumb(0x2905)
	if c.Cond(0x8) {
		goto L_0800BD06
	}
	c.R[15] = 0x0800BCE4
	c.Thumb(0x4A0A)
	c.Thumb(0x0089)
	c.Thumb(0x5852)
	jt = c.R[2] &^ 1
	goto Ldispatch
L_0800BCE8:
	c.NT(4)
	c.R[15] = 0x0800BCEC
	c.Thumb(0x4809)
	c.Thumb(0x1818)
L_0800BCEC:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0800BCEE:
	c.NT(6)
	c.R[15] = 0x0800BCF2
	c.Thumb(0x4809)
	c.Thumb(0x1818)
	goto L_0800BCEC
L_0800BCF4:
	c.NT(6)
	c.R[15] = 0x0800BCF8
	c.Thumb(0x4808)
	c.Thumb(0x1818)
	goto L_0800BCEC
L_0800BCFA:
	c.NT(6)
	c.R[15] = 0x0800BCFE
	c.Thumb(0x4808)
	c.Thumb(0x1818)
	goto L_0800BCEC
L_0800BD00:
	c.NT(6)
	c.R[15] = 0x0800BD04
	c.Thumb(0x4807)
	c.Thumb(0x1818)
	goto L_0800BCEC
L_0800BD06:
	c.NT(6)
	c.R[15] = 0x0800BD0A
	c.Thumb(0x4807)
	c.Thumb(0x1818)
	goto L_0800BCEC
Ldispatch:
	switch jt {
	case 0x0800BCE8:
		goto L_0800BCE8
	case 0x0800BCEE:
		goto L_0800BCEE
	case 0x0800BCF4:
		goto L_0800BCF4
	case 0x0800BCFA:
		goto L_0800BCFA
	case 0x0800BD00:
		goto L_0800BD00
	case 0x0800BD06:
		goto L_0800BD06
	default:
		t := jt | 1
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallT(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BD28
func Task_SwitchToFollowupFuncAfterButtonPress(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(16)
	c.Thumb(0xB500)
	c.R[15] = 0x0800BD2E
	c.Thumb(0x4B05)
	c.Thumb(0x8DDB)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
	c.Thumb(0x079B)
	if c.Cond(0x0) {
		goto L_0800BD3A
	}
	c.R[14] = 0x0800BD3B
	c.NCallT(0x081B4E28)
	if c.U != 0 {
		if c.U != 0x0800BD3B {
			return
		}
		c.U = 0
	}
L_0800BD3A:
	c.NT(4)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BD44
func Task_ExecuteFuncAfterButtonPress(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB510)
	c.R[15] = 0x0800BD4A
	c.Thumb(0x4B0D)
	c.Thumb(0x8DDB)
	c.Thumb(0x0604)
	c.Thumb(0x0E24)
	c.Thumb(0x079B)
	if c.Cond(0x0) {
		goto L_0800BD74
	}
	c.Thumb(0x00A3)
	c.R[15] = 0x0800BD58
	c.Thumb(0x4A0A)
	c.Thumb(0x191B)
	c.Thumb(0x00DB)
	c.Thumb(0x18D2)
	c.Thumb(0x210A)
	c.Thumb(0x5E53)
	c.Thumb(0x8912)
	c.Thumb(0x041B)
	c.Thumb(0x4313)
	c.R[15] = 0x0800BD6A
	c.Thumb(0x4A07)
	c.Thumb(0x6013)
	c.R[14] = 0x0800BD6F
	stub_0800BDD0(c)
	if c.U != 0 {
		if c.U != 0x0800BD6F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0020)
	c.R[14] = 0x0800BD75
	c.NCallT(0x081B4D48)
	if c.U != 0 {
		if c.U != 0x0800BD75 {
			return
		}
		c.U = 0
	}
L_0800BD74:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BD88
func ExecuteFuncAfterButtonPress(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0xB510)
	c.Thumb(0x2101)
	c.Thumb(0x0004)
	c.R[15] = 0x0800BD92
	c.Thumb(0x4806)
	c.R[14] = 0x0800BD95
	c.NCallT(0x081B4C48)
	if c.U != 0 {
		if c.U != 0x0800BD95 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0083)
	c.R[15] = 0x0800BD9A
	c.Thumb(0x4A05)
	c.Thumb(0x181B)
	c.Thumb(0x00DB)
	c.Thumb(0x189B)
	c.Thumb(0x609C)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BDB0
func ExecuteFollowupFuncAfterButtonPress(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.Thumb(0xB530)
	c.Thumb(0x0005)
	c.R[15] = 0x0800BDB8
	c.Thumb(0x4C05)
	c.Thumb(0x2101)
	c.Thumb(0x0020)
	c.R[14] = 0x0800BDBF
	c.NCallT(0x081B4C48)
	if c.U != 0 {
		if c.U != 0x0800BDBF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x002A)
	c.Thumb(0x0021)
	c.R[14] = 0x0800BDC7
	c.NCallT(0x081B4E08)
	if c.U != 0 {
		if c.U != 0x0800BDC7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0800BDD0
func stub_0800BDD0(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(2)
	{
		t := c.R[3]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}
