// Code generated by cmd/recomp from pokeemerald_modern.elf. DO NOT EDIT.
package berry

import g "dbut.dev/sapphire/gba"

var regs0 = []reg{
	{0x080A68CC, 48, ClearEnigmaBerries},
	{0x080A68FC, 32, SetEnigmaBerry},
	{0x080A691C, 20, GetEnigmaBerryChecksum},
	{0x080A6930, 84, IsEnigmaBerryValid},
	{0x080A6984, 128, GetBerryInfo},
	{0x080A6A04, 24, GetBerryTreeInfo},
	{0x080A6A1C, 148, ObjectEventInteractionWaterBerryTree},
	{0x080A6AB0, 68, IsPlayerFacingEmptyBerryTreePatch},
	{0x080A6AF4, 36, TryToWaterBerryTree},
	{0x080A6B18, 32, ClearBerryTrees},
	{0x080A6B38, 114, BerryTreeGrow},
	{0x080A6BAC, 456, BerryTreeTimeUpdate},
	{0x080A6D74, 168, PlantBerryTree},
	{0x080A6E1C, 32, RemoveBerryTree},
	{0x080A6E3C, 24, GetBerryTypeByBerryTreeId},
	{0x080A6E54, 32, GetStageByBerryTreeId},
	{0x080A6E74, 28, ItemIdToBerryType},
	{0x080A6E90, 32, BerryTypeToItemId},
	{0x080A6EB0, 32, GetBerryNameByBerryType},
	{0x080A6ED0, 30, GetBerryCountStringByBerryType},
	{0x080A6EF0, 32, AllowBerryTreeGrowth},
	{0x080A6F10, 34, BerryTreeGetNumStagesWatered},
	{0x080A6F34, 56, GetNumStagesWateredByBerryTreeId},
	{0x080A6F6C, 70, CalcBerryYieldInternal},
	{0x080A6FB4, 154, CalcBerryYield},
	{0x080A7050, 24, GetBerryCountByBerryTreeId},
	{0x080A7068, 20, GetStageDurationByBerryType},
	{0x080A707C, 184, ObjectEventInteractionGetBerryTreeData},
	{0x080A7134, 64, ObjectEventInteractionGetBerryName},
	{0x080A7174, 68, ObjectEventInteractionGetBerryCountString},
	{0x080A71B8, 16, Bag_ChooseBerry},
	{0x080A71C8, 64, ObjectEventInteractionPlantBerryTree},
	{0x080A7208, 80, ObjectEventInteractionPickBerryTree},
	{0x080A7258, 60, ObjectEventInteractionRemoveBerryTree},
	{0x080A7294, 12, PlayerHasBerries},
	{0x080A72A0, 248, SetBerryTreesSeen},
}

// 0x080A68CC
func ClearEnigmaBerries(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0xB500)
	c.Thumb(0xB081)
	c.Thumb(0x466A)
	c.Thumb(0x2300)
	c.Thumb(0x8053)
	c.R[15] = 0x080A68DA
	c.Thumb(0x4B06)
	c.Thumb(0x6819)
	c.R[15] = 0x080A68DE
	c.Thumb(0x4B06)
	c.Thumb(0x18C9)
	c.Thumb(0x466B)
	c.R[15] = 0x080A68E4
	c.Thumb(0x4A05)
	c.Thumb(0x1C98)
	c.R[14] = 0x080A68E9
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x080A68E9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A68FC
func SetEnigmaBerry(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(10)
	c.R[15] = 0x080A6900
	c.Thumb(0x4B05)
	c.Thumb(0x6819)
	c.Thumb(0x2300)
	c.R[15] = 0x080A6906
	c.Thumb(0x4A05)
	c.Thumb(0x1889)
L_080A6906:
	c.NT(12)
	c.Thumb(0x5CC2)
	c.Thumb(0x54CA)
	c.Thumb(0x3301)
	c.Thumb(0x2B34)
	if c.Cond(0x1) {
		goto L_080A6906
	}
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A691C
func GetEnigmaBerryChecksum(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0x0001)
	c.Thumb(0x0003)
	c.Thumb(0x2000)
	c.Thumb(0x3130)
L_080A6924:
	c.NT(12)
	c.Thumb(0x781A)
	c.Thumb(0x3301)
	c.Thumb(0x1880)
	c.Thumb(0x428B)
	if c.Cond(0x1) {
		goto L_080A6924
	}
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6930
func IsEnigmaBerryValid(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0xB510)
	c.R[15] = 0x080A6936
	c.Thumb(0x4B0F)
	c.Thumb(0x681C)
	c.R[15] = 0x080A693A
	c.Thumb(0x4B0F)
	c.Thumb(0x5CE3)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A6966
	}
	c.R[15] = 0x080A6942
	c.Thumb(0x4B0E)
	c.Thumb(0x5CE3)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A6966
	}
	c.R[15] = 0x080A694A
	c.Thumb(0x4A0D)
	c.Thumb(0x18A0)
	c.Thumb(0x2200)
	c.R[15] = 0x080A6950
	c.Thumb(0x4B0C)
	c.Thumb(0x18E3)
L_080A6950:
	c.NT(22)
	c.Thumb(0x7819)
	c.Thumb(0x3301)
	c.Thumb(0x1852)
	c.Thumb(0x4283)
	if c.Cond(0x1) {
		goto L_080A6950
	}
	c.R[15] = 0x080A695E
	c.Thumb(0x4B08)
	c.Thumb(0x58E0)
	c.Thumb(0x1A80)
	c.Thumb(0x4243)
	c.Thumb(0x4158)
	goto L_080A6968
L_080A6966:
	c.NT(2)
	c.Thumb(0x2000)
L_080A6968:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6984
func GetBerryInfo(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(42)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
	c.Thumb(0x282B)
	if c.Cond(0x1) {
		goto L_080A69C6
	}
	c.R[15] = 0x080A6990
	c.Thumb(0x4B16)
	c.Thumb(0x681B)
	c.Thumb(0x469C)
	c.Thumb(0x4662)
	c.R[15] = 0x080A6998
	c.Thumb(0x4B15)
	c.Thumb(0x5CD3)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A69C2
	}
	c.R[15] = 0x080A69A0
	c.Thumb(0x4B14)
	c.Thumb(0x5CD3)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A69C2
	}
	c.Thumb(0x2200)
	c.R[15] = 0x080A69AA
	c.Thumb(0x4B13)
	c.R[15] = 0x080A69AC
	c.Thumb(0x4813)
	c.Thumb(0x4463)
	c.Thumb(0x4460)
L_080A69AE:
	c.NT(20)
	c.Thumb(0x7819)
	c.Thumb(0x3301)
	c.Thumb(0x1852)
	c.Thumb(0x4298)
	if c.Cond(0x1) {
		goto L_080A69AE
	}
	c.Thumb(0x4661)
	c.R[15] = 0x080A69BE
	c.Thumb(0x4B0F)
	c.Thumb(0x58CB)
	c.Thumb(0x429A)
	if c.Cond(0x0) {
		goto L_080A69E0
	}
L_080A69C2:
	c.NT(4)
	c.R[15] = 0x080A69C6
	c.Thumb(0x480E)
	goto L_080A69D2
L_080A69C6:
	c.NT(12)
	c.Thumb(0x3801)
	c.Thumb(0x0603)
	c.Thumb(0x0E1B)
	c.Thumb(0x2B2A)
	if c.Cond(0x9) {
		goto L_080A69D4
	}
	c.R[15] = 0x080A69D4
	c.Thumb(0x480B)
L_080A69D2:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A69D4:
	c.NT(12)
	c.Thumb(0x00C3)
	c.Thumb(0x1A18)
	c.R[15] = 0x080A69DC
	c.Thumb(0x4B09)
	c.Thumb(0x0080)
	c.Thumb(0x18C0)
	goto L_080A69D2
L_080A69E0:
	c.NT(6)
	c.R[15] = 0x080A69E4
	c.Thumb(0x4804)
	c.Thumb(0x4460)
	goto L_080A69D2
}

// 0x080A6A04
func GetBerryTreeInfo(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(16)
	c.R[15] = 0x080A6A08
	c.Thumb(0x4A03)
	c.R[15] = 0x080A6A0A
	c.Thumb(0x4904)
	c.Thumb(0x0603)
	c.Thumb(0x0D5B)
	c.Thumb(0x6810)
	c.Thumb(0x185B)
	c.Thumb(0x18C0)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6A1C
func ObjectEventInteractionWaterBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(58)
	c.Thumb(0xB500)
	c.R[15] = 0x080A6A22
	c.Thumb(0x4B21)
	c.Thumb(0x7818)
	c.R[14] = 0x080A6A27
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A6A27 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A6A2A
	c.Thumb(0x4B20)
	c.Thumb(0x681A)
	c.R[15] = 0x080A6A2E
	c.Thumb(0x4920)
	c.Thumb(0x00C3)
	c.Thumb(0x18D3)
	c.Thumb(0x185B)
	c.Thumb(0x785B)
	c.Thumb(0x065B)
	c.Thumb(0x0E5B)
	c.Thumb(0x2B03)
	if c.Cond(0x0) {
		goto L_080A6A7C
	}
	if c.Cond(0x8) {
		goto L_080A6A5E
	}
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_080A6A90
	}
	c.Thumb(0x2B02)
	if c.Cond(0x1) {
		goto L_080A6A78
	}
	c.Thumb(0x23B5)
	c.Thumb(0x009B)
	c.Thumb(0x18C0)
	c.Thumb(0x00C0)
	c.Thumb(0x1810)
	c.Thumb(0x2220)
	c.Thumb(0x7843)
	c.Thumb(0x4313)
	c.Thumb(0x7043)
L_080A6A58:
	c.NT(2)
	c.Thumb(0x2001)
L_080A6A5A:
	c.NT(4)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6A5E:
	c.NT(26)
	c.Thumb(0x2B04)
	if c.Cond(0x1) {
		goto L_080A6A78
	}
	c.Thumb(0x23B5)
	c.Thumb(0x009B)
	c.Thumb(0x18C0)
	c.Thumb(0x2380)
	c.Thumb(0x00C0)
	c.Thumb(0x1812)
	c.Thumb(0x7851)
	c.Thumb(0x425B)
	c.Thumb(0x430B)
	c.Thumb(0x7053)
	goto L_080A6A58
L_080A6A78:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_080A6A5A
L_080A6A7C:
	c.NT(20)
	c.Thumb(0x23B5)
	c.Thumb(0x009B)
	c.Thumb(0x18C0)
	c.Thumb(0x00C0)
	c.Thumb(0x1810)
	c.Thumb(0x2240)
	c.Thumb(0x7843)
	c.Thumb(0x4313)
	c.Thumb(0x7043)
	goto L_080A6A58
L_080A6A90:
	c.NT(20)
	c.Thumb(0x23B5)
	c.Thumb(0x009B)
	c.Thumb(0x18C0)
	c.Thumb(0x00C0)
	c.Thumb(0x1810)
	c.Thumb(0x2210)
	c.Thumb(0x7843)
	c.Thumb(0x4313)
	c.Thumb(0x7043)
	goto L_080A6A58
}

// 0x080A6AB0
func IsPlayerFacingEmptyBerryTreePatch(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.Thumb(0xB500)
	c.R[14] = 0x080A6AB7
	c.NCallT(0x080EC228)
	if c.U != 0 {
		if c.U != 0x080A6AB7 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A6ABA
	c.Thumb(0x4B0B)
	c.Thumb(0x0002)
	c.Thumb(0x2000)
	c.Thumb(0x429A)
	if c.Cond(0x0) {
		goto L_080A6AC4
	}
L_080A6AC0:
	c.NT(4)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6AC4:
	c.NT(28)
	c.R[15] = 0x080A6AC8
	c.Thumb(0x4B08)
	c.Thumb(0x7818)
	c.R[14] = 0x080A6ACD
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A6ACD {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A6AD0
	c.Thumb(0x4B07)
	c.Thumb(0x681B)
	c.Thumb(0x00C0)
	c.R[15] = 0x080A6AD6
	c.Thumb(0x4A07)
	c.Thumb(0x181B)
	c.Thumb(0x189B)
	c.Thumb(0x7858)
	c.Thumb(0x0640)
	c.Thumb(0x4243)
	c.Thumb(0x4158)
	goto L_080A6AC0
}

// 0x080A6AF4
func TryToWaterBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.Thumb(0xB500)
	c.R[14] = 0x080A6AFB
	c.NCallT(0x080EC228)
	if c.U != 0 {
		if c.U != 0x080A6AFB {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A6AFE
	c.Thumb(0x4B06)
	c.Thumb(0x0002)
	c.Thumb(0x2000)
	c.Thumb(0x429A)
	if c.Cond(0x0) {
		goto L_080A6B08
	}
L_080A6B04:
	c.NT(4)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6B08:
	c.NT(8)
	c.R[14] = 0x080A6B0D
	ObjectEventInteractionWaterBerryTree(c)
	if c.U != 0 {
		if c.U != 0x080A6B0D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
	goto L_080A6B04
}

// 0x080A6B18
func ClearBerryTrees(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.Thumb(0x2280)
	c.R[15] = 0x080A6B1E
	c.Thumb(0x4B05)
	c.Thumb(0xB500)
	c.Thumb(0x6818)
	c.R[15] = 0x080A6B24
	c.Thumb(0x4B04)
	c.Thumb(0x2100)
	c.Thumb(0x18C0)
	c.Thumb(0x00D2)
	c.R[14] = 0x080A6B2D
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x080A6B2D {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6B38
func BerryTreeGrow(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(26)
	c.Thumb(0x7842)
	c.Thumb(0xB510)
	c.Thumb(0x0004)
	c.Thumb(0x2A7F)
	if c.Cond(0x8) {
		goto L_080A6B90
	}
	c.Thumb(0x0653)
	c.Thumb(0x0E5B)
	c.Thumb(0x2B04)
	if c.Cond(0x0) {
		goto L_080A6B94
	}
	if c.Cond(0x8) {
		goto L_080A6B68
	}
	c.Thumb(0x2000)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A6B62
	}
L_080A6B52:
	c.NT(14)
	c.Thumb(0x217F)
	c.Thumb(0x7862)
	c.Thumb(0x3301)
	c.Thumb(0x400B)
	c.Thumb(0x438A)
	c.Thumb(0x4313)
	c.Thumb(0x7063)
L_080A6B60:
	c.NT(2)
	c.Thumb(0x2001)
L_080A6B62:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6B68:
	c.NT(40)
	c.Thumb(0x2B05)
	if c.Cond(0x1) {
		goto L_080A6B60
	}
	c.Thumb(0x21F0)
	c.Thumb(0x8883)
	c.Thumb(0x0109)
	c.Thumb(0x400B)
	c.Thumb(0x217F)
	c.Thumb(0x438A)
	c.Thumb(0x2102)
	c.Thumb(0x430A)
	c.Thumb(0x7042)
	c.Thumb(0x220F)
	c.Thumb(0x8083)
	c.Thumb(0x0A1B)
	c.Thumb(0x3301)
	c.Thumb(0x4013)
	c.Thumb(0x2B0A)
	if c.Cond(0x0) {
		goto L_080A6BA2
	}
	c.Thumb(0x7143)
	goto L_080A6B60
L_080A6B90:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_080A6B62
L_080A6B94:
	c.NT(12)
	c.R[14] = 0x080A6B99
	CalcBerryYield(c)
	if c.U != 0 {
		if c.U != 0x080A6B99 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x7863)
	c.Thumb(0x065B)
	c.Thumb(0x7120)
	c.Thumb(0x0E5B)
	goto L_080A6B52
L_080A6BA2:
	c.NT(8)
	c.Thumb(0x2200)
	c.Thumb(0x2300)
	c.Thumb(0xC40C)
	goto L_080A6B60
}

// 0x080A6BAC
func BerryTreeTimeUpdate(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x464E)
	c.Thumb(0x4657)
	c.Thumb(0x4645)
	c.Thumb(0xB5E0)
	c.R[15] = 0x080A6BBC
	c.Thumb(0x4964)
	c.Thumb(0x4689)
	c.R[15] = 0x080A6BC0
	c.Thumb(0x4964)
	c.Thumb(0xB083)
	c.Thumb(0x2400)
	c.Thumb(0x4683)
	c.R[15] = 0x080A6BC8
	c.Thumb(0x4A63)
	c.Thumb(0x9102)
	goto L_080A6BD2
L_080A6BCA:
	c.NT(8)
	c.Thumb(0x3401)
	c.Thumb(0x3208)
	c.Thumb(0x2C80)
	if c.Cond(0x0) {
		goto L_080A6C4C
	}
L_080A6BD2:
	c.NT(46)
	c.Thumb(0x464B)
	c.Thumb(0x681D)
	c.R[15] = 0x080A6BDA
	c.Thumb(0x495F)
	c.Thumb(0x00E0)
	c.Thumb(0x182B)
	c.Thumb(0x185B)
	c.Thumb(0x7819)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_080A6BCA
	}
	c.Thumb(0x785B)
	c.Thumb(0x065E)
	if c.Cond(0x0) {
		goto L_080A6BCA
	}
	c.Thumb(0x43DB)
	c.Thumb(0x061B)
	if c.Cond(0x5) {
		goto L_080A6BCA
	}
	c.Thumb(0x292B)
	if c.Cond(0x1) {
		goto L_080A6C5E
	}
	c.R[15] = 0x080A6BF8
	c.Thumb(0x4B58)
	c.Thumb(0x5CEB)
	c.Thumb(0x469C)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_080A6C00
	}
	goto L_080A6CFE
L_080A6C00:
	c.NT(10)
	c.R[15] = 0x080A6C04
	c.Thumb(0x4B56)
	c.Thumb(0x5CEB)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_080A6C0A
	}
	goto L_080A6CFE
L_080A6C0A:
	c.NT(10)
	c.R[15] = 0x080A6C0E
	c.Thumb(0x4955)
	c.Thumb(0x186F)
	c.Thumb(0x2100)
	c.R[15] = 0x080A6C14
	c.Thumb(0x4B54)
	c.Thumb(0x18EB)
L_080A6C14:
	c.NT(32)
	c.Thumb(0x781E)
	c.Thumb(0x3301)
	c.Thumb(0x1989)
	c.Thumb(0x429F)
	if c.Cond(0x1) {
		goto L_080A6C14
	}
	c.R[15] = 0x080A6C22
	c.Thumb(0x4B50)
	c.Thumb(0x58EB)
	c.Thumb(0x4299)
	if c.Cond(0x1) {
		goto L_080A6CFE
	}
	c.Thumb(0x233C)
	c.Thumb(0x4661)
	c.Thumb(0x4359)
	c.Thumb(0x00CB)
	c.Thumb(0x185B)
	c.Thumb(0x00DB)
	c.Thumb(0x1A5B)
L_080A6C34:
	c.NT(4)
	c.Thumb(0x459B)
	if c.Cond(0xB) {
		goto L_080A6C6E
	}
L_080A6C38:
	c.NT(20)
	c.Thumb(0x182D)
	c.Thumb(0x2100)
	c.Thumb(0x2000)
	c.R[15] = 0x080A6C42
	c.Thumb(0x4B45)
	c.Thumb(0x3401)
	c.Thumb(0x18ED)
	c.Thumb(0xC503)
	c.Thumb(0x3208)
	c.Thumb(0x2C80)
	if c.Cond(0x1) {
		goto L_080A6BD2
	}
L_080A6C4C:
	c.NT(18)
	c.Thumb(0xB003)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6C5E:
	c.NT(16)
	c.Thumb(0x3901)
	c.Thumb(0x060B)
	c.Thumb(0x0E1B)
	c.Thumb(0x2B2A)
	if c.Cond(0x9) {
		goto L_080A6D26
	}
	c.R[15] = 0x080A6C6C
	c.Thumb(0x4B3F)
	c.Thumb(0x459B)
	if c.Cond(0xA) {
		goto L_080A6C38
	}
L_080A6C6E:
	c.NT(26)
	c.Thumb(0x18AB)
	c.Thumb(0x469A)
	c.R[15] = 0x080A6C76
	c.Thumb(0x4B3E)
	c.Thumb(0x465E)
	c.Thumb(0x4698)
	c.Thumb(0x182D)
	c.Thumb(0x44A8)
	c.Thumb(0x2E00)
	if c.Cond(0x0) {
		goto L_080A6BCA
	}
	c.Thumb(0x4643)
	c.Thumb(0x46A0)
	c.Thumb(0x001C)
	c.Thumb(0x9201)
L_080A6C88:
	c.NT(48)
	c.Thumb(0x8827)
	c.Thumb(0x42B7)
	if c.Cond(0xC) {
		goto L_080A6D40
	}
	c.R[15] = 0x080A6C92
	c.Thumb(0x4B31)
	c.Thumb(0x5CEB)
	c.Thumb(0x2B2B)
	if c.Cond(0x1) {
		goto L_080A6D02
	}
	c.Thumb(0x464B)
	c.Thumb(0x6819)
	c.R[15] = 0x080A6C9E
	c.Thumb(0x4B2F)
	c.Thumb(0x5CCB)
	c.Thumb(0x469C)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A6D20
	}
	c.R[15] = 0x080A6CA8
	c.Thumb(0x4B2D)
	c.Thumb(0x5CCB)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_080A6D20
	}
	c.R[15] = 0x080A6CB0
	c.Thumb(0x4A2C)
	c.Thumb(0x1888)
	c.Thumb(0x2200)
	c.R[15] = 0x080A6CB6
	c.Thumb(0x4B2C)
	c.Thumb(0x9700)
	c.Thumb(0x18CB)
L_080A6CB8:
	c.NT(26)
	c.Thumb(0x781F)
	c.Thumb(0x3301)
	c.Thumb(0x19D2)
	c.Thumb(0x4298)
	if c.Cond(0x1) {
		goto L_080A6CB8
	}
	c.R[15] = 0x080A6CC6
	c.Thumb(0x4B27)
	c.Thumb(0x58CB)
	c.Thumb(0x9F00)
	c.Thumb(0x429A)
	if c.Cond(0x1) {
		goto L_080A6D20
	}
	c.Thumb(0x233C)
	c.Thumb(0x4662)
	c.Thumb(0x435A)
L_080A6CD2:
	c.NT(32)
	c.Thumb(0x4650)
	c.Thumb(0x8022)
	c.R[14] = 0x080A6CDB
	BerryTreeGrow(c)
	if c.U != 0 {
		if c.U != 0x080A6CDB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_080A6CF8
	}
	c.R[15] = 0x080A6CE2
	c.Thumb(0x4B1D)
	c.Thumb(0x18EB)
	c.Thumb(0x785A)
	c.Thumb(0x237F)
	c.Thumb(0x1BF6)
	c.Thumb(0x4013)
	c.Thumb(0x2B05)
	if c.Cond(0x1) {
		goto L_080A6CF4
	}
	c.Thumb(0x8823)
	c.Thumb(0x009B)
	c.Thumb(0x8023)
L_080A6CF4:
	c.NT(4)
	c.Thumb(0x2E00)
	if c.Cond(0x1) {
		goto L_080A6C88
	}
L_080A6CF8:
	c.NT(6)
	c.Thumb(0x4644)
	c.Thumb(0x9A01)
	goto L_080A6BCA
L_080A6CFE:
	c.NT(4)
	c.R[15] = 0x080A6D02
	c.Thumb(0x4B1C)
	goto L_080A6C34
L_080A6D02:
	c.NT(30)
	c.Thumb(0x3B01)
	c.Thumb(0x0619)
	c.Thumb(0x22B4)
	c.Thumb(0x0E09)
	c.Thumb(0x292A)
	if c.Cond(0x8) {
		goto L_080A6CD2
	}
	c.Thumb(0x00DA)
	c.Thumb(0x1AD3)
	c.Thumb(0x9A02)
	c.Thumb(0x009B)
	c.Thumb(0x18D3)
	c.Thumb(0x7D1A)
	c.Thumb(0x233C)
	c.Thumb(0x435A)
	goto L_080A6CD2
L_080A6D20:
	c.NT(6)
	c.Thumb(0x22B4)
	c.Thumb(0x00D2)
	goto L_080A6CD2
L_080A6D26:
	c.NT(26)
	c.Thumb(0x00CB)
	c.Thumb(0x1A5B)
	c.R[15] = 0x080A6D2E
	c.Thumb(0x4909)
	c.Thumb(0x009B)
	c.Thumb(0x185B)
	c.Thumb(0x7D19)
	c.Thumb(0x233C)
	c.Thumb(0x4359)
	c.Thumb(0x00CB)
	c.Thumb(0x185B)
	c.Thumb(0x00DB)
	c.Thumb(0x1A5B)
	goto L_080A6C34
L_080A6D40:
	c.NT(12)
	c.Thumb(0x0023)
	c.Thumb(0x1BBF)
	c.Thumb(0x4644)
	c.Thumb(0x9A01)
	c.Thumb(0x801F)
	goto L_080A6BCA
}

// 0x080A6D74
func PlantBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(86)
	c.Thumb(0xB5F0)
	c.Thumb(0x46D6)
	c.Thumb(0x464F)
	c.Thumb(0x4646)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x4698)
	c.R[15] = 0x080A6D86
	c.Thumb(0x4B23)
	c.Thumb(0xB5C0)
	c.Thumb(0x0604)
	c.Thumb(0x681F)
	c.Thumb(0x0D63)
	c.Thumb(0x0E20)
	c.Thumb(0x4699)
	c.Thumb(0x18FC)
	c.R[15] = 0x080A6D96
	c.Thumb(0x4B20)
	c.Thumb(0x0612)
	c.Thumb(0x18E6)
	c.Thumb(0x0E15)
	c.Thumb(0x2300)
	c.Thumb(0x2200)
	c.Thumb(0x0609)
	c.Thumb(0x4682)
	c.Thumb(0x0E08)
	c.Thumb(0x6032)
	c.Thumb(0x6073)
	c.Thumb(0x7030)
	c.R[14] = 0x080A6DAF
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A6DAF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x223C)
	c.R[15] = 0x080A6DB4
	c.Thumb(0x4B19)
	c.Thumb(0x18E4)
	c.Thumb(0x7D03)
	c.Thumb(0x4353)
	c.Thumb(0x227F)
	c.Thumb(0x0011)
	c.Thumb(0x8023)
	c.Thumb(0x7873)
	c.Thumb(0x4029)
	c.Thumb(0x4393)
	c.Thumb(0x430B)
	c.Thumb(0x7073)
	c.Thumb(0x2D05)
	if c.Cond(0x0) {
		goto L_080A6DF0
	}
L_080A6DCC:
	c.NT(22)
	c.Thumb(0x4643)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_080A6DE2
	}
	c.R[15] = 0x080A6DD6
	c.Thumb(0x4B10)
	c.Thumb(0x444F)
	c.Thumb(0x18FF)
	c.Thumb(0x2380)
	c.Thumb(0x787A)
	c.Thumb(0x425B)
	c.Thumb(0x4313)
	c.Thumb(0x707B)
L_080A6DE2:
	c.NT(14)
	c.Thumb(0xBCE0)
	c.Thumb(0x46BA)
	c.Thumb(0x46B1)
	c.Thumb(0x46A8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6DF0:
	c.NT(30)
	c.Thumb(0x4648)
	c.R[15] = 0x080A6DF6
	c.Thumb(0x4B08)
	c.Thumb(0x18C0)
	c.Thumb(0x1838)
	c.R[14] = 0x080A6DFD
	CalcBerryYield(c)
	if c.U != 0 {
		if c.U != 0x080A6DFD {
			return
		}
		c.U = 0
	}
	c.Thumb(0x22B5)
	c.Thumb(0x4653)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x00DB)
	c.Thumb(0x54F8)
	c.Thumb(0x8823)
	c.Thumb(0x009B)
	c.Thumb(0x8023)
	goto L_080A6DCC
}

// 0x080A6E1C
func RemoveBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.R[15] = 0x080A6E20
	c.Thumb(0x4B05)
	c.Thumb(0x681B)
	c.Thumb(0x0600)
	c.Thumb(0x0D40)
	c.Thumb(0x2100)
	c.Thumb(0x181B)
	c.Thumb(0x2000)
	c.R[15] = 0x080A6E2E
	c.Thumb(0x4A03)
	c.Thumb(0x189B)
	c.Thumb(0xC303)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6E3C
func GetBerryTypeByBerryTreeId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(16)
	c.R[15] = 0x080A6E40
	c.Thumb(0x4B03)
	c.Thumb(0x681B)
	c.Thumb(0x0600)
	c.R[15] = 0x080A6E46
	c.Thumb(0x4A03)
	c.Thumb(0x0D40)
	c.Thumb(0x181B)
	c.Thumb(0x5C98)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6E54
func GetStageByBerryTreeId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.R[15] = 0x080A6E58
	c.Thumb(0x4B05)
	c.Thumb(0x681B)
	c.Thumb(0x0600)
	c.R[15] = 0x080A6E5E
	c.Thumb(0x4A05)
	c.Thumb(0x0D40)
	c.Thumb(0x181B)
	c.Thumb(0x189B)
	c.Thumb(0x7858)
	c.Thumb(0x0640)
	c.Thumb(0x0E40)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6E74
func ItemIdToBerryType(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.R[15] = 0x080A6E78
	c.Thumb(0x4B05)
	c.Thumb(0x0400)
	c.Thumb(0x0C02)
	c.Thumb(0x18C0)
	c.Thumb(0x0C03)
	c.Thumb(0x2001)
	c.Thumb(0x2B2A)
	if c.Cond(0x8) {
		goto L_080A6E8A
	}
	c.Thumb(0x327C)
	c.Thumb(0x0612)
	c.Thumb(0x0E10)
L_080A6E8A:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6E90
func BerryTypeToItemId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(20)
	c.R[15] = 0x080A6E94
	c.Thumb(0x4A06)
	c.Thumb(0x0400)
	c.Thumb(0x0C03)
	c.Thumb(0x1880)
	c.Thumb(0x0C00)
	c.Thumb(0x282A)
	if c.Cond(0x8) {
		goto L_080A6EA6
	}
	c.Thumb(0x3384)
	c.Thumb(0x0418)
	c.Thumb(0x0C00)
L_080A6EA4:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6EA6:
	c.NT(4)
	c.Thumb(0x2085)
	goto L_080A6EA4
}

// 0x080A6EB0
func GetBerryNameByBerryType(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0x0600)
	c.Thumb(0xB510)
	c.Thumb(0x0E00)
	c.Thumb(0x000C)
	c.R[14] = 0x080A6EBD
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A6EBD {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2206)
	c.Thumb(0x0001)
	c.Thumb(0x0020)
	c.R[14] = 0x080A6EC7
	c.NCallT(0x082E6960)
	if c.U != 0 {
		if c.U != 0x080A6EC7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x23FF)
	c.Thumb(0x71A3)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6ED0
func GetBerryCountStringByBerryType(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(26)
	c.Thumb(0x0600)
	c.Thumb(0xB530)
	c.Thumb(0x0E00)
	c.Thumb(0x000D)
	c.Thumb(0x0014)
	c.R[14] = 0x080A6EDF
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A6EDF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0022)
	c.Thumb(0x0001)
	c.Thumb(0x0028)
	c.R[14] = 0x080A6EE9
	c.NCallT(0x08119954)
	if c.U != 0 {
		if c.U != 0x080A6EE9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6EF0
func AllowBerryTreeGrowth(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.R[15] = 0x080A6EF4
	c.Thumb(0x4B05)
	c.Thumb(0x681B)
	c.Thumb(0x0600)
	c.R[15] = 0x080A6EFA
	c.Thumb(0x4A05)
	c.Thumb(0x0D40)
	c.Thumb(0x181B)
	c.Thumb(0x189B)
	c.Thumb(0x227F)
	c.Thumb(0x7859)
	c.Thumb(0x400A)
	c.Thumb(0x705A)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6F10
func BerryTreeGetNumStagesWatered(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0x7943)
	c.Thumb(0x06D8)
	c.Thumb(0x0FC0)
	c.Thumb(0x069A)
	if c.Cond(0x5) {
		goto L_080A6F1C
	}
	c.Thumb(0x3001)
L_080A6F1C:
	c.NT(10)
	c.Thumb(0x065A)
	if c.Cond(0x5) {
		goto L_080A6F26
	}
	c.Thumb(0x3001)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
L_080A6F26:
	c.NT(10)
	c.Thumb(0x061B)
	if c.Cond(0x5) {
		goto L_080A6F30
	}
	c.Thumb(0x3001)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
L_080A6F30:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6F34
func GetNumStagesWateredByBerryTreeId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(26)
	c.R[15] = 0x080A6F38
	c.Thumb(0x4B0B)
	c.Thumb(0x0600)
	c.Thumb(0x681B)
	c.Thumb(0x0D40)
	c.R[15] = 0x080A6F40
	c.Thumb(0x4A0A)
	c.Thumb(0x181B)
	c.Thumb(0x189B)
	c.Thumb(0x795B)
	c.Thumb(0x06D8)
	c.Thumb(0x0FC0)
	c.Thumb(0x069A)
	if c.Cond(0x5) {
		goto L_080A6F4E
	}
	c.Thumb(0x3001)
L_080A6F4E:
	c.NT(10)
	c.Thumb(0x065A)
	if c.Cond(0x5) {
		goto L_080A6F58
	}
	c.Thumb(0x3001)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
L_080A6F58:
	c.NT(10)
	c.Thumb(0x061B)
	if c.Cond(0x5) {
		goto L_080A6F62
	}
	c.Thumb(0x3001)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
L_080A6F62:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A6F6C
func CalcBerryYieldInternal(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.Thumb(0x0409)
	c.Thumb(0x0C0B)
	c.Thumb(0x0400)
	c.Thumb(0x0612)
	c.Thumb(0x0209)
	c.Thumb(0x469C)
	c.Thumb(0xB570)
	c.Thumb(0x0C00)
	c.Thumb(0x0E13)
	c.Thumb(0x0E0C)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_080A6F8C
	}
L_080A6F84:
	c.NT(8)
	c.Thumb(0x0020)
	c.Thumb(0xBC70)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A6F8C:
	c.NT(34)
	c.Thumb(0x4662)
	c.Thumb(0x3B01)
	c.Thumb(0x1A85)
	c.Thumb(0x002E)
	c.Thumb(0x435E)
	c.R[14] = 0x080A6F9B
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x080A6F9B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x1C69)
	c.R[14] = 0x080A6FA1
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x080A6FA1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x1980)
	c.Thumb(0x0883)
	c.Thumb(0x0780)
	c.Thumb(0x0FC0)
	c.Thumb(0x181B)
	c.Thumb(0x18E3)
	c.Thumb(0x061B)
	c.Thumb(0x0E1C)
	goto L_080A6F84
}

// 0x080A6FB4
func CalcBerryYield(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB570)
	c.Thumb(0x0004)
	c.Thumb(0x7800)
	c.R[14] = 0x080A6FBF
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A6FBF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x7961)
	c.Thumb(0x7AC5)
	c.Thumb(0x2440)
	c.Thumb(0x7A82)
	c.Thumb(0x2010)
	c.Thumb(0x400C)
	c.Thumb(0x4008)
	c.Thumb(0x46A4)
	c.Thumb(0x0503)
	c.Thumb(0x060C)
	c.Thumb(0x0E1B)
	c.Thumb(0x1624)
	c.Thumb(0x0689)
	if c.Cond(0x5) {
		goto L_080A701A
	}
	c.Thumb(0x4661)
	c.Thumb(0x3301)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_080A702E
	}
L_080A6FE2:
	c.NT(20)
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x2C00)
	if c.Cond(0xB) {
		goto L_080A703E
	}
	c.Thumb(0x1B52)
	c.Thumb(0x3B01)
	c.Thumb(0x0014)
	c.Thumb(0x435C)
	c.Thumb(0x18A6)
L_080A6FF6:
	c.NT(24)
	c.R[14] = 0x080A6FFB
	c.NCallT(0x0818D7D4)
	if c.U != 0 {
		if c.U != 0x080A6FFB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x1B31)
	c.Thumb(0x3101)
	c.R[14] = 0x080A7003
	c.NCallT(0x082E4F04)
	if c.U != 0 {
		if c.U != 0x080A7003 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x1900)
	c.Thumb(0x0883)
	c.Thumb(0x0780)
	c.Thumb(0x0FC0)
	c.Thumb(0x181B)
	c.Thumb(0x18EB)
	c.Thumb(0x061B)
	c.Thumb(0x0E1D)
L_080A7012:
	c.NT(8)
	c.Thumb(0x0028)
	c.Thumb(0xBC70)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A701A:
	c.NT(20)
	c.Thumb(0x4661)
	c.Thumb(0x2900)
	if c.Cond(0x1) {
		goto L_080A6FE2
	}
	c.Thumb(0x2C00)
	if c.Cond(0xB) {
		goto L_080A703E
	}
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_080A7012
	}
	c.Thumb(0x2400)
	c.Thumb(0x1B56)
	goto L_080A6FF6
L_080A702E:
	c.NT(16)
	c.Thumb(0x2C00)
	if c.Cond(0xB) {
		goto L_080A703E
	}
	c.Thumb(0x3B01)
	c.Thumb(0x1B52)
	c.Thumb(0x425C)
	c.Thumb(0x4014)
	c.Thumb(0x18A6)
	goto L_080A6FF6
L_080A703E:
	c.NT(16)
	c.Thumb(0x3301)
	c.Thumb(0x061C)
	c.Thumb(0x0E24)
	c.Thumb(0x1B52)
	c.Thumb(0x3C01)
	c.Thumb(0x4354)
	c.Thumb(0x1916)
	goto L_080A6FF6
}

// 0x080A7050
func GetBerryCountByBerryTreeId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.Thumb(0x22B5)
	c.R[15] = 0x080A7056
	c.Thumb(0x4B04)
	c.Thumb(0x0600)
	c.Thumb(0x681B)
	c.Thumb(0x0152)
	c.Thumb(0x0D40)
	c.Thumb(0x1880)
	c.Thumb(0x5C18)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A7068
func GetStageDurationByBerryType(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.Thumb(0x0600)
	c.Thumb(0xB500)
	c.Thumb(0x0E00)
	c.R[14] = 0x080A7073
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A7073 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x233C)
	c.Thumb(0x7D00)
	c.Thumb(0x4358)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A707C
func ObjectEventInteractionGetBerryTreeData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(64)
	c.Thumb(0xB5F0)
	c.R[15] = 0x080A7082
	c.Thumb(0x4B25)
	c.Thumb(0x7818)
	c.R[14] = 0x080A7087
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A7087 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A708A
	c.Thumb(0x4E24)
	c.Thumb(0x6831)
	c.R[15] = 0x080A708E
	c.Thumb(0x4A24)
	c.Thumb(0x00C5)
	c.Thumb(0x194B)
	c.Thumb(0x189B)
	c.Thumb(0x781A)
	c.Thumb(0x0017)
	c.Thumb(0x227F)
	c.Thumb(0x0004)
	c.Thumb(0x7858)
	c.Thumb(0x4002)
	c.Thumb(0x705A)
	c.R[15] = 0x080A70A4
	c.Thumb(0x4B1F)
	c.Thumb(0x790A)
	c.Thumb(0x7818)
	c.Thumb(0x7949)
	c.R[14] = 0x080A70AD
	c.NCallT(0x080DE398)
	if c.U != 0 {
		if c.U != 0x080A70AD {
			return
		}
		c.U = 0
	}
	c.Thumb(0x23FF)
	c.Thumb(0x6832)
	c.Thumb(0x2800)
	if c.Cond(0x1) {
		goto L_080A70C0
	}
	c.R[15] = 0x080A70B8
	c.Thumb(0x4919)
	c.Thumb(0x1953)
	c.Thumb(0x185B)
	c.Thumb(0x785B)
	c.Thumb(0x065B)
	c.Thumb(0x0E5B)
L_080A70C0:
	c.NT(22)
	c.R[15] = 0x080A70C4
	c.Thumb(0x4918)
	c.Thumb(0x800B)
	c.R[15] = 0x080A70C8
	c.Thumb(0x4B15)
	c.Thumb(0x1955)
	c.Thumb(0x18ED)
	c.Thumb(0x7969)
	c.Thumb(0x06CB)
	c.Thumb(0x0FDB)
	c.Thumb(0x0688)
	if c.Cond(0x5) {
		goto L_080A70D6
	}
	c.Thumb(0x3301)
L_080A70D6:
	c.NT(10)
	c.Thumb(0x0648)
	if c.Cond(0x5) {
		goto L_080A70E0
	}
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
L_080A70E0:
	c.NT(10)
	c.Thumb(0x0609)
	if c.Cond(0x5) {
		goto L_080A70EA
	}
	c.Thumb(0x3301)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
L_080A70EA:
	c.NT(36)
	c.R[15] = 0x080A70EE
	c.Thumb(0x490F)
	c.Thumb(0x800B)
	c.Thumb(0x23B5)
	c.Thumb(0x009B)
	c.Thumb(0x18E4)
	c.Thumb(0x00E4)
	c.Thumb(0x5CA4)
	c.R[15] = 0x080A70FC
	c.Thumb(0x4B0C)
	c.Thumb(0x0038)
	c.Thumb(0x801C)
	c.R[14] = 0x080A7103
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A7103 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0022)
	c.Thumb(0x0001)
	c.R[15] = 0x080A710A
	c.Thumb(0x480A)
	c.R[14] = 0x080A710D
	c.NCallT(0x08119954)
	if c.U != 0 {
		if c.U != 0x080A710D {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A7134
func ObjectEventInteractionGetBerryName(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(40)
	c.Thumb(0xB500)
	c.R[15] = 0x080A713A
	c.Thumb(0x4B0B)
	c.Thumb(0x7818)
	c.R[14] = 0x080A713F
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A713F {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A7142
	c.Thumb(0x4B0A)
	c.Thumb(0x681B)
	c.R[15] = 0x080A7146
	c.Thumb(0x4A0A)
	c.Thumb(0x00C0)
	c.Thumb(0x181B)
	c.Thumb(0x5C98)
	c.R[14] = 0x080A714F
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A714F {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A7152
	c.Thumb(0x4B08)
	c.Thumb(0x0001)
	c.Thumb(0x2206)
	c.Thumb(0x0018)
	c.R[14] = 0x080A715B
	c.NCallT(0x082E6960)
	if c.U != 0 {
		if c.U != 0x080A715B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x23FF)
	c.Thumb(0x7183)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A7174
func ObjectEventInteractionGetBerryCountString(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(46)
	c.Thumb(0xB530)
	c.R[15] = 0x080A717A
	c.Thumb(0x4B0C)
	c.Thumb(0x7818)
	c.R[14] = 0x080A717F
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A717F {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A7182
	c.Thumb(0x4B0B)
	c.Thumb(0x681D)
	c.R[15] = 0x080A7186
	c.Thumb(0x4A0B)
	c.Thumb(0x00C3)
	c.Thumb(0x18EB)
	c.Thumb(0x0004)
	c.Thumb(0x5C98)
	c.R[14] = 0x080A7191
	GetBerryInfo(c)
	if c.U != 0 {
		if c.U != 0x080A7191 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x23B5)
	c.Thumb(0x009B)
	c.Thumb(0x18E4)
	c.Thumb(0x00E4)
	c.Thumb(0x0001)
	c.Thumb(0x5D62)
	c.R[15] = 0x080A71A0
	c.Thumb(0x4805)
	c.R[14] = 0x080A71A3
	c.NCallT(0x08119954)
	if c.U != 0 {
		if c.U != 0x080A71A3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A71B8
func Bag_ChooseBerry(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(10)
	c.Thumb(0xB500)
	c.R[15] = 0x080A71BE
	c.Thumb(0x4802)
	c.R[14] = 0x080A71C1
	c.NCallT(0x080005B8)
	if c.U != 0 {
		if c.U != 0x080A71C1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A71C8
func ObjectEventInteractionPlantBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(26)
	c.R[15] = 0x080A71CC
	c.Thumb(0x4B0D)
	c.Thumb(0x881A)
	c.Thumb(0x0013)
	c.Thumb(0x3B85)
	c.Thumb(0x041B)
	c.Thumb(0xB510)
	c.Thumb(0x0C1B)
	c.Thumb(0x2401)
	c.Thumb(0x2B2A)
	if c.Cond(0x8) {
		goto L_080A71E2
	}
	c.Thumb(0x327C)
	c.Thumb(0x0612)
	c.Thumb(0x0E14)
L_080A71E2:
	c.NT(22)
	c.R[15] = 0x080A71E6
	c.Thumb(0x4B08)
	c.Thumb(0x7818)
	c.R[14] = 0x080A71EB
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A71EB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2301)
	c.Thumb(0x2201)
	c.Thumb(0x0021)
	c.R[14] = 0x080A71F5
	PlantBerryTree(c)
	if c.U != 0 {
		if c.U != 0x080A71F5 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x080A71F9
	ObjectEventInteractionGetBerryTreeData(c)
	if c.U != 0 {
		if c.U != 0x080A71F9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A7208
func ObjectEventInteractionPickBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(34)
	c.Thumb(0xB500)
	c.R[15] = 0x080A720E
	c.Thumb(0x4B0F)
	c.Thumb(0x7818)
	c.R[14] = 0x080A7213
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A7213 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A7216
	c.Thumb(0x4A0E)
	c.Thumb(0x6811)
	c.Thumb(0x0003)
	c.Thumb(0x00C2)
	c.R[15] = 0x080A721E
	c.Thumb(0x480D)
	c.Thumb(0x188A)
	c.Thumb(0x5C10)
	c.Thumb(0x1E42)
	c.Thumb(0x0412)
	c.Thumb(0x0C12)
	c.Thumb(0x2A2A)
	if c.Cond(0x8) {
		goto L_080A7242
	}
	c.Thumb(0x3084)
L_080A722C:
	c.NT(20)
	c.Thumb(0x22B5)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x00DB)
	c.Thumb(0x5C59)
	c.R[14] = 0x080A723B
	c.NCallT(0x08119BF4)
	if c.U != 0 {
		if c.U != 0x080A723B {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A723E
	c.Thumb(0x4B06)
	c.Thumb(0x8018)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080A7242:
	c.NT(4)
	c.Thumb(0x2085)
	goto L_080A722C
}

// 0x080A7258
func ObjectEventInteractionRemoveBerryTree(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(40)
	c.Thumb(0xB500)
	c.R[15] = 0x080A725E
	c.Thumb(0x4B0A)
	c.Thumb(0x7818)
	c.R[14] = 0x080A7263
	c.NCallT(0x080D9FAC)
	if c.U != 0 {
		if c.U != 0x080A7263 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x080A7266
	c.Thumb(0x4B09)
	c.Thumb(0x681B)
	c.R[15] = 0x080A726A
	c.Thumb(0x4A09)
	c.Thumb(0x00C0)
	c.Thumb(0x1818)
	c.Thumb(0x1880)
	c.Thumb(0x2100)
	c.Thumb(0x2200)
	c.Thumb(0xC006)
	c.Thumb(0x791A)
	c.Thumb(0x7959)
	c.R[15] = 0x080A727C
	c.Thumb(0x4B05)
	c.Thumb(0x7818)
	c.R[14] = 0x080A7281
	c.NCallT(0x080DE3D8)
	if c.U != 0 {
		if c.U != 0x080A7281 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A7294
func PlayerHasBerries(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(10)
	c.Thumb(0xB500)
	c.Thumb(0x2004)
	c.R[14] = 0x080A729D
	c.NCallT(0x08119980)
	if c.U != 0 {
		if c.U != 0x080A729D {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080A72A0
func SetBerryTreesSeen(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(90)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x464E)
	c.Thumb(0x4645)
	c.Thumb(0xB5E0)
	c.Thumb(0xB086)
	c.Thumb(0xAB05)
	c.Thumb(0x001D)
	c.Thumb(0x1C9C)
	c.Thumb(0x0021)
	c.Thumb(0x0018)
	c.R[14] = 0x080A72BD
	c.NCallT(0x081035D8)
	if c.U != 0 {
		if c.U != 0x080A72BD {
			return
		}
		c.U = 0
	}
	c.Thumb(0x8827)
	c.Thumb(0x2300)
	c.Thumb(0x5EE8)
	c.Thumb(0x1CFB)
	c.Thumb(0x041B)
	c.Thumb(0x141B)
	c.Thumb(0x469C)
	c.Thumb(0x4681)
	c.Thumb(0x0003)
	c.Thumb(0x0FC0)
	c.Thumb(0x9000)
	c.Thumb(0x4660)
	c.Thumb(0x370B)
	c.Thumb(0x043F)
	c.Thumb(0x143F)
	c.Thumb(0x0FC0)
	c.Thumb(0x9001)
	c.Thumb(0x17F8)
	c.Thumb(0x9003)
	c.Thumb(0x4660)
	c.Thumb(0x330E)
	c.Thumb(0x041B)
	c.Thumb(0x141C)
	c.R[15] = 0x080A72EE
	c.Thumb(0x4928)
	c.Thumb(0x46A2)
	c.Thumb(0x17E4)
	c.Thumb(0x000A)
	c.Thumb(0x2300)
	c.Thumb(0x46A3)
	c.Thumb(0x9002)
	c.Thumb(0x9704)
	goto L_080A7304
L_080A72FC:
	c.NT(8)
	c.Thumb(0x3301)
	c.Thumb(0x3224)
	c.Thumb(0x2B10)
	if c.Cond(0x0) {
		goto L_080A737A
	}
L_080A7304:
	c.NT(118)
	c.Thumb(0x00D8)
	c.Thumb(0x18C0)
	c.Thumb(0x0080)
	c.Thumb(0x5C08)
	c.Thumb(0x07C0)
	if c.Cond(0x5) {
		goto L_080A72FC
	}
	c.Thumb(0x7990)
	c.Thumb(0x280C)
	if c.Cond(0x1) {
		goto L_080A72FC
	}
	c.Thumb(0x2010)
	c.Thumb(0x5E15)
	c.Thumb(0x2012)
	c.Thumb(0x5E16)
	c.Thumb(0x4654)
	c.Thumb(0x4658)
	c.Thumb(0x0FEF)
	c.Thumb(0x42AC)
	c.Thumb(0x4147)
	c.Thumb(0x46BC)
	c.Thumb(0x464F)
	c.Thumb(0x9C00)
	c.Thumb(0x17E8)
	c.Thumb(0x42BD)
	c.Thumb(0x4160)
	c.Thumb(0x4667)
	c.Thumb(0x9C01)
	c.Thumb(0x9D02)
	c.Thumb(0x4007)
	c.Thumb(0x17F0)
	c.Thumb(0x42AE)
	c.Thumb(0x4160)
	c.Thumb(0x4038)
	c.Thumb(0x0600)
	if c.Cond(0x0) {
		goto L_080A72FC
	}
	c.Thumb(0x9C03)
	c.Thumb(0x9D04)
	c.Thumb(0x0FF0)
	c.Thumb(0x42B5)
	c.Thumb(0x4160)
	c.Thumb(0x0600)
	if c.Cond(0x0) {
		goto L_080A72FC
	}
	c.R[15] = 0x080A735A
	c.Thumb(0x480E)
	c.Thumb(0x7F54)
	c.Thumb(0x6800)
	c.Thumb(0x00E4)
	c.Thumb(0x1900)
	c.R[15] = 0x080A7364
	c.Thumb(0x4C0C)
	c.Thumb(0x1900)
	c.Thumb(0x7844)
	c.Thumb(0x46A0)
	c.Thumb(0x247F)
	c.Thumb(0x0025)
	c.Thumb(0x4644)
	c.Thumb(0x3301)
	c.Thumb(0x402C)
	c.Thumb(0x7044)
	c.Thumb(0x3224)
	c.Thumb(0x2B10)
	if c.Cond(0x1) {
		goto L_080A7304
	}
L_080A737A:
	c.NT(18)
	c.Thumb(0xB006)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}
