// dataconv converts an assembled pokeemerald data object (elf32-littlearm,
// produced by arm-none-eabi-as) into native-pointer C. Each defined symbol
// becomes a packed struct whose fields are byte-runs interleaved with
// pointer-width members at the R_ARM_ABS32 relocation offsets, so 4-byte GBA
// pointers become correct 8-byte host pointers with no interior-label tricks.
package main

import (
	"debug/elf"
	"encoding/binary"
	"fmt"
	"os"
	"sort"
	"strings"
)

// A section-relative reloc (target is a section symbol) is resolved to the
// named symbol containing addend, shifting addend by 4 per intervening pointer
// so it lands at the right host byte after the 4->8 expansion.
type rawReloc struct {
	targetSym  string
	targetSec  int
	addend     uint32
	sectionRel bool
}

type secInfo struct {
	syms       []elf.Symbol
	relocOffs  []uint32
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: dataconv <in.o> <out.c>")
		os.Exit(2)
	}
	f, err := elf.Open(os.Args[1])
	must(err)
	defer f.Close()
	syms, err := f.Symbols()
	must(err)

	inFile := map[string]bool{}
	sec := map[int]*secInfo{}
	bssSec := map[int]bool{}
	for i, s := range f.Sections {
		if s.Flags&elf.SHF_ALLOC == 0 {
			continue
		}
		if s.Type == elf.SHT_PROGBITS {
			sec[i] = &secInfo{}
		} else if s.Type == elf.SHT_NOBITS {
			bssSec[i] = true
		}
	}
	var bss []elf.Symbol
	for _, s := range syms {
		if defined(s) {
			inFile[s.Name] = true
			if si, ok := sec[int(s.Section)]; ok {
				si.syms = append(si.syms, s)
			} else if bssSec[int(s.Section)] {
				bss = append(bss, s)
			}
		}
	}
	relocs := map[int]map[uint32]rawReloc{}
	for i := range sec {
		data, _ := f.Sections[i].Data()
		relocs[i] = readRelocs(f, i, syms, data)
		for off := range relocs[i] {
			sec[i].relocOffs = append(sec[i].relocOffs, off)
		}
		sort.Slice(sec[i].syms, func(a, b int) bool { return sec[i].syms[a].Value < sec[i].syms[b].Value })
		sort.Slice(sec[i].relocOffs, func(a, b int) bool { return sec[i].relocOffs[a] < sec[i].relocOffs[b] })
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by port/tools/dataconv from %s. Do not edit.\n", os.Args[1])
	fmt.Fprint(&b, "typedef unsigned char u8;\n\n")

	type ptrSlot struct {
		off  int
		expr string
	}
	type object struct {
		name  string
		bytes []byte
		slots []ptrSlot
	}
	var objects []object
	externs := map[string]bool{}

	for si := range sec {
		data, _ := f.Sections[si].Data()
		locals := sec[si].syms
		for i, s := range locals {
			start, end := uint32(s.Value), uint32(len(data))
			if i+1 < len(locals) {
				end = uint32(locals[i+1].Value)
			}
			o := object{name: s.Name}
			for pos := start; pos < end; {
				if r, ok := relocs[si][pos]; ok {
					o.slots = append(o.slots, ptrSlot{len(o.bytes), resolve(r, sec, inFile, externs)})
					o.bytes = append(o.bytes, make([]byte, 8)...)
					pos += 4
					continue
				}
				o.bytes = append(o.bytes, data[pos])
				pos++
			}
			objects = append(objects, o)
		}
	}

	var ext []string
	for n := range externs {
		if !inFile[n] {
			ext = append(ext, n)
		}
	}
	sort.Strings(ext)
	for _, n := range ext {
		fmt.Fprintf(&b, "extern u8 %s[];\n", n)
	}
	b.WriteString("\n")
	for _, o := range objects {
		fmt.Fprintf(&b, "extern u8 %s[];\n", o.name)
	}
	for _, s := range bss {
		n := s.Size
		if n == 0 {
			n = 1
		}
		fmt.Fprintf(&b, "u8 %s[%d] __attribute__((weak));\n", s.Name, n)
	}
	b.WriteString("\n")
	for _, o := range objects {
		fmt.Fprintf(&b, "u8 %s[%d] __attribute__((weak)) = {%s};\n", o.name, len(o.bytes), byteList(o.bytes))
	}

	fmt.Fprint(&b, "\nstatic const struct { u8 *base; unsigned off; const void *tgt; } _relocs[] __attribute__((used)) = {\n")
	nrel := 0
	for _, o := range objects {
		for _, sl := range o.slots {
			fmt.Fprintf(&b, "  {%s, %d, %s},\n", o.name, sl.off, sl.expr)
			nrel++
		}
	}
	fmt.Fprint(&b, "};\n")
	if nrel > 0 {
		fmt.Fprint(&b, "__attribute__((constructor)) static void _apply(void){\n")
		fmt.Fprint(&b, "  for (unsigned i=0;i<sizeof(_relocs)/sizeof(_relocs[0]);i++)\n")
		fmt.Fprint(&b, "    __builtin_memcpy(_relocs[i].base+_relocs[i].off,&_relocs[i].tgt,sizeof(void*));\n}\n")
	}
	must(os.WriteFile(os.Args[2], []byte(b.String()), 0644))
	fmt.Fprintf(os.Stderr, "wrote %d objects, %d externs -> %s\n", len(objects), len(ext), os.Args[2])
}

func resolve(r rawReloc, sec map[int]*secInfo, inFile, externs map[string]bool) string {
	if !r.sectionRel {
		externs[r.targetSym] = true
		if inFile[r.targetSym] {
			return withAddend("(const void *)&"+r.targetSym, r.addend)
		}
		return withAddend("(const void *)"+r.targetSym, r.addend)
	}
	si, ok := sec[r.targetSec]
	if !ok || len(si.syms) == 0 {
		return fmt.Sprintf("(const void *)0 /* unresolved section reloc +%d */", r.addend)
	}
	idx := sort.Search(len(si.syms), func(i int) bool { return uint32(si.syms[i].Value) > r.addend }) - 1
	if idx < 0 {
		idx = 0
	}
	s := si.syms[idx]
	src := r.addend - uint32(s.Value)
	between := uint32(0)
	for _, off := range si.relocOffs {
		if off >= uint32(s.Value) && off < r.addend {
			between++
		}
	}
	host := src + 4*between
	externs[s.Name] = true
	if host == 0 {
		return "(const void *)&" + s.Name
	}
	return fmt.Sprintf("(const void *)((const u8 *)&%s + %d)", s.Name, host)
}

func withAddend(base string, addend uint32) string {
	if addend == 0 {
		return base
	}
	return fmt.Sprintf("(const void *)((const u8 *)%s + %d)", strings.TrimPrefix(base, "(const void *)"), addend)
}

func readRelocs(f *elf.File, secIdx int, syms []elf.Symbol, data []byte) map[uint32]rawReloc {
	out := map[uint32]rawReloc{}
	for _, rs := range f.Sections {
		if rs.Type != elf.SHT_REL || int(rs.Info) != secIdx {
			continue
		}
		rd, _ := rs.Data()
		for off := 0; off+8 <= len(rd); off += 8 {
			roff := binary.LittleEndian.Uint32(rd[off:])
			info := binary.LittleEndian.Uint32(rd[off+4:])
			symIdx := info >> 8
			if symIdx == 0 || int(symIdx) > len(syms) {
				continue
			}
			s := syms[symIdx-1]
			addend := binary.LittleEndian.Uint32(data[roff:])
			if elf.ST_TYPE(s.Info) == elf.STT_SECTION || s.Name == "" {
				out[roff] = rawReloc{targetSec: int(s.Section), addend: addend, sectionRel: true}
			} else {
				out[roff] = rawReloc{targetSym: s.Name, addend: addend}
			}
		}
	}
	return out
}

func byteList(b []byte) string {
	parts := make([]string, len(b))
	for i, by := range b {
		parts[i] = fmt.Sprintf("%d", by)
	}
	return strings.Join(parts, ",")
}

func defined(s elf.Symbol) bool {
	return s.Name != "" && !strings.HasPrefix(s.Name, "$") &&
		s.Section != elf.SHN_UNDEF && s.Section < elf.SHN_LORESERVE &&
		elf.ST_TYPE(s.Info) != elf.STT_SECTION
}

func sanitize(s string) string {
	return strings.Map(func(r rune) rune {
		if r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, s)
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
