// Code generated by cmd/recomp from pokeemerald_modern.elf. DO NOT EDIT.
package confetti_util

import g "dbut.dev/sapphire/gba"

var regs0 = []reg{
	{0x080AE2D4, 152, ConfettiUtil_Init},
	{0x080AE36C, 112, ConfettiUtil_Free},
	{0x080AE3DC, 216, ConfettiUtil_Update},
	{0x080AE4B4, 64, SetAnimAndTileNum},
	{0x080AE4F4, 48, ConfettiUtil_SetCallback},
	{0x080AE524, 72, ConfettiUtil_SetData},
	{0x080AE56C, 252, ConfettiUtil_AddNew},
	{0x080AE668, 112, ConfettiUtil_Remove},
	{0x080AE6D8, 4, stub_080AE6D8},
}

// 0x080AE2D4
func ConfettiUtil_Init(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(16)
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[6], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[5], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	c.R[14] = c.R[9]
	c.R[7] = c.R[8]
	{
		v, cy := g.ShiftLSL(c.R[0], 24)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
	}
	{
		v, cy := g.ShiftLSR(c.R[0], 24)
		c.R[6] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[0], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[0], 0, val))
	}
	if c.Cond(0x1) {
		goto L_080AE2F2
	}
L_080AE2E4:
	c.NT(2)
	c.R[0] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
L_080AE2E6:
	c.NT(12)
	{
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	c.R[9] = c.R[7]
	c.R[8] = c.R[6]
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080AE2F2:
	c.NT(18)
	c.R[0] = 8
	c.SetNZ(int32(8) < 0, 8 == 0)
	c.R[14] = 0x080AE2F9
	c.NCallT(0x081292A4)
	if c.U != 0 {
		if c.U != 0x080AE2F9 {
			return
		}
		c.U = 0
	}
	c.R[4] = c.Memory.Read32(0x080AE364, true, false)
	{
		op1, op2 := c.R[0], uint32(0)
		val := g.SUB(op1, op2, 0)
		c.R[5] = uint32(val)
		c.SetNZCV(g.FlagArithSub(op1, op2, val))
	}
	c.Memory.Set32(c.R[4]+0, c.R[0], true, false)
	if c.Cond(0x0) {
		goto L_080AE2E4
	}
	{
		op1, op2 := c.R[6], uint32(0)
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		val := g.SUB(c.R[6], 64, 0)
		c.SetNZCV(g.FlagArithSub(c.R[6], 64, val))
	}
	if c.Cond(0x8) {
		goto L_080AE354
	}
L_080AE306:
	c.NT(34)
	{
		v, cy := g.ShiftLSL(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 24)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 23)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[0], uint32(c.R[2])
		val := g.ADD(op1, op2, 0)
		c.R[0] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[0], 4)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[8] = c.R[2]
	c.R[14] = 0x080AE317
	c.NCallT(0x081292A4)
	if c.U != 0 {
		if c.U != 0x080AE317 {
			return
		}
		c.U = 0
	}
	c.R[6] = c.Memory.Read32(c.R[4]+0, true, false)
	c.Memory.Set32(c.R[5]+4, c.R[0], true, false)
	c.R[7] = c.Memory.Read32(c.R[6]+4, true, false)
	{
		val := g.SUB(c.R[7], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[7], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE358
	}
	c.R[3] = c.R[8]
	c.Memory.Set8(c.R[6]+0, uint8(c.R[3]), true, false)
	c.R[3] = c.Memory.Read32(0x080AE368, true, false)
	c.R[5] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[9] = c.R[3]
L_080AE32A:
	c.NT(40)
	{
		v, cy := g.ShiftLSL(c.R[5], 1)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[4], uint32(c.R[5])
		val := g.ADD(op1, op2, 0)
		c.R[4] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[4], 4)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[7], uint32(c.R[4])
		val := g.ADD(op1, op2, 0)
		c.R[0] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[2] = 8
	c.SetNZ(int32(8) < 0, 8 == 0)
	c.R[1] = c.R[9]
	c.R[14] = 0x080AE33B
	c.NCallT(0x082E6960)
	if c.U != 0 {
		if c.U != 0x080AE33B {
			return
		}
		c.U = 0
	}
	c.R[2] = 4
	c.SetNZ(int32(4) < 0, 4 == 0)
	c.R[7] = c.Memory.Read32(c.R[6]+4, true, false)
	{
		op1, op2 := c.R[7], uint32(c.R[4])
		val := g.ADD(op1, op2, 0)
		c.R[4] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[4]+25, true, false))
	{
		val := g.ADD(c.R[5], 1, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[5], 1, val))
		c.R[5] = uint32(val)
	}
	{
		v := uint32(c.R[3] | c.R[2])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.Memory.Set8(c.R[4]+25, uint8(c.R[3]), true, false)
	{
		v, cy := g.ShiftLSL(c.R[5], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[8], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[8], c.R[3], val))
	}
	if c.Cond(0x8) {
		goto L_080AE32A
	}
	c.R[0] = 1
	c.SetNZ(int32(1) < 0, 1 == 0)
	goto L_080AE2E6
L_080AE354:
	c.NT(4)
	c.R[3] = 64
	c.SetNZ(int32(64) < 0, 64 == 0)
	goto L_080AE306
L_080AE358:
	c.NT(8)
	c.R[0] = c.R[6]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	c.R[14] = 0x080AE35F
	c.NCallT(0x081292E8)
	if c.U != 0 {
		if c.U != 0x080AE35F {
			return
		}
		c.U = 0
	}
	c.Memory.Set32(c.R[4]+0, c.R[7], true, false)
	goto L_080AE2E4
}

// 0x080AE36C
func ConfettiUtil_Free(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[6], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[5], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	c.R[5] = c.Memory.Read32(0x080AE3D0, true, false)
	c.R[6] = c.Memory.Read32(c.R[5]+0, true, false)
	{
		val := g.SUB(c.R[6], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[6], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE3C6
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[6]+0, true, false))
	{
		val := g.SUB(c.R[3], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE3CA
	}
	c.R[3] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[2] = c.Memory.Read32(0x080AE3D4, true, false)
	c.R[1] = c.Memory.Read32(0x080AE3D8, true, false)
L_080AE382:
	c.NT(24)
	c.R[0] = c.R[1]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	{
		addr := c.R[0]
		c.R[4] = c.Memory.Read32(addr, true, false)
		addr += 4
		c.R[7] = c.Memory.Read32(addr, true, false)
		addr += 4
		c.R[0] = addr
	}
	{
		addr := c.R[2]
		c.Memory.Set32(addr, c.R[4], true, false)
		addr += 4
		c.Memory.Set32(addr, c.R[7], true, false)
		addr += 4
		c.R[2] = addr
	}
	{
		val := g.ADD(c.R[3], 1, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[3], 1, val))
		c.R[3] = uint32(val)
	}
	c.R[0] = uint32(c.Memory.Read8(c.R[6]+0, true, false))
	{
		v, cy := g.ShiftLSL(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[0], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[0], c.R[3], val))
	}
	if c.Cond(0x8) {
		goto L_080AE382
	}
	{
		v, cy := g.ShiftLSL(c.R[0], 1)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[2], uint32(c.R[0])
		val := g.ADD(op1, op2, 0)
		c.R[2] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[2], 4)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
L_080AE39A:
	c.NT(30)
	c.R[1] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[0] = c.Memory.Read32(c.R[6]+4, true, false)
	c.R[14] = 0x080AE3A3
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x080AE3A3 {
			return
		}
		c.U = 0
	}
	c.R[0] = c.Memory.Read32(c.R[6]+4, true, false)
	c.R[14] = 0x080AE3A9
	c.NCallT(0x081292E8)
	if c.U != 0 {
		if c.U != 0x080AE3A9 {
			return
		}
		c.U = 0
	}
	c.R[4] = c.Memory.Read32(c.R[5]+0, true, false)
	c.R[2] = 8
	c.SetNZ(int32(8) < 0, 8 == 0)
	c.R[1] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[0] = c.R[4]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	c.R[14] = 0x080AE3B5
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x080AE3B5 {
			return
		}
		c.U = 0
	}
	c.R[0] = c.R[4]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	c.R[14] = 0x080AE3BB
	c.NCallT(0x081292E8)
	if c.U != 0 {
		if c.U != 0x080AE3BB {
			return
		}
		c.U = 0
	}
	c.R[3] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[0] = 1
	c.SetNZ(int32(1) < 0, 1 == 0)
	c.Memory.Set32(c.R[5]+0, c.R[3], true, false)
L_080AE3C0:
	c.NT(6)
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080AE3C6:
	c.NT(4)
	c.R[0] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	goto L_080AE3C0
L_080AE3CA:
	c.NT(4)
	c.R[2] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	goto L_080AE39A
}

// 0x080AE3DC
func ConfettiUtil_Update(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(40)
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[6], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[5], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	c.R[7] = c.R[8]
	c.R[14] = c.R[9]
	c.R[3] = c.Memory.Read32(0x080AE4A8, true, false)
	c.R[8] = c.R[3]
	c.R[3] = c.Memory.Read32(c.R[3]+0, true, false)
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
	}
	{
		val := g.SUB(c.R[3], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE4A4
	}
	c.R[0] = c.Memory.Read32(c.R[3]+4, true, false)
	{
		val := g.SUB(c.R[0], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[0], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE45A
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[3]+0, true, false))
	{
		val := g.SUB(c.R[3], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE458
	}
	c.R[3] = c.Memory.Read32(0x080AE4AC, true, false)
	c.R[5] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[9] = c.R[3]
	c.R[6] = c.Memory.Read32(0x080AE4B0, true, false)
	goto L_080AE418
L_080AE404:
	c.NT(4)
	c.R[3] = c.R[8]
	c.R[7] = c.Memory.Read32(c.R[3]+0, true, false)
L_080AE408:
	c.NT(12)
	{
		val := g.ADD(c.R[5], 1, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[5], 1, val))
		c.R[5] = uint32(val)
	}
	c.R[2] = uint32(c.Memory.Read8(c.R[7]+0, true, false))
	{
		v, cy := g.ShiftLSL(c.R[5], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[2], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[2], c.R[3], val))
	}
	if c.Cond(0x9) {
		goto L_080AE458
	}
L_080AE414:
	c.NT(4)
	c.R[0] = c.Memory.Read32(c.R[7]+4, true, false)
	{
		val := g.ADD(c.R[6], 8, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[6], 8, val))
		c.R[6] = uint32(val)
	}
L_080AE418:
	c.NT(26)
	c.R[2] = 3
	c.SetNZ(int32(3) < 0, 3 == 0)
	{
		v, cy := g.ShiftLSL(c.R[5], 1)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[4], uint32(c.R[5])
		val := g.ADD(op1, op2, 0)
		c.R[4] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[4], 4)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[0], uint32(c.R[4])
		val := g.ADD(op1, op2, 0)
		c.R[0] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[0]+25, true, false))
	{
		v := uint32(c.R[3] & c.R[2])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	{
		val := g.SUB(c.R[3], 3, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 3, val))
	}
	if c.Cond(0x1) {
		goto L_080AE404
	}
	c.R[3] = c.Memory.Read32(c.R[0]+44, true, false)
	{
		val := g.SUB(c.R[3], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE434
	}
	c.R[14] = 0x080AE435
	stub_080AE6D8(c)
	if c.U != 0 {
		if c.U != 0x080AE435 {
			return
		}
		c.U = 0
	}
L_080AE434:
	c.NT(36)
	c.R[3] = c.R[8]
	c.R[2] = 4
	c.SetNZ(int32(4) < 0, 4 == 0)
	c.R[7] = c.Memory.Read32(c.R[3]+0, true, false)
	c.R[1] = c.Memory.Read32(c.R[7]+4, true, false)
	{
		op1, op2 := c.R[1], uint32(c.R[4])
		val := g.ADD(op1, op2, 0)
		c.R[1] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[1]+25, true, false))
	{
		v := c.R[2] & c.R[3]
		c.SetNZ(int32(v) < 0, v == 0)
	}
	if c.Cond(0x0) {
		goto L_080AE466
	}
	c.R[3] = c.R[6]
	c.SetNZ(int32(c.R[3]) < 0, c.R[3] == 0)
	c.R[2] = c.R[9]
	{
		addr := c.R[2]
		c.R[0] = c.Memory.Read32(addr, true, false)
		addr += 4
		c.R[1] = c.Memory.Read32(addr, true, false)
		addr += 4
		c.R[2] = addr
	}
	{
		addr := c.R[3]
		c.Memory.Set32(addr, c.R[0], true, false)
		addr += 4
		c.Memory.Set32(addr, c.R[1], true, false)
		addr += 4
		c.R[3] = addr
	}
	{
		val := g.ADD(c.R[5], 1, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[5], 1, val))
		c.R[5] = uint32(val)
	}
	c.R[2] = uint32(c.Memory.Read8(c.R[7]+0, true, false))
	{
		v, cy := g.ShiftLSL(c.R[5], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[2], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[2], c.R[3], val))
	}
	if c.Cond(0x8) {
		goto L_080AE414
	}
L_080AE458:
	c.NT(2)
	c.R[0] = 1
	c.SetNZ(int32(1) < 0, 1 == 0)
L_080AE45A:
	c.NT(12)
	{
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	c.R[9] = c.R[7]
	c.R[8] = c.R[6]
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080AE466:
	c.NT(60)
	c.R[0] = c.LoadHalf(c.R[1] + 14)
	c.R[2] = c.LoadHalf(c.R[1] + 10)
	{
		op1, op2 := c.R[2], uint32(c.R[0])
		val := g.ADD(op1, op2, 0)
		c.R[2] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.Memory.Set8(c.R[1]+0, uint8(c.R[2]), true, false)
	c.R[4] = c.LoadHalf(c.R[1] + 8)
	c.R[2] = c.LoadHalf(c.R[1] + 12)
	{
		op1, op2 := c.R[4], uint32(c.R[2])
		val := g.ADD(op1, op2, 0)
		c.R[4] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[2] = c.LoadHalf(c.R[1] + 2)
	{
		v, cy := g.ShiftLSL(c.R[4], 23)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[2], 9)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[4], 23)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSL(c.R[2], 9)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v := uint32(c.R[2] | c.R[4])
		c.R[2] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.R[0] = c.LoadHalf(c.R[1] + 20)
	c.Memory.Set16(c.R[1]+2, uint16(c.R[2]), true, false)
	{
		v, cy := g.ShiftLSL(c.R[3], 27)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[2] = c.LoadHalf(c.R[1] + 4)
	{
		v, cy := g.ShiftLSR(c.R[3], 30)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSL(c.R[0], 22)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[0], 22)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSL(c.R[3], 10)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[2], 12)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v := uint32(c.R[3] | c.R[0])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	{
		v, cy := g.ShiftLSL(c.R[2], 12)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v := uint32(c.R[3] | c.R[2])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.R[0] = c.R[6]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	c.R[2] = 8
	c.SetNZ(int32(8) < 0, 8 == 0)
	c.Memory.Set16(c.R[1]+4, uint16(c.R[3]), true, false)
	c.R[14] = 0x080AE4A3
	c.NCallT(0x082E6960)
	if c.U != 0 {
		if c.U != 0x080AE4A3 {
			return
		}
		c.U = 0
	}
	goto L_080AE408
L_080AE4A4:
	c.NT(4)
	c.R[0] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	goto L_080AE45A
}

// 0x080AE4B4
func SetAnimAndTileNum(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(46)
	{
		v, cy := g.ShiftLSL(c.R[1], 24)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[6], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[5], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	c.R[5] = c.R[0]
	c.SetNZ(int32(c.R[5]) < 0, c.R[5] == 0)
	{
		v, cy := g.ShiftLSR(c.R[1], 24)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[0], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[0], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE4E6
	}
	c.R[0] = c.LoadHalf(c.R[0] + 16)
	c.R[14] = 0x080AE4C7
	c.NCallT(0x081B1BEC)
	if c.U != 0 {
		if c.U != 0x080AE4C7 {
			return
		}
		c.U = 0
	}
	c.R[3] = c.Memory.Read32(0x080AE4F0, true, false)
	c.R[6] = c.R[0]
	c.SetNZ(int32(c.R[6]) < 0, c.R[6] == 0)
	{
		val := g.SUB(c.R[0], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[0], c.R[3], val))
	}
	if c.Cond(0x0) {
		goto L_080AE4E6
	}
	c.R[1] = uint32(c.Memory.Read8(c.R[5]+3, true, false))
	c.R[0] = uint32(c.Memory.Read8(c.R[5]+1, true, false))
	{
		v, cy := g.ShiftLSR(c.R[1], 6)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.Memory.Set8(c.R[5]+24, uint8(c.R[4]), true, false)
	{
		v, cy := g.ShiftLSR(c.R[0], 6)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[14] = 0x080AE4DD
	c.NCallT(0x080C8474)
	if c.U != 0 {
		if c.U != 0x080AE4DD {
			return
		}
		c.U = 0
	}
	{
		val := g.MUL(c.R[0], c.R[4], 0)
		v := uint32(val)
		c.R[0] = v
		c.SetNZCV(g.FlagArithAdd(c.R[0], c.R[4], val))
	}
	{
		op1, op2 := c.R[6], uint32(c.R[0])
		val := g.ADD(op1, op2, 0)
		c.R[1] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.Memory.Set16(c.R[5]+20, uint16(c.R[1]), true, false)
	c.R[0] = 1
	c.SetNZ(int32(1) < 0, 1 == 0)
	goto L_080AE4E8
L_080AE4E6:
	c.NT(2)
	c.R[0] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
L_080AE4E8:
	c.NT(6)
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080AE4F4
func ConfettiUtil_SetCallback(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(36)
	c.R[3] = c.Memory.Read32(0x080AE520, true, false)
	c.R[2] = c.Memory.Read32(c.R[3]+0, true, false)
	{
		v, cy := g.ShiftLSL(c.R[0], 24)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[0], 24)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[2], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[2], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE51A
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[2]+0, true, false))
	{
		val := g.SUB(c.R[3], c.R[0], 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], c.R[0], val))
	}
	if c.Cond(0x9) {
		goto L_080AE51A
	}
	{
		v, cy := g.ShiftLSL(c.R[0], 1)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[2] = c.Memory.Read32(c.R[2]+4, true, false)
	{
		op1, op2 := c.R[3], uint32(c.R[0])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[3], 4)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[2], uint32(c.R[3])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[2] = uint32(c.Memory.Read8(c.R[3]+25, true, false))
	{
		v, cy := g.ShiftLSL(c.R[2], 31)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	if c.Cond(0x5) {
		goto L_080AE51A
	}
	c.Memory.Set32(c.R[3]+44, c.R[1], true, false)
L_080AE518:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080AE51A:
	c.NT(4)
	c.R[0] = 255
	c.SetNZ(int32(255) < 0, 255 == 0)
	goto L_080AE518
}

// 0x080AE524
func ConfettiUtil_SetData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(58)
	c.R[3] = c.Memory.Read32(0x080AE568, true, false)
	c.R[3] = c.Memory.Read32(c.R[3]+0, true, false)
	{
		v, cy := g.ShiftLSL(c.R[0], 24)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSL(c.R[1], 24)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[12] = c.R[3]
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	{
		v, cy := g.ShiftLSR(c.R[0], 24)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[1], 24)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[3], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE55E
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[3]+0, true, false))
	{
		val := g.SUB(c.R[3], c.R[0], 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], c.R[0], val))
	}
	if c.Cond(0x9) {
		goto L_080AE55E
	}
	c.R[4] = c.R[12]
	{
		v, cy := g.ShiftLSL(c.R[0], 1)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[4] = c.Memory.Read32(c.R[4]+4, true, false)
	{
		op1, op2 := c.R[3], uint32(c.R[0])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[3], 4)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[4], uint32(c.R[3])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[4] = uint32(c.Memory.Read8(c.R[3]+25, true, false))
	{
		v, cy := g.ShiftLSL(c.R[4], 31)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	if c.Cond(0x5) {
		goto L_080AE55E
	}
	{
		val := g.SUB(c.R[1], 7, 0)
		c.SetNZCV(g.FlagArithSub(c.R[1], 7, val))
	}
	if c.Cond(0x8) {
		goto L_080AE55E
	}
	{
		val := g.ADD(c.R[1], 12, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[1], 12, val))
		c.R[1] = uint32(val)
	}
	{
		v, cy := g.ShiftLSL(c.R[1], 1)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[3], uint32(c.R[1])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.Memory.Set16(c.R[3]+2, uint16(c.R[2]), true, false)
	goto L_080AE560
L_080AE55E:
	c.NT(2)
	c.R[0] = 255
	c.SetNZ(int32(255) < 0, 255 == 0)
L_080AE560:
	c.NT(6)
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080AE56C
func ConfettiUtil_AddNew(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(76)
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[6], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[5], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	c.R[14] = c.R[11]
	c.R[7] = c.R[10]
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
	}
	c.R[7] = c.R[8]
	c.R[14] = c.R[9]
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[7], true, false)
	}
	c.R[13] -= 4
	c.R[11] = c.R[3]
	{
		v, cy := g.ShiftLSL(c.R[2], 16)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[3] = c.Memory.Read32(c.R[13]+48, true, false)
	{
		v, cy := g.ShiftLSR(c.R[2], 16)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[5] = c.R[0]
	c.SetNZ(int32(c.R[5]) < 0, c.R[5] == 0)
	c.R[0] = c.Memory.Read32(c.R[13]+44, true, false)
	{
		v, cy := g.ShiftLSL(c.R[3], 24)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[9] = c.R[2]
	c.R[2] = c.Memory.Read32(c.R[13]+40, true, false)
	{
		v, cy := g.ShiftLSL(c.R[0], 24)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[3], 24)
		c.R[7] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[3] = c.Memory.Read32(0x080AE660, true, false)
	c.R[10] = c.R[2]
	{
		v, cy := g.ShiftLSR(c.R[0], 24)
		c.R[2] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.Memory.Set32(c.R[13]+0, c.R[2], true, false)
	{
		v, cy := g.ShiftLSL(c.R[1], 16)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[2] = c.Memory.Read32(c.R[3]+0, true, false)
	{
		v, cy := g.ShiftLSR(c.R[1], 16)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[8] = c.R[1]
	{
		val := g.SUB(c.R[2], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[2], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE64C
	}
	{
		val := g.SUB(c.R[5], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[5], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE64C
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[2]+0, true, false))
	{
		val := g.SUB(c.R[3], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[3], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE64C
	}
	c.R[6] = c.Memory.Read32(c.R[2]+4, true, false)
	c.R[4] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[2] = 1
	c.SetNZ(int32(1) < 0, 1 == 0)
	goto L_080AE5C4
L_080AE5B8:
	c.NT(12)
	{
		val := g.ADD(c.R[4], 1, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[4], 1, val))
		c.R[4] = uint32(val)
	}
	{
		v, cy := g.ShiftLSL(c.R[4], 24)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[4], 24)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.ADD(c.R[6], 48, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[6], 48, val))
		c.R[6] = uint32(val)
	}
	{
		val := g.SUB(c.R[4], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[4], c.R[3], val))
	}
	if c.Cond(0x0) {
		goto L_080AE64C
	}
L_080AE5C4:
	c.NT(90)
	c.R[1] = uint32(c.Memory.Read8(c.R[6]+25, true, false))
	{
		v := c.R[2] & c.R[1]
		c.SetNZ(int32(v) < 0, v == 0)
	}
	if c.Cond(0x1) {
		goto L_080AE5B8
	}
	c.R[2] = 48
	c.SetNZ(int32(48) < 0, 48 == 0)
	c.R[1] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[0] = c.R[6]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	c.R[14] = 0x080AE5D5
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x080AE5D5 {
			return
		}
		c.U = 0
	}
	c.R[3] = 3
	c.SetNZ(int32(3) < 0, 3 == 0)
	c.R[2] = 8
	c.SetNZ(int32(8) < 0, 8 == 0)
	c.R[1] = c.R[5]
	c.SetNZ(int32(c.R[1]) < 0, c.R[1] == 0)
	c.Memory.Set8(c.R[6]+25, uint8(c.R[3]), true, false)
	c.R[0] = c.R[6]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
	c.Memory.Set8(c.R[6]+22, uint8(c.R[4]), true, false)
	c.R[14] = 0x080AE5E5
	c.NCallT(0x082E6960)
	if c.U != 0 {
		if c.U != 0x080AE5E5 {
			return
		}
		c.U = 0
	}
	c.R[3] = c.R[8]
	c.Memory.Set16(c.R[6]+16, uint16(c.R[3]), true, false)
	c.R[3] = c.R[11]
	c.R[0] = c.R[9]
	c.Memory.Set16(c.R[6]+8, uint16(c.R[3]), true, false)
	c.R[3] = c.R[10]
	c.Memory.Set16(c.R[6]+18, uint16(c.R[0]), true, false)
	c.Memory.Set16(c.R[6]+10, uint16(c.R[3]), true, false)
	c.R[14] = 0x080AE5F9
	c.NCallT(0x081B1DFC)
	if c.U != 0 {
		if c.U != 0x080AE5F9 {
			return
		}
		c.U = 0
	}
	c.R[3] = 15
	c.SetNZ(int32(15) < 0, 15 == 0)
	c.R[2] = uint32(c.Memory.Read8(c.R[6]+5, true, false))
	{
		v, cy := g.ShiftLSL(c.R[0], 4)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v := uint32(c.R[3] & c.R[2])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	{
		v := uint32(c.R[3] | c.R[0])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.Memory.Set8(c.R[6]+5, uint8(c.R[3]), true, false)
	{
		val := g.SUB(c.R[7], 3, 0)
		c.SetNZCV(g.FlagArithSub(c.R[7], 3, val))
	}
	if c.Cond(0x8) {
		goto L_080AE624
	}
	c.R[3] = 3
	c.SetNZ(int32(3) < 0, 3 == 0)
	c.R[0] = 24
	c.SetNZ(int32(24) < 0, 24 == 0)
	c.R[2] = uint32(c.Memory.Read8(c.R[6]+25, true, false))
	{
		v := uint32(c.R[3] & c.R[7])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	{
		v, cy := g.ShiftLSL(c.R[3], 3)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v := uint32(c.R[2] &^ c.R[0])
		c.R[2] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	{
		v := uint32(c.R[2] | c.R[1])
		c.R[2] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.R[1] = 12
	c.SetNZ(int32(12) < 0, 12 == 0)
	c.Memory.Set8(c.R[6]+25, uint8(c.R[2]), true, false)
	c.R[2] = uint32(c.Memory.Read8(c.R[6]+5, true, false))
	{
		v, cy := g.ShiftLSL(c.R[3], 2)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v := uint32(c.R[2] &^ c.R[1])
		c.R[2] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	{
		v := uint32(c.R[3] | c.R[2])
		c.R[3] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.Memory.Set8(c.R[6]+5, uint8(c.R[3]), true, false)
L_080AE624:
	c.NT(32)
	c.R[0] = c.LoadHalf(c.R[6] + 16)
	c.R[14] = 0x080AE62B
	c.NCallT(0x081B1BEC)
	if c.U != 0 {
		if c.U != 0x080AE62B {
			return
		}
		c.U = 0
	}
	c.R[3] = c.Memory.Read32(0x080AE664, true, false)
	c.R[4] = c.R[0]
	c.SetNZ(int32(c.R[4]) < 0, c.R[4] == 0)
	{
		val := g.SUB(c.R[0], c.R[3], 0)
		c.SetNZCV(g.FlagArithSub(c.R[0], c.R[3], val))
	}
	if c.Cond(0x0) {
		goto L_080AE648
	}
	c.R[5] = c.Memory.Read32(c.R[13]+0, true, false)
	c.R[1] = uint32(c.Memory.Read8(c.R[6]+3, true, false))
	c.R[0] = uint32(c.Memory.Read8(c.R[6]+1, true, false))
	c.Memory.Set8(c.R[6]+24, uint8(c.R[5]), true, false)
	{
		v, cy := g.ShiftLSR(c.R[1], 6)
		c.R[1] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[0], 6)
		c.R[0] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[14] = 0x080AE643
	c.NCallT(0x080C8474)
	if c.U != 0 {
		if c.U != 0x080AE643 {
			return
		}
		c.U = 0
	}
	{
		val := g.MUL(c.R[5], c.R[0], 0)
		v := uint32(val)
		c.R[5] = v
		c.SetNZCV(g.FlagArithAdd(c.R[5], c.R[0], val))
	}
	{
		op1, op2 := c.R[4], uint32(c.R[5])
		val := g.ADD(op1, op2, 0)
		c.R[4] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.Memory.Set16(c.R[6]+20, uint16(c.R[4]), true, false)
L_080AE648:
	c.NT(4)
	c.R[0] = uint32(c.Memory.Read8(c.R[6]+22, true, false))
	goto L_080AE64E
L_080AE64C:
	c.NT(2)
	c.R[0] = 255
	c.SetNZ(int32(255) < 0, 255 == 0)
L_080AE64E:
	c.NT(18)
	c.R[13] += 4
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	c.R[11] = c.R[7]
	c.R[10] = c.R[6]
	c.R[9] = c.R[5]
	c.R[8] = c.R[4]
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[7] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x080AE668
func ConfettiUtil_Remove(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(78)
	c.R[3] = c.Memory.Read32(0x080AE6C4, true, false)
	{
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[14], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[6], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[5], true, false)
		c.R[13] -= 4
		c.Memory.Set32(c.R[13], c.R[4], true, false)
	}
	c.R[6] = c.Memory.Read32(c.R[3]+0, true, false)
	{
		v, cy := g.ShiftLSL(c.R[0], 24)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		v, cy := g.ShiftLSR(c.R[4], 24)
		c.R[4] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		val := g.SUB(c.R[6], 0, 0)
		c.SetNZCV(g.FlagArithSub(c.R[6], 0, val))
	}
	if c.Cond(0x0) {
		goto L_080AE6BE
	}
	{
		v, cy := g.ShiftLSL(c.R[4], 1)
		c.R[5] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	c.R[0] = c.Memory.Read32(c.R[6]+4, true, false)
	{
		op1, op2 := c.R[5], uint32(c.R[4])
		val := g.ADD(op1, op2, 0)
		c.R[5] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	{
		v, cy := g.ShiftLSL(c.R[5], 4)
		c.R[5] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[0], uint32(c.R[5])
		val := g.ADD(op1, op2, 0)
		c.R[0] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[3] = uint32(c.Memory.Read8(c.R[0]+25, true, false))
	{
		v, cy := g.ShiftLSL(c.R[3], 31)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	if c.Cond(0x5) {
		goto L_080AE6BE
	}
	c.R[2] = 48
	c.SetNZ(int32(48) < 0, 48 == 0)
	c.R[1] = 0
	c.SetNZ(int32(0) < 0, 0 == 0)
	c.R[14] = 0x080AE68F
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x080AE68F {
			return
		}
		c.U = 0
	}
	c.R[3] = c.Memory.Read32(c.R[6]+4, true, false)
	{
		op1, op2 := c.R[3], uint32(c.R[5])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[1] = c.Memory.Read32(c.R[3]+0, true, false)
	c.R[2] = c.Memory.Read32(0x080AE6C8, true, false)
	{
		v := uint32(c.R[1] & c.R[2])
		c.R[1] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.R[2] = c.Memory.Read32(0x080AE6CC, true, false)
	{
		v := uint32(c.R[2] | c.R[1])
		c.R[2] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.R[1] = 4
	c.SetNZ(int32(4) < 0, 4 == 0)
	c.Memory.Set32(c.R[3]+0, c.R[2], true, false)
	c.R[2] = uint32(c.Memory.Read8(c.R[3]+25, true, false))
	{
		v := uint32(c.R[2] | c.R[1])
		c.R[2] = v
		c.SetNZ(int32(v) < 0, v == 0)
	}
	c.Memory.Set8(c.R[3]+25, uint8(c.R[2]), true, false)
	c.R[3] = c.R[4]
	c.SetNZ(int32(c.R[3]) < 0, c.R[3] == 0)
	c.R[2] = c.Memory.Read32(0x080AE6D0, true, false)
	{
		val := g.ADD(c.R[3], 71, 0)
		c.SetNZCV(g.FlagArithAdd(c.R[3], 71, val))
		c.R[3] = uint32(val)
	}
	{
		v, cy := g.ShiftLSL(c.R[3], 3)
		c.R[3] = v
		c.SetNZC(int32(v) < 0, v == 0, cy)
	}
	{
		op1, op2 := c.R[3], uint32(c.R[2])
		val := g.ADD(op1, op2, 0)
		c.R[3] = uint32(val)
		c.SetNZCV(g.FlagArithAdd(op1, op2, val))
	}
	c.R[2] = c.Memory.Read32(0x080AE6D4, true, false)
	{
		addr := c.R[2]
		c.R[0] = c.Memory.Read32(addr, true, false)
		addr += 4
		c.R[5] = c.Memory.Read32(addr, true, false)
		addr += 4
		c.R[2] = addr
	}
	{
		addr := c.R[3]
		c.Memory.Set32(addr, c.R[0], true, false)
		addr += 4
		c.Memory.Set32(addr, c.R[5], true, false)
		addr += 4
		c.R[3] = addr
	}
	c.R[0] = c.R[4]
	c.SetNZ(int32(c.R[0]) < 0, c.R[0] == 0)
L_080AE6B8:
	c.NT(6)
	{
		c.R[4] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[5] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
		c.R[6] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		c.R[1] = c.Memory.Read32(c.R[13], true, false)
		c.R[13] += 4
	}
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_080AE6BE:
	c.NT(4)
	c.R[0] = 255
	c.SetNZ(int32(255) < 0, 255 == 0)
	goto L_080AE6B8
}

// 0x080AE6D8
func stub_080AE6D8(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(2)
	{
		t := c.R[3]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}
