// Code generated by cmd/recomp from pokeemerald_modern.elf. DO NOT EDIT.
package mail

import g "dbut.dev/sapphire/gba"

var regs0 = []reg{
	{0x08125944, 220, ReadMail},
	{0x08125A20, 864, MailReadBuildGraphics},
	{0x08125D80, 36, CB2_InitMailRead},
	{0x08125DA4, 216, BufferMailText},
	{0x08125E7C, 320, PrintMailText},
	{0x08125FBC, 18, VBlankCB_MailRead},
	{0x08125FD0, 52, CB2_MailRead},
	{0x08126004, 36, CB2_WaitForPaletteExitOnKeyPress},
	{0x08126028, 64, CB2_ExitOnKeyPress},
	{0x08126068, 148, CB2_ExitMailReadFreeVars},
	{0x081260FC, 4, stub_081260FC},
}

// 0x08125944
func ReadMail(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(76)
	c.Thumb(0xB5F0)
	c.Thumb(0x46C6)
	c.Thumb(0xB500)
	c.Thumb(0x0005)
	c.Thumb(0xB081)
	c.R[15] = 0x08125952
	c.Thumb(0x482A)
	c.Thumb(0x0614)
	c.Thumb(0x4688)
	c.R[14] = 0x08125959
	c.NCallT(0x081292A4)
	if c.U != 0 {
		if c.U != 0x08125959 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2202)
	c.R[15] = 0x0812595E
	c.Thumb(0x4B28)
	c.Thumb(0x54C2)
	c.R[15] = 0x08125962
	c.Thumb(0x4B28)
	c.Thumb(0x3A01)
	c.Thumb(0x54C2)
	c.Thumb(0x2288)
	c.R[15] = 0x0812596A
	c.Thumb(0x4B27)
	c.Thumb(0x0092)
	c.Thumb(0x5083)
	c.R[15] = 0x08125970
	c.Thumb(0x4E26)
	c.R[15] = 0x08125972
	c.Thumb(0x4B27)
	c.Thumb(0x3204)
	c.Thumb(0x5083)
	c.Thumb(0x6030)
	c.Thumb(0x8C2B)
	c.Thumb(0x3B79)
	c.Thumb(0x041A)
	c.Thumb(0x0E24)
	c.Thumb(0x0C12)
	c.Thumb(0x2A0B)
	if c.Cond(0x8) {
		goto L_081259EA
	}
	c.Thumb(0x061B)
	c.Thumb(0x0E1A)
	c.Thumb(0x0DDB)
	c.R[15] = 0x0812598E
	c.Thumb(0x4921)
	c.Thumb(0x189B)
	c.Thumb(0x009B)
	c.Thumb(0x185B)
L_08125992:
	c.NT(48)
	c.R[15] = 0x08125996
	c.Thumb(0x4F20)
	c.Thumb(0x55C2)
	c.Thumb(0x228A)
	c.Thumb(0x0092)
	c.Thumb(0x5083)
	c.Thumb(0x4669)
	c.Thumb(0x8BE8)
	c.R[14] = 0x081259A5
	c.NCallT(0x08125780)
	if c.U != 0 {
		if c.U != 0x081259A5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x21CD)
	c.Thumb(0x3801)
	c.Thumb(0x0400)
	c.Thumb(0x2200)
	c.Thumb(0x6833)
	c.Thumb(0x0049)
	c.Thumb(0x0C00)
	c.Thumb(0x4288)
	if c.Cond(0x8) {
		goto L_081259C4
	}
	c.Thumb(0x5DDA)
	c.Thumb(0x2A06)
	if c.Cond(0x0) {
		goto L_081259F2
	}
	c.Thumb(0x3A09)
	c.Thumb(0x4251)
	c.Thumb(0x414A)
	c.Thumb(0x0052)
L_081259C4:
	c.NT(36)
	c.R[15] = 0x081259C8
	c.Thumb(0x4914)
	c.Thumb(0x545A)
	c.Thumb(0x2285)
	c.Thumb(0x4641)
	c.Thumb(0x0092)
	c.Thumb(0x509D)
	c.Thumb(0x3A08)
	c.Thumb(0x5099)
	c.Thumb(0x320C)
	c.Thumb(0x549C)
	c.R[15] = 0x081259DC
	c.Thumb(0x4810)
	c.R[14] = 0x081259DF
	c.NCallT(0x080005B8)
	if c.U != 0 {
		if c.U != 0x081259DF {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB001)
	c.Thumb(0xBC80)
	c.Thumb(0x46B8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081259EA:
	c.NT(8)
	c.Thumb(0x2200)
	c.Thumb(0x2400)
	c.R[15] = 0x081259F2
	c.Thumb(0x4B08)
	goto L_08125992
L_081259F2:
	c.NT(4)
	c.Thumb(0x2201)
	goto L_081259C4
}

// 0x08125A20
func MailReadBuildGraphics(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	var jt uint32
	c.NT(24)
	c.Thumb(0x2387)
	c.Thumb(0xB570)
	c.R[15] = 0x08125A28
	c.Thumb(0x4CC4)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	c.Thumb(0xB083)
	c.Thumb(0x2B12)
	if c.Cond(0x8) {
		goto L_08125A86
	}
	c.R[15] = 0x08125A34
	c.Thumb(0x49C2)
	c.Thumb(0x009A)
	c.Thumb(0x588A)
	jt = c.R[2] &^ 1
	goto Ldispatch
L_08125A38:
	c.NT(26)
	c.Thumb(0x2385)
	c.R[15] = 0x08125A3E
	c.Thumb(0x4DC1)
	c.Thumb(0x682A)
	c.Thumb(0x009B)
	c.Thumb(0x58D3)
	c.Thumb(0x8BD8)
	c.R[14] = 0x08125A49
	c.NCallT(0x08163DCC)
	if c.U != 0 {
		if c.U != 0x08125A49 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x682A)
	c.R[15] = 0x08125A4E
	c.Thumb(0x4BBE)
	c.Thumb(0x5CD3)
	c.Thumb(0x2B01)
	if c.Cond(0x1) {
		goto L_08125A54
	}
	goto L_08125D20
L_08125A54:
	c.NT(22)
	c.Thumb(0x2B02)
	if c.Cond(0x1) {
		goto L_08125AB2
	}
	c.Thumb(0x0006)
	c.R[14] = 0x08125A5F
	c.NCallT(0x08163F28)
	if c.U != 0 {
		if c.U != 0x08125A5F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x2228)
	c.R[15] = 0x08125A66
	c.Thumb(0x49B9)
	c.Thumb(0x682D)
	c.Thumb(0x9301)
	c.Thumb(0x9300)
	c.Thumb(0x3380)
L_08125A6C:
	c.NT(16)
	c.Thumb(0x0030)
	c.R[14] = 0x08125A73
	c.NCallT(0x08163CB4)
	if c.U != 0 {
		if c.U != 0x08125A73 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x009B)
	c.Thumb(0x54E8)
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
L_08125A7E:
	c.NT(8)
	c.Thumb(0x2287)
	c.Thumb(0x3301)
	c.Thumb(0x00D2)
	c.Thumb(0x54A3)
L_08125A86:
	c.NT(2)
	c.Thumb(0x2000)
L_08125A88:
	c.NT(8)
	c.Thumb(0xB003)
	c.Thumb(0xBC70)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08125A90:
	c.NT(24)
	c.R[15] = 0x08125A94
	c.Thumb(0x48AE)
	c.R[14] = 0x08125A97
	c.NCallT(0x08000760)
	if c.U != 0 {
		if c.U != 0x08125A97 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2380)
	c.R[15] = 0x08125A9C
	c.Thumb(0x4AAD)
	c.Thumb(0x7A11)
	c.Thumb(0x425B)
	c.Thumb(0x430B)
	c.Thumb(0x7213)
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125AAA:
	c.NT(6)
	c.R[14] = 0x08125AAF
	c.NCallT(0x081418CC)
	if c.U != 0 {
		if c.U != 0x08125AAF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2801)
	if c.Cond(0x0) {
		goto L_08125A86
	}
L_08125AB2:
	c.NT(8)
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125ABA:
	c.NT(26)
	c.R[15] = 0x08125ABE
	c.Thumb(0x4AA1)
	c.Thumb(0x6811)
	c.Thumb(0x2286)
	c.Thumb(0x0092)
	c.Thumb(0x5C8A)
	c.Thumb(0x2A00)
	if c.Cond(0x0) {
		goto L_08125A7E
	}
	c.R[14] = 0x08125ACD
	PrintMailText(c)
	if c.U != 0 {
		if c.U != 0x08125ACD {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125AD1
	c.NCallT(0x081B55F4)
	if c.U != 0 {
		if c.U != 0x08125AD1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125AD8:
	c.NT(24)
	c.R[15] = 0x08125ADC
	c.Thumb(0x4A99)
	c.Thumb(0x6811)
	c.Thumb(0x2286)
	c.Thumb(0x0092)
	c.Thumb(0x5C8A)
	c.Thumb(0x2A00)
	if c.Cond(0x0) {
		goto L_08125A7E
	}
	c.R[14] = 0x08125AEB
	BufferMailText(c)
	if c.U != 0 {
		if c.U != 0x08125AEB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125AF2:
	c.NT(74)
	c.R[14] = 0x08125AF7
	c.NCallT(0x081B53DC)
	if c.U != 0 {
		if c.U != 0x08125AF7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2220)
	c.Thumb(0x21F0)
	c.R[14] = 0x08125AFF
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08125AFF {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x08125B02
	c.Thumb(0x4B90)
	c.Thumb(0x681A)
	c.R[15] = 0x08125B06
	c.Thumb(0x4B94)
	c.Thumb(0x5CD2)
	c.Thumb(0x0093)
	c.Thumb(0x189B)
	c.Thumb(0x009B)
	c.Thumb(0x0019)
	c.R[15] = 0x08125B12
	c.Thumb(0x4A92)
	c.Thumb(0x3110)
	c.Thumb(0x5850)
	c.Thumb(0x21FA)
	c.R[15] = 0x08125B1A
	c.Thumb(0x4D91)
	c.R[15] = 0x08125B1C
	c.Thumb(0x4E91)
	c.Thumb(0x0049)
	c.Thumb(0x5068)
	c.Thumb(0x5070)
	c.Thumb(0x58D0)
	c.Thumb(0x2100)
	c.Thumb(0x2220)
	c.R[14] = 0x08125B2B
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08125B2B {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x08125B2E
	c.Thumb(0x4B8E)
	c.Thumb(0x681B)
	c.Thumb(0x7A1B)
	c.R[15] = 0x08125B34
	c.Thumb(0x4A8D)
	c.Thumb(0x009B)
	c.Thumb(0x58D3)
	c.Thumb(0x616B)
	c.Thumb(0x6173)
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125B42:
	c.NT(20)
	c.Thumb(0x2000)
	c.R[14] = 0x08125B49
	c.NCallT(0x080A8258)
	if c.U != 0 {
		if c.U != 0x08125B49 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2001)
	c.R[14] = 0x08125B4F
	c.NCallT(0x080A8258)
	if c.U != 0 {
		if c.U != 0x08125B4F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2002)
	c.R[14] = 0x08125B55
	c.NCallT(0x080A8258)
	if c.U != 0 {
		if c.U != 0x08125B55 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125B5C:
	c.NT(68)
	c.Thumb(0x2514)
	c.Thumb(0x261E)
	c.Thumb(0x2300)
	c.Thumb(0x2200)
	c.Thumb(0x2100)
	c.Thumb(0x2000)
	c.Thumb(0x9501)
	c.Thumb(0x9600)
	c.R[14] = 0x08125B71
	c.NCallT(0x080A84BC)
	if c.U != 0 {
		if c.U != 0x08125B71 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x2200)
	c.Thumb(0x2101)
	c.Thumb(0x2002)
	c.Thumb(0x9501)
	c.Thumb(0x9600)
	c.R[14] = 0x08125B81
	c.NCallT(0x080A84BC)
	if c.U != 0 {
		if c.U != 0x08125B81 {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x08125B84
	c.Thumb(0x4A6F)
	c.Thumb(0x6811)
	c.R[15] = 0x08125B88
	c.Thumb(0x4A73)
	c.Thumb(0x5C89)
	c.Thumb(0x008A)
	c.R[15] = 0x08125B8E
	c.Thumb(0x4B73)
	c.Thumb(0x1852)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x6899)
	c.Thumb(0x2200)
	c.Thumb(0x2300)
	c.Thumb(0x2001)
	c.R[14] = 0x08125B9F
	c.NCallT(0x080A8208)
	if c.U != 0 {
		if c.U != 0x08125B9F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125BA6:
	c.NT(8)
	c.R[14] = 0x08125BAB
	c.NCallT(0x081312D4)
	if c.U != 0 {
		if c.U != 0x08125BAB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_08125AB2
	}
	goto L_08125A86
L_08125BB0:
	c.NT(38)
	c.R[15] = 0x08125BB4
	c.Thumb(0x4A63)
	c.Thumb(0x6811)
	c.R[15] = 0x08125BB8
	c.Thumb(0x4A67)
	c.Thumb(0x5C89)
	c.Thumb(0x008A)
	c.R[15] = 0x08125BBE
	c.Thumb(0x4B67)
	c.Thumb(0x1852)
	c.Thumb(0x0092)
	c.Thumb(0x189B)
	c.Thumb(0x6859)
	c.Thumb(0x2300)
	c.Thumb(0x2200)
	c.Thumb(0x9300)
	c.Thumb(0x2001)
	c.R[14] = 0x08125BD1
	c.NCallT(0x08131314)
	if c.U != 0 {
		if c.U != 0x08125BD1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125BD8:
	c.NT(14)
	c.R[15] = 0x08125BDC
	c.Thumb(0x4864)
	c.R[14] = 0x08125BDF
	c.NCallT(0x081DF61C)
	if c.U != 0 {
		if c.U != 0x08125BDF {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125BE3
	c.NCallT(0x081B5444)
	if c.U != 0 {
		if c.U != 0x08125BE3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125BEA:
	c.NT(44)
	c.Thumb(0x2000)
	c.R[14] = 0x08125BF1
	c.NCallT(0x080A7760)
	if c.U != 0 {
		if c.U != 0x08125BF1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2203)
	c.Thumb(0x2000)
	c.R[15] = 0x08125BF8
	c.Thumb(0x495E)
	c.R[14] = 0x08125BFB
	c.NCallT(0x080A77A8)
	if c.U != 0 {
		if c.U != 0x08125BFB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x238B)
	c.R[15] = 0x08125C00
	c.Thumb(0x4D50)
	c.Thumb(0x6829)
	c.Thumb(0x009B)
	c.Thumb(0x18C9)
	c.Thumb(0x2001)
	c.R[14] = 0x08125C0B
	c.NCallT(0x080A81C0)
	if c.U != 0 {
		if c.U != 0x08125C0B {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x08125C0E
	c.Thumb(0x4B5A)
	c.Thumb(0x6829)
	c.Thumb(0x2002)
	c.Thumb(0x18C9)
	c.R[14] = 0x08125C17
	c.NCallT(0x080A81C0)
	if c.U != 0 {
		if c.U != 0x08125C17 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125C1E:
	c.NT(72)
	c.R[14] = 0x08125C23
	c.NCallT(0x081B1CD4)
	if c.U != 0 {
		if c.U != 0x08125C23 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125C27
	c.NCallT(0x081312B4)
	if c.U != 0 {
		if c.U != 0x08125C27 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2010)
	c.R[14] = 0x08125C2F
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C2F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2012)
	c.R[14] = 0x08125C37
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C37 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2014)
	c.R[14] = 0x08125C3F
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C3F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2016)
	c.R[14] = 0x08125C47
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C47 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x201A)
	c.R[14] = 0x08125C4F
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C4F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2018)
	c.R[14] = 0x08125C57
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C57 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x201C)
	c.R[14] = 0x08125C5F
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C5F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x201E)
	c.R[14] = 0x08125C67
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C67 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2050)
	c.R[14] = 0x08125C6F
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C6F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2052)
	c.R[14] = 0x08125C77
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125C77 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125C7E:
	c.NT(10)
	c.R[14] = 0x08125C83
	c.NCallT(0x081AFB50)
	if c.U != 0 {
		if c.U != 0x08125C83 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125C8A:
	c.NT(10)
	c.R[14] = 0x08125C8F
	c.NCallT(0x081B4BE8)
	if c.U != 0 {
		if c.U != 0x08125C8F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125C96:
	c.NT(10)
	c.R[14] = 0x08125C9B
	c.NCallT(0x08142DBC)
	if c.U != 0 {
		if c.U != 0x08125C9B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125CA2:
	c.NT(28)
	c.Thumb(0x2300)
	c.Thumb(0x466A)
	c.Thumb(0x21E0)
	c.Thumb(0x8153)
	c.Thumb(0x330A)
	c.Thumb(0x446B)
	c.Thumb(0x0018)
	c.R[15] = 0x08125CB4
	c.Thumb(0x4A31)
	c.Thumb(0x04C9)
	c.R[14] = 0x08125CB9
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x08125CB9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125CC0:
	c.NT(20)
	c.Thumb(0x2000)
	c.R[14] = 0x08125CC7
	c.NCallT(0x08000760)
	if c.U != 0 {
		if c.U != 0x08125CC7 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125CCB
	c.NCallT(0x0819F210)
	if c.U != 0 {
		if c.U != 0x08125CCB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2000)
	c.R[14] = 0x08125CD3
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125CD3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x00DB)
	c.Thumb(0x5CE3)
	goto L_08125A7E
L_08125CDA:
	c.NT(60)
	c.Thumb(0x2182)
	c.Thumb(0x2000)
	c.Thumb(0x0149)
	c.R[14] = 0x08125CE5
	c.NCallT(0x0810BD34)
	if c.U != 0 {
		if c.U != 0x08125CE5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2000)
	c.R[14] = 0x08125CEB
	c.NCallT(0x080A7B54)
	if c.U != 0 {
		if c.U != 0x08125CEB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2001)
	c.R[14] = 0x08125CF1
	c.NCallT(0x080A7B54)
	if c.U != 0 {
		if c.U != 0x08125CF1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2002)
	c.R[14] = 0x08125CF7
	c.NCallT(0x080A7B54)
	if c.U != 0 {
		if c.U != 0x08125CF7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x2001)
	c.Thumb(0x2210)
	c.Thumb(0x2100)
	c.Thumb(0x9300)
	c.Thumb(0x4240)
	c.R[14] = 0x08125D07
	c.NCallT(0x08142E80)
	if c.U != 0 {
		if c.U != 0x08125D07 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x237F)
	c.R[15] = 0x08125D0C
	c.Thumb(0x4A11)
	c.Thumb(0x7A11)
	c.Thumb(0x400B)
	c.Thumb(0x7213)
	c.Thumb(0x2284)
	c.R[15] = 0x08125D16
	c.Thumb(0x4B0B)
	c.Thumb(0x6819)
	c.R[15] = 0x08125D1A
	c.Thumb(0x4B19)
	c.Thumb(0x0092)
	c.Thumb(0x2001)
	c.Thumb(0x508B)
	goto L_08125A88
L_08125D20:
	c.NT(20)
	c.Thumb(0x0006)
	c.R[14] = 0x08125D27
	c.NCallT(0x08163F28)
	if c.U != 0 {
		if c.U != 0x08125D27 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x682D)
	c.Thumb(0x2260)
	c.Thumb(0x9301)
	c.Thumb(0x9300)
	c.R[15] = 0x08125D34
	c.Thumb(0x4905)
	c.Thumb(0x3380)
	goto L_08125A6C
Ldispatch:
	switch jt {
	case 0x08125A38:
		goto L_08125A38
	case 0x08125A90:
		goto L_08125A90
	case 0x08125AAA:
		goto L_08125AAA
	case 0x08125ABA:
		goto L_08125ABA
	case 0x08125AD8:
		goto L_08125AD8
	case 0x08125AF2:
		goto L_08125AF2
	case 0x08125B42:
		goto L_08125B42
	case 0x08125B5C:
		goto L_08125B5C
	case 0x08125BA6:
		goto L_08125BA6
	case 0x08125BB0:
		goto L_08125BB0
	case 0x08125BD8:
		goto L_08125BD8
	case 0x08125BEA:
		goto L_08125BEA
	case 0x08125C1E:
		goto L_08125C1E
	case 0x08125C7E:
		goto L_08125C7E
	case 0x08125C8A:
		goto L_08125C8A
	case 0x08125C96:
		goto L_08125C96
	case 0x08125CA2:
		goto L_08125CA2
	case 0x08125CC0:
		goto L_08125CC0
	case 0x08125CDA:
		goto L_08125CDA
	default:
		t := jt | 1
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallT(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08125D80
func CB2_InitMailRead(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(4)
	c.Thumb(0xB500)
	goto L_08125D8C
L_08125D84:
	c.NT(6)
	c.R[14] = 0x08125D89
	c.NCallT(0x0812C94C)
	if c.U != 0 {
		if c.U != 0x08125D89 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2801)
	if c.Cond(0x0) {
		goto L_08125D9A
	}
L_08125D8C:
	c.NT(10)
	c.R[14] = 0x08125D91
	MailReadBuildGraphics(c)
	if c.U != 0 {
		if c.U != 0x08125D91 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2801)
	if c.Cond(0x1) {
		goto L_08125D84
	}
	c.R[15] = 0x08125D98
	c.Thumb(0x4802)
	c.R[14] = 0x08125D9B
	c.NCallT(0x080005B8)
	if c.U != 0 {
		if c.U != 0x08125D9B {
			return
		}
		c.U = 0
	}
L_08125D9A:
	c.NT(4)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08125DA4
func BufferMailText(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(38)
	c.Thumb(0x238A)
	c.Thumb(0xB5F0)
	c.Thumb(0x46CE)
	c.Thumb(0x4647)
	c.R[15] = 0x08125DB0
	c.Thumb(0x4D2F)
	c.Thumb(0x6828)
	c.Thumb(0x009B)
	c.Thumb(0x4699)
	c.Thumb(0x58C3)
	c.Thumb(0x781A)
	c.Thumb(0xB580)
	c.Thumb(0x2A00)
	if c.Cond(0x0) {
		goto L_08125E04
	}
	c.Thumb(0x689A)
	c.Thumb(0x2385)
	c.Thumb(0x009B)
	c.Thumb(0x2400)
	c.Thumb(0x2700)
	c.Thumb(0x4698)
L_08125DCA:
	c.NT(56)
	c.Thumb(0x4641)
	c.Thumb(0x00A6)
	c.Thumb(0x5841)
	c.Thumb(0x5D92)
	c.Thumb(0x007B)
	c.Thumb(0x18C9)
	c.Thumb(0x0792)
	c.Thumb(0x01A3)
	c.Thumb(0x0F92)
	c.Thumb(0x18C0)
	c.Thumb(0x2301)
	c.R[14] = 0x08125DE5
	c.NCallT(0x080D4058)
	if c.U != 0 {
		if c.U != 0x08125DE5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x464B)
	c.Thumb(0x6828)
	c.Thumb(0x58C1)
	c.Thumb(0x688A)
	c.Thumb(0x5D93)
	c.Thumb(0x079B)
	c.Thumb(0x0F9B)
	c.Thumb(0x18FB)
	c.Thumb(0x061B)
	c.Thumb(0x3401)
	c.Thumb(0x7809)
	c.Thumb(0x0E1F)
	c.Thumb(0x0423)
	c.Thumb(0x0C1B)
	c.Thumb(0x4299)
	if c.Cond(0x8) {
		goto L_08125DCA
	}
L_08125E04:
	c.NT(58)
	c.Thumb(0x2385)
	c.Thumb(0x009B)
	c.Thumb(0x58C1)
	c.Thumb(0x3B14)
	c.Thumb(0x18C0)
	c.Thumb(0x3112)
	c.R[14] = 0x08125E15
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x08125E15 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x682B)
	c.R[15] = 0x08125E1A
	c.Thumb(0x4A16)
	c.Thumb(0x5C9A)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_08125E50
	}
	c.R[15] = 0x08125E22
	c.Thumb(0x4915)
	c.R[14] = 0x08125E25
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x08125E25 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x238A)
	c.Thumb(0x6828)
	c.Thumb(0x009B)
	c.Thumb(0x58C3)
	c.Thumb(0x789C)
	c.Thumb(0x2380)
	c.Thumb(0x009B)
	c.Thumb(0x18C0)
	c.R[14] = 0x08125E39
	c.NCallT(0x081B42DC)
	if c.U != 0 {
		if c.U != 0x08125E39 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x380C)
	c.Thumb(0x682A)
	c.R[15] = 0x08125E40
	c.Thumb(0x4B0E)
	c.Thumb(0x00C0)
	c.Thumb(0x1A24)
	c.Thumb(0x54D4)
L_08125E44:
	c.NT(12)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08125E50:
	c.NT(24)
	c.Thumb(0x2280)
	c.Thumb(0x0092)
	c.Thumb(0x1898)
	c.R[14] = 0x08125E5B
	c.NCallT(0x0810FE44)
	if c.U != 0 {
		if c.U != 0x08125E5B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x228A)
	c.Thumb(0x682B)
	c.Thumb(0x0092)
	c.Thumb(0x589A)
	c.Thumb(0x7891)
	c.R[15] = 0x08125E68
	c.Thumb(0x4A04)
	c.Thumb(0x5499)
	goto L_08125E44
}

// 0x08125E7C
func PrintMailText(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(54)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x464E)
	c.Thumb(0x4645)
	c.Thumb(0xB5E0)
	c.Thumb(0x2000)
	c.Thumb(0xB08B)
	c.R[14] = 0x08125E91
	c.NCallT(0x081DFB8C)
	if c.U != 0 {
		if c.U != 0x08125E91 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2001)
	c.R[14] = 0x08125E97
	c.NCallT(0x081DFB8C)
	if c.U != 0 {
		if c.U != 0x08125E97 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2000)
	c.R[14] = 0x08125E9F
	c.NCallT(0x081DFFD4)
	if c.U != 0 {
		if c.U != 0x08125E9F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2100)
	c.Thumb(0x2001)
	c.R[14] = 0x08125EA7
	c.NCallT(0x081DFFD4)
	if c.U != 0 {
		if c.U != 0x08125EA7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x238A)
	c.R[15] = 0x08125EAC
	c.Thumb(0x4C40)
	c.Thumb(0x6821)
	c.Thumb(0x009B)
	c.Thumb(0x58CA)
	c.Thumb(0x469B)
	c.Thumb(0x7813)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_08125EBA
	}
	goto L_08125FA4
L_08125EBA:
	c.NT(10)
	c.R[15] = 0x08125EBE
	c.Thumb(0x4B3D)
	c.Thumb(0x2700)
	c.Thumb(0x2500)
	c.Thumb(0x4698)
	goto L_08125ED6
L_08125EC4:
	c.NT(18)
	c.Thumb(0x465B)
	c.Thumb(0x6821)
	c.Thumb(0x58CA)
	c.Thumb(0x3701)
	c.Thumb(0x7810)
	c.Thumb(0x043B)
	c.Thumb(0x0C1B)
	c.Thumb(0x4298)
	if c.Cond(0x9) {
		goto L_08125F36
	}
L_08125ED6:
	c.NT(94)
	c.Thumb(0x01B8)
	c.Thumb(0x5C43)
	c.Thumb(0x3B01)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x2BFD)
	if c.Cond(0x8) {
		goto L_08125EC4
	}
	c.Thumb(0x78D3)
	c.Thumb(0x469C)
	c.Thumb(0x44AC)
	c.Thumb(0x4663)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x469C)
	c.Thumb(0x6893)
	c.Thumb(0x00BE)
	c.Thumb(0x5D9B)
	c.Thumb(0x7912)
	c.Thumb(0x089B)
	c.Thumb(0x18D2)
	c.Thumb(0x2300)
	c.Thumb(0x9301)
	c.Thumb(0x4643)
	c.Thumb(0x1808)
	c.Thumb(0x0612)
	c.Thumb(0x2101)
	c.Thumb(0x9002)
	c.Thumb(0x9300)
	c.Thumb(0x2000)
	c.Thumb(0x4663)
	c.Thumb(0x0E12)
	c.R[14] = 0x08125F19
	c.NCallT(0x08131744)
	if c.U != 0 {
		if c.U != 0x08125F19 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x465B)
	c.Thumb(0x6821)
	c.Thumb(0x58CA)
	c.Thumb(0x6893)
	c.Thumb(0x199B)
	c.Thumb(0x785B)
	c.Thumb(0x18EB)
	c.Thumb(0x061B)
	c.Thumb(0x3701)
	c.Thumb(0x7810)
	c.Thumb(0x0E1D)
	c.Thumb(0x043B)
	c.Thumb(0x0C1B)
	c.Thumb(0x4298)
	if c.Cond(0x8) {
		goto L_08125ED6
	}
L_08125F36:
	c.NT(98)
	c.Thumb(0xAD03)
	c.Thumb(0x0028)
	c.R[15] = 0x08125F3E
	c.Thumb(0x491E)
	c.R[14] = 0x08125F41
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x08125F41 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2380)
	c.Thumb(0x6821)
	c.Thumb(0x009B)
	c.Thumb(0x18C9)
	c.R[14] = 0x08125F4D
	c.NCallT(0x081B4254)
	if c.U != 0 {
		if c.U != 0x08125F4D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6822)
	c.R[15] = 0x08125F52
	c.Thumb(0x4B1A)
	c.Thumb(0x0029)
	c.Thumb(0x5CD2)
	c.Thumb(0x2001)
	c.R[14] = 0x08125F5B
	c.NCallT(0x0810FC2C)
	if c.U != 0 {
		if c.U != 0x08125F5B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x238A)
	c.Thumb(0x2100)
	c.Thumb(0x6822)
	c.Thumb(0x009B)
	c.Thumb(0x58D3)
	c.Thumb(0x22FF)
	c.Thumb(0x785B)
	c.Thumb(0x9101)
	c.Thumb(0x4641)
	c.Thumb(0x3358)
	c.Thumb(0x3068)
	c.Thumb(0x061B)
	c.Thumb(0x4002)
	c.Thumb(0x0E1B)
	c.Thumb(0x9100)
	c.Thumb(0x2000)
	c.Thumb(0x2101)
	c.Thumb(0x9502)
	c.R[14] = 0x08125F83
	c.NCallT(0x08131744)
	if c.U != 0 {
		if c.U != 0x08125F83 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2103)
	c.Thumb(0x2000)
	c.R[14] = 0x08125F8B
	c.NCallT(0x081DFA9C)
	if c.U != 0 {
		if c.U != 0x08125F8B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2103)
	c.Thumb(0x2001)
	c.R[14] = 0x08125F93
	c.NCallT(0x081DFA9C)
	if c.U != 0 {
		if c.U != 0x08125F93 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB00B)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08125FA4:
	c.NT(6)
	c.R[15] = 0x08125FA8
	c.Thumb(0x4B02)
	c.Thumb(0x4698)
	goto L_08125F36
}

// 0x08125FBC
func VBlankCB_MailRead(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0xB500)
	c.R[14] = 0x08125FC3
	c.NCallT(0x081B05A4)
	if c.U != 0 {
		if c.U != 0x08125FC3 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125FC7
	c.NCallT(0x081B0830)
	if c.U != 0 {
		if c.U != 0x08125FC7 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125FCB
	c.NCallT(0x08142CDC)
	if c.U != 0 {
		if c.U != 0x08125FCB {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08125FD0
func CB2_MailRead(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.Thumb(0xB510)
	c.R[15] = 0x08125FD6
	c.Thumb(0x4C0A)
	c.R[15] = 0x08125FD8
	c.Thumb(0x4A0A)
	c.Thumb(0x6823)
	c.Thumb(0x5C9A)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_08125FEE
	}
L_08125FDE:
	c.NT(14)
	c.Thumb(0x2284)
	c.Thumb(0x0092)
	c.Thumb(0x589B)
	c.R[14] = 0x08125FE9
	stub_081260FC(c)
	if c.U != 0 {
		if c.U != 0x08125FE9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08125FEE:
	c.NT(8)
	c.R[14] = 0x08125FF3
	c.NCallT(0x081AFBF4)
	if c.U != 0 {
		if c.U != 0x08125FF3 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x08125FF7
	c.NCallT(0x081AFCA0)
	if c.U != 0 {
		if c.U != 0x08125FF7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6823)
	goto L_08125FDE
}

// 0x08126004
func CB2_WaitForPaletteExitOnKeyPress(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(20)
	c.Thumb(0xB500)
	c.R[14] = 0x0812600B
	c.NCallT(0x08142D38)
	if c.U != 0 {
		if c.U != 0x0812600B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2800)
	if c.Cond(0x1) {
		goto L_0812601A
	}
	c.Thumb(0x2284)
	c.R[15] = 0x08126014
	c.Thumb(0x4B03)
	c.Thumb(0x6819)
	c.R[15] = 0x08126018
	c.Thumb(0x4B03)
	c.Thumb(0x0092)
	c.Thumb(0x508B)
L_0812601A:
	c.NT(4)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08126028
func CB2_ExitOnKeyPress(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0xB500)
	c.R[15] = 0x0812602E
	c.Thumb(0x4B0C)
	c.Thumb(0x8DDB)
	c.Thumb(0xB081)
	c.Thumb(0x079B)
	if c.Cond(0x1) {
		goto L_0812603A
	}
L_08126034:
	c.NT(6)
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0812603A:
	c.NT(30)
	c.Thumb(0x2300)
	c.Thumb(0x2001)
	c.Thumb(0x2200)
	c.Thumb(0x2100)
	c.Thumb(0x9300)
	c.Thumb(0x4240)
	c.Thumb(0x3310)
	c.R[14] = 0x0812604D
	c.NCallT(0x08142E80)
	if c.U != 0 {
		if c.U != 0x0812604D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2284)
	c.R[15] = 0x08126052
	c.Thumb(0x4B04)
	c.Thumb(0x6819)
	c.R[15] = 0x08126056
	c.Thumb(0x4B04)
	c.Thumb(0x0092)
	c.Thumb(0x508B)
	goto L_08126034
}

// 0x08126068
func CB2_ExitMailReadFreeVars(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(8)
	c.Thumb(0xB510)
	c.R[14] = 0x0812606F
	c.NCallT(0x08142D38)
	if c.U != 0 {
		if c.U != 0x0812606F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_08126078
	}
L_08126072:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08126078:
	c.NT(24)
	c.Thumb(0x2383)
	c.R[15] = 0x0812607E
	c.Thumb(0x4C1C)
	c.Thumb(0x6822)
	c.Thumb(0x009B)
	c.Thumb(0x58D0)
	c.R[14] = 0x08126087
	c.NCallT(0x080005B8)
	if c.U != 0 {
		if c.U != 0x08126087 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6820)
	c.R[15] = 0x0812608C
	c.Thumb(0x4B19)
	c.Thumb(0x5CC3)
	c.Thumb(0x3B01)
	c.Thumb(0x2B01)
	if c.Cond(0x9) {
		goto L_081260C0
	}
L_08126092:
	c.NT(32)
	c.Thumb(0x2100)
	c.R[15] = 0x08126098
	c.Thumb(0x4A17)
	c.R[14] = 0x0812609B
	c.NCallT(0x082E66B0)
	if c.U != 0 {
		if c.U != 0x0812609B {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0812609F
	c.NCallT(0x08142DBC)
	if c.U != 0 {
		if c.U != 0x0812609F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2000)
	c.R[14] = 0x081260A5
	c.NCallT(0x080A81D8)
	if c.U != 0 {
		if c.U != 0x081260A5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2001)
	c.R[14] = 0x081260AB
	c.NCallT(0x080A81D8)
	if c.U != 0 {
		if c.U != 0x081260AB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2000)
	c.R[14] = 0x081260B1
	c.NCallT(0x080A7760)
	if c.U != 0 {
		if c.U != 0x081260B1 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x081260B5
	c.NCallT(0x081DFA48)
	if c.U != 0 {
		if c.U != 0x081260B5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6820)
	c.R[14] = 0x081260BB
	c.NCallT(0x081292E8)
	if c.U != 0 {
		if c.U != 0x081260BB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2300)
	c.Thumb(0x6023)
	goto L_08126072
L_081260C0:
	c.NT(36)
	c.Thumb(0x2385)
	c.Thumb(0x009B)
	c.Thumb(0x58C3)
	c.Thumb(0x8BD8)
	c.R[14] = 0x081260CD
	c.NCallT(0x08163DCC)
	if c.U != 0 {
		if c.U != 0x081260CD {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x081260D1
	c.NCallT(0x08163FAC)
	if c.U != 0 {
		if c.U != 0x081260D1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2387)
	c.Thumb(0x6822)
	c.Thumb(0x009B)
	c.Thumb(0x5CD3)
	c.Thumb(0x0118)
	c.Thumb(0x18C0)
	c.R[15] = 0x081260E0
	c.Thumb(0x4B06)
	c.Thumb(0x0080)
	c.Thumb(0x18C0)
	c.R[14] = 0x081260E7
	c.NCallT(0x08163E84)
	if c.U != 0 {
		if c.U != 0x081260E7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6820)
	goto L_08126092
}

// 0x081260FC
func stub_081260FC(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(2)
	{
		t := c.R[3]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}
