// Code generated by cmd/recomp from pokeemerald_modern.elf. DO NOT EDIT.
package fieldmap

import g "dbut.dev/sapphire/gba"

var regs0 = []reg{
	{0x081025D0, 14, GetMapHeaderFromConnection},
	{0x081025E0, 32, InitMap},
	{0x08102600, 52, InitMapFromSavedGame},
	{0x08102634, 52, InitBattlePyramidMap},
	{0x08102668, 48, InitTrainerHillMap},
	{0x08102698, 168, InitMapLayoutData},
	{0x08102740, 96, InitBackupMapLayoutData},
	{0x081027A0, 160, InitBackupMapLayoutConnections},
	{0x08102840, 104, FillConnection},
	{0x081028A8, 148, FillSouthConnection},
	{0x0810293C, 140, FillNorthConnection},
	{0x081029C8, 104, FillWestConnection},
	{0x08102A30, 92, FillEastConnection},
	{0x08102A8C, 108, MapGridGetElevationAt},
	{0x08102AF8, 112, MapGridGetCollisionAt},
	{0x08102B68, 144, MapGridGetMetatileIdAt},
	{0x08102BF8, 56, MapGridGetMetatileBehaviorAt},
	{0x08102C30, 56, MapGridGetMetatileLayerTypeAt},
	{0x08102C68, 84, MapGridSetMetatileIdAt},
	{0x08102CBC, 72, MapGridSetMetatileEntryAt},
	{0x08102D04, 64, GetMetatileAttributesById},
	{0x08102D44, 76, SaveMapView},
	{0x08102D90, 36, SavedMapViewIsEmpty},
	{0x08102DB4, 40, ClearSavedMapView},
	{0x08102DDC, 468, LoadSavedMapView},
	{0x08102FB0, 228, MoveMapViewToBackup},
	{0x08103094, 200, GetMapBorderIdAt},
	{0x0810315C, 36, GetPostCameraMoveMapBorderId},
	{0x08103180, 60, CanCameraMoveInDirection},
	{0x081031BC, 120, SetPositionFromConnection},
	{0x08103234, 220, CameraMove},
	{0x08103310, 92, GetIncomingConnection},
	{0x0810336C, 160, IsPosInIncomingConnectingMap},
	{0x0810340C, 48, IsCoordInIncomingConnectingMap},
	{0x0810343C, 18, IsCoordInConnectingMap},
	{0x08103450, 102, IsPosInConnectingMap},
	{0x081034B8, 228, GetMapConnectionAtPos},
	{0x0810359C, 20, SetCameraFocusCoords},
	{0x081035B0, 24, GetCameraFocusCoords},
	{0x081035C8, 16, SetCameraCoords},
	{0x081035D8, 20, GetCameraCoords},
	{0x081035EC, 92, MapGridSetMetatileImpassabilityAt},
	{0x08103648, 50, SkipCopyingMetatileFromSavedMap},
	{0x0810367C, 56, CopyTilesetToVram},
	{0x081036B4, 56, CopyTilesetToVramUsingHeap},
	{0x081036EC, 2, ApplyGlobalTintToPaletteEntries},
	{0x081036F0, 2, ApplyGlobalTintToPaletteSlot},
	{0x081036F4, 102, LoadTilesetPalette},
	{0x0810375C, 50, CopyPrimaryTilesetToVram},
	{0x08103790, 58, CopySecondaryTilesetToVram},
	{0x081037CC, 58, CopySecondaryTilesetToVramUsingHeap},
	{0x08103808, 82, LoadPrimaryTilesetPalette},
	{0x0810385C, 82, LoadSecondaryTilesetPalette},
	{0x081038B0, 112, CopyMapTilesetsToVram},
	{0x08103920, 32, LoadMapTilesetPalettes},
}

// 0x081025D0
func GetMapHeaderFromConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0xB500)
	c.Thumb(0x7A41)
	c.Thumb(0x7A00)
	c.R[14] = 0x081025DB
	c.NCallT(0x0813E778)
	if c.U != 0 {
		if c.U != 0x081025DB {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081025E0
func InitMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(20)
	c.Thumb(0xB510)
	c.R[15] = 0x081025E6
	c.Thumb(0x4C06)
	c.Thumb(0x0020)
	c.R[14] = 0x081025EB
	InitMapLayoutData(c)
	if c.U != 0 {
		if c.U != 0x081025EB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6860)
	c.R[14] = 0x081025F1
	c.NCallT(0x081A4050)
	if c.U != 0 {
		if c.U != 0x081025F1 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x081025F5
	c.NCallT(0x081A3924)
	if c.U != 0 {
		if c.U != 0x081025F5 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102600
func InitMapFromSavedGame(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0xB510)
	c.R[15] = 0x08102606
	c.Thumb(0x4C0A)
	c.Thumb(0x0020)
	c.R[14] = 0x0810260B
	InitMapLayoutData(c)
	if c.U != 0 {
		if c.U != 0x0810260B {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2000)
	c.R[14] = 0x08102611
	c.NCallT(0x081A43F0)
	if c.U != 0 {
		if c.U != 0x08102611 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6860)
	c.R[14] = 0x08102617
	c.NCallT(0x081A4050)
	if c.U != 0 {
		if c.U != 0x08102617 {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0810261B
	LoadSavedMapView(c)
	if c.U != 0 {
		if c.U != 0x0810261B {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x0810261F
	c.NCallT(0x081A3924)
	if c.U != 0 {
		if c.U != 0x0810261F {
			return
		}
		c.U = 0
	}
	c.R[15] = 0x08102622
	c.Thumb(0x4B04)
	c.Thumb(0xCB03)
	c.R[14] = 0x08102627
	c.NCallT(0x081C6AD0)
	if c.U != 0 {
		if c.U != 0x08102627 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102634
func InitBattlePyramidMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(36)
	c.Thumb(0xB530)
	c.R[15] = 0x0810263A
	c.Thumb(0x4C09)
	c.Thumb(0xB081)
	c.R[15] = 0x0810263E
	c.Thumb(0x4B09)
	c.Thumb(0x0600)
	c.Thumb(0x0021)
	c.R[15] = 0x08102644
	c.Thumb(0x4A08)
	c.Thumb(0x0E05)
	c.Thumb(0x4668)
	c.Thumb(0x9300)
	c.R[14] = 0x0810264D
	c.NCallT(0x082E484C)
	if c.U != 0 {
		if c.U != 0x0810264D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0029)
	c.Thumb(0x0020)
	c.R[14] = 0x08102655
	c.NCallT(0x080776B8)
	if c.U != 0 {
		if c.U != 0x08102655 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB001)
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102668
func InitTrainerHillMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB510)
	c.R[15] = 0x0810266E
	c.Thumb(0x4C08)
	c.Thumb(0xB081)
	c.R[15] = 0x08102672
	c.Thumb(0x4B08)
	c.Thumb(0x0021)
	c.Thumb(0x4668)
	c.R[15] = 0x08102678
	c.Thumb(0x4A07)
	c.Thumb(0x9300)
	c.R[14] = 0x0810267D
	c.NCallT(0x082E484C)
	if c.U != 0 {
		if c.U != 0x0810267D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0020)
	c.R[14] = 0x08102683
	c.NCallT(0x081C48FC)
	if c.U != 0 {
		if c.U != 0x08102683 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB001)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102698
func InitMapLayoutData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(62)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x4645)
	c.Thumb(0x464E)
	c.Thumb(0xB5E0)
	c.R[15] = 0x081026A8
	c.Thumb(0x4D22)
	c.Thumb(0x6804)
	c.R[15] = 0x081026AC
	c.Thumb(0x4B22)
	c.Thumb(0xB081)
	c.Thumb(0x0029)
	c.R[15] = 0x081026B2
	c.Thumb(0x4A22)
	c.Thumb(0x4683)
	c.Thumb(0x4668)
	c.Thumb(0x9300)
	c.R[14] = 0x081026BB
	c.NCallT(0x082E484C)
	if c.U != 0 {
		if c.U != 0x081026BB {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6827)
	c.Thumb(0x6861)
	c.Thumb(0x0038)
	c.Thumb(0x000B)
	c.R[15] = 0x081026C6
	c.Thumb(0x4A1E)
	c.Thumb(0x300F)
	c.Thumb(0x330E)
	c.Thumb(0x6053)
	c.Thumb(0x6095)
	c.Thumb(0x6010)
	c.Thumb(0x22A0)
	c.Thumb(0x4343)
	c.Thumb(0x0192)
	c.Thumb(0x4293)
	if c.Cond(0xD) {
		goto L_081026EA
	}
L_081026D8:
	c.NT(18)
	c.Thumb(0xB001)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081026EA:
	c.NT(42)
	c.Thumb(0x0409)
	c.Thumb(0x0C0B)
	c.Thumb(0x4698)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_08102728
	}
	c.Thumb(0x003B)
	c.Thumb(0x043F)
	c.Thumb(0x3310)
	c.Thumb(0x0C3A)
	c.Thumb(0x68E6)
	c.Thumb(0x00DC)
	c.Thumb(0x1AE4)
	c.Thumb(0x0013)
	c.Thumb(0x330F)
	c.Thumb(0x0064)
	c.Thumb(0x005B)
	c.Thumb(0x1964)
	c.Thumb(0x4691)
	c.Thumb(0x469A)
	c.Thumb(0x2500)
	c.Thumb(0x0057)
L_08102714:
	c.NT(18)
	c.Thumb(0x0021)
	c.Thumb(0x0030)
	c.Thumb(0x464A)
	c.Thumb(0x3501)
	c.R[14] = 0x08102721
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x08102721 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4454)
	c.Thumb(0x19F6)
	c.Thumb(0x45A8)
	if c.Cond(0x1) {
		goto L_08102714
	}
L_08102728:
	c.NT(6)
	c.Thumb(0x4658)
	c.R[14] = 0x0810272F
	InitBackupMapLayoutConnections(c)
	if c.U != 0 {
		if c.U != 0x0810272F {
			return
		}
		c.U = 0
	}
	goto L_081026D8
}

// 0x08102740
func InitBackupMapLayoutData(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(56)
	c.Thumb(0xB5F0)
	c.Thumb(0x464F)
	c.Thumb(0x46D6)
	c.Thumb(0x4646)
	c.Thumb(0x0412)
	c.Thumb(0x0409)
	c.Thumb(0x0C13)
	c.Thumb(0xB5C0)
	c.Thumb(0x0004)
	c.Thumb(0x4699)
	c.Thumb(0x0C0F)
	c.Thumb(0x2A00)
	if c.Cond(0x0) {
		goto L_0810278C
	}
	c.R[15] = 0x0810275E
	c.Thumb(0x4B10)
	c.Thumb(0x681A)
	c.Thumb(0x3201)
	c.Thumb(0x689D)
	c.Thumb(0x00D3)
	c.Thumb(0x1A9B)
	c.Thumb(0x005B)
	c.Thumb(0x18ED)
	c.Thumb(0x003B)
	c.Thumb(0x330F)
	c.Thumb(0x005B)
	c.Thumb(0x4698)
	c.Thumb(0x007B)
	c.Thumb(0x469A)
	c.Thumb(0x2600)
L_08102778:
	c.NT(18)
	c.Thumb(0x0029)
	c.Thumb(0x0020)
	c.Thumb(0x003A)
	c.Thumb(0x3601)
	c.R[14] = 0x08102785
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x08102785 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4445)
	c.Thumb(0x4454)
	c.Thumb(0x454E)
	if c.Cond(0xB) {
		goto L_08102778
	}
L_0810278C:
	c.NT(14)
	c.Thumb(0xBCE0)
	c.Thumb(0x46BA)
	c.Thumb(0x46B1)
	c.Thumb(0x46A8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081027A0
func InitBackupMapLayoutConnections(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0xB5F0)
	c.Thumb(0x46C6)
	c.Thumb(0x68C3)
	c.Thumb(0x4680)
	c.Thumb(0xB500)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0810280E
	}
	c.Thumb(0x681F)
	c.Thumb(0x685C)
	c.Thumb(0x2300)
	c.R[15] = 0x081027B8
	c.Thumb(0x4E21)
	c.Thumb(0x6033)
	c.Thumb(0x2F00)
	if c.Cond(0xD) {
		goto L_0810280E
	}
	c.Thumb(0x2500)
	goto L_081027E0
L_081027C0:
	c.NT(22)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_08102818
	}
	c.Thumb(0x2B02)
	if c.Cond(0x1) {
		goto L_081027D8
	}
	c.Thumb(0x0001)
	c.Thumb(0x4640)
	c.R[14] = 0x081027D1
	FillNorthConnection(c)
	if c.U != 0 {
		if c.U != 0x081027D1 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2202)
	c.Thumb(0x7833)
	c.Thumb(0x4313)
	c.Thumb(0x7033)
L_081027D8:
	c.NT(8)
	c.Thumb(0x3501)
	c.Thumb(0x340C)
	c.Thumb(0x42AF)
	if c.Cond(0x0) {
		goto L_0810280E
	}
L_081027E0:
	c.NT(42)
	c.Thumb(0x7A61)
	c.Thumb(0x7A20)
	c.R[14] = 0x081027E9
	c.NCallT(0x0813E778)
	if c.U != 0 {
		if c.U != 0x081027E9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x7823)
	c.Thumb(0x6862)
	c.Thumb(0x2B03)
	if c.Cond(0x0) {
		goto L_0810282A
	}
	if c.Cond(0x9) {
		goto L_081027C0
	}
	c.Thumb(0x2B04)
	if c.Cond(0x1) {
		goto L_081027D8
	}
	c.Thumb(0x0001)
	c.Thumb(0x4640)
	c.R[14] = 0x081027FF
	FillEastConnection(c)
	if c.U != 0 {
		if c.U != 0x081027FF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2208)
	c.Thumb(0x7833)
	c.Thumb(0x3501)
	c.Thumb(0x4313)
	c.Thumb(0x7033)
	c.Thumb(0x340C)
	c.Thumb(0x42AF)
	if c.Cond(0x1) {
		goto L_081027E0
	}
L_0810280E:
	c.NT(10)
	c.Thumb(0xBC80)
	c.Thumb(0x46B8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102818:
	c.NT(16)
	c.Thumb(0x0001)
	c.Thumb(0x4640)
	c.R[14] = 0x08102821
	FillSouthConnection(c)
	if c.U != 0 {
		if c.U != 0x08102821 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2201)
	c.Thumb(0x7833)
	c.Thumb(0x4313)
	c.Thumb(0x7033)
	goto L_081027D8
L_0810282A:
	c.NT(16)
	c.Thumb(0x0001)
	c.Thumb(0x4640)
	c.R[14] = 0x08102833
	FillWestConnection(c)
	if c.U != 0 {
		if c.U != 0x08102833 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2204)
	c.Thumb(0x7833)
	c.Thumb(0x4313)
	c.Thumb(0x7033)
	goto L_081027D8
}

// 0x08102840
func FillConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(60)
	c.Thumb(0xB5F0)
	c.Thumb(0x46CE)
	c.Thumb(0x4647)
	c.Thumb(0xB580)
	c.Thumb(0x9C09)
	c.Thumb(0x2C00)
	if c.Cond(0xD) {
		goto L_08102898
	}
	c.Thumb(0x6814)
	c.Thumb(0x9A07)
	c.Thumb(0x6826)
	c.Thumb(0x4372)
	c.Thumb(0x18D2)
	c.R[15] = 0x0810285C
	c.Thumb(0x4B12)
	c.Thumb(0x4699)
	c.Thumb(0x68E5)
	c.Thumb(0x0052)
	c.Thumb(0x18AD)
	c.Thumb(0x464A)
	c.Thumb(0x681B)
	c.Thumb(0x434B)
	c.Thumb(0x6894)
	c.Thumb(0x181B)
	c.Thumb(0x005B)
	c.Thumb(0x18E4)
	c.Thumb(0x0073)
	c.Thumb(0x2600)
	c.Thumb(0x4698)
	c.Thumb(0x9B08)
	c.Thumb(0x02DF)
	c.Thumb(0x0AFF)
L_0810287C:
	c.NT(26)
	c.Thumb(0x0021)
	c.Thumb(0x0028)
	c.Thumb(0x003A)
	c.R[14] = 0x08102887
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x08102887 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x464B)
	c.Thumb(0x681B)
	c.Thumb(0x005B)
	c.Thumb(0x18E4)
	c.Thumb(0x9B09)
	c.Thumb(0x3601)
	c.Thumb(0x4445)
	c.Thumb(0x42B3)
	if c.Cond(0x1) {
		goto L_0810287C
	}
L_08102898:
	c.NT(12)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081028A8
func FillSouthConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB5F0)
	c.Thumb(0x46CE)
	c.Thumb(0x4647)
	c.Thumb(0xB580)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_08102908
	}
	c.Thumb(0x680C)
	c.Thumb(0x6803)
	c.Thumb(0x6826)
	c.Thumb(0x6858)
	c.R[15] = 0x081028C0
	c.Thumb(0x4B1E)
	c.Thumb(0x1DD1)
	c.Thumb(0x4698)
	c.Thumb(0x3007)
	c.Thumb(0x681B)
	c.Thumb(0x1877)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102914
	}
	c.Thumb(0x429F)
	if c.Cond(0xB) {
		goto L_08102924
	}
	c.Thumb(0x2200)
	c.Thumb(0x1A5F)
L_081028D4:
	c.NT(26)
	c.Thumb(0x68E5)
	c.Thumb(0x18AD)
	c.Thumb(0x4642)
	c.Thumb(0x4343)
	c.Thumb(0x6894)
	c.Thumb(0x185B)
	c.Thumb(0x005B)
	c.Thumb(0x18E4)
	c.Thumb(0x0073)
	c.Thumb(0x4699)
	c.Thumb(0x2607)
	c.Thumb(0x02FF)
	c.Thumb(0x0AFF)
L_081028EE:
	c.NT(24)
	c.Thumb(0x0021)
	c.Thumb(0x0028)
	c.Thumb(0x003A)
	c.R[14] = 0x081028F9
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x081028F9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x3E01)
	c.Thumb(0x005B)
	c.Thumb(0x18E4)
	c.Thumb(0x444D)
	c.Thumb(0x2E00)
	if c.Cond(0x1) {
		goto L_081028EE
	}
L_08102908:
	c.NT(12)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102914:
	c.NT(16)
	c.Thumb(0x429F)
	if c.Cond(0xC) {
		goto L_0810292A
	}
	c.Thumb(0x2107)
	c.Thumb(0x4249)
	c.Thumb(0x1A8A)
	c.Thumb(0x0052)
	c.Thumb(0x2100)
	goto L_081028D4
L_08102924:
	c.NT(6)
	c.Thumb(0x0037)
	c.Thumb(0x2200)
	goto L_081028D4
L_0810292A:
	c.NT(14)
	c.Thumb(0x2107)
	c.Thumb(0x4249)
	c.Thumb(0x1A8A)
	c.Thumb(0x001F)
	c.Thumb(0x2100)
	c.Thumb(0x0052)
	goto L_081028D4
}

// 0x0810293C
func FillNorthConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB5F0)
	c.Thumb(0x46CE)
	c.Thumb(0x4647)
	c.Thumb(0xB580)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_0810299C
	}
	c.Thumb(0x6808)
	c.R[15] = 0x0810294E
	c.Thumb(0x4D1E)
	c.Thumb(0x6801)
	c.Thumb(0x6843)
	c.Thumb(0x1DD4)
	c.Thumb(0x46A8)
	c.Thumb(0x3B07)
	c.Thumb(0x682D)
	c.Thumb(0x190F)
	c.Thumb(0x2C00)
	if c.Cond(0xB) {
		goto L_081029A8
	}
	c.Thumb(0x0066)
	c.Thumb(0x42AF)
	if c.Cond(0xB) {
		goto L_081029B6
	}
	c.Thumb(0x2200)
	c.Thumb(0x1B2F)
L_08102968:
	c.NT(26)
	c.Thumb(0x434B)
	c.Thumb(0x68C5)
	c.Thumb(0x189B)
	c.Thumb(0x005B)
	c.Thumb(0x18ED)
	c.Thumb(0x4643)
	c.Thumb(0x689C)
	c.Thumb(0x004B)
	c.Thumb(0x19A4)
	c.Thumb(0x4699)
	c.Thumb(0x2607)
	c.Thumb(0x02FF)
	c.Thumb(0x0AFF)
L_08102982:
	c.NT(24)
	c.Thumb(0x0021)
	c.Thumb(0x0028)
	c.Thumb(0x003A)
	c.R[14] = 0x0810298D
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x0810298D {
			return
		}
		c.U = 0
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x3E01)
	c.Thumb(0x005B)
	c.Thumb(0x18E4)
	c.Thumb(0x444D)
	c.Thumb(0x2E00)
	if c.Cond(0x1) {
		goto L_08102982
	}
L_0810299C:
	c.NT(12)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081029A8:
	c.NT(14)
	c.Thumb(0x2407)
	c.Thumb(0x4264)
	c.Thumb(0x1AA2)
	c.Thumb(0x42AF)
	if c.Cond(0xC) {
		goto L_081029BC
	}
	c.Thumb(0x2600)
	goto L_08102968
L_081029B6:
	c.NT(6)
	c.Thumb(0x000F)
	c.Thumb(0x2200)
	goto L_08102968
L_081029BC:
	c.NT(6)
	c.Thumb(0x002F)
	c.Thumb(0x2600)
	goto L_08102968
}

// 0x081029C8
func FillWestConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB570)
	c.Thumb(0x4694)
	c.Thumb(0xB083)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_08102A08
	}
	c.Thumb(0x4660)
	c.Thumb(0x680B)
	c.Thumb(0x685A)
	c.R[15] = 0x081029DC
	c.Thumb(0x4C14)
	c.Thumb(0x681B)
	c.Thumb(0x3007)
	c.Thumb(0x1815)
	c.Thumb(0x002E)
	c.Thumb(0x6864)
	c.Thumb(0x3B07)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08102A10
	}
	c.Thumb(0x2500)
	c.Thumb(0x46AC)
	c.Thumb(0x42A6)
	if c.Cond(0xB) {
		goto L_081029F4
	}
	c.Thumb(0x1A22)
L_081029F4:
	c.NT(18)
	c.Thumb(0x9202)
	c.Thumb(0x2207)
	c.Thumb(0x9201)
	c.Thumb(0x4662)
	c.Thumb(0x9200)
	c.Thumb(0x000A)
	c.Thumb(0x0001)
	c.Thumb(0x2000)
	c.R[14] = 0x08102A09
	FillConnection(c)
	if c.U != 0 {
		if c.U != 0x08102A09 {
			return
		}
		c.U = 0
	}
L_08102A08:
	c.NT(8)
	c.Thumb(0xB003)
	c.Thumb(0xBC70)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102A10:
	c.NT(20)
	c.Thumb(0x2007)
	c.Thumb(0x4662)
	c.Thumb(0x4240)
	c.Thumb(0x1A82)
	c.Thumb(0x4694)
	c.Thumb(0x002A)
	c.Thumb(0x42A5)
	if c.Cond(0xC) {
		goto L_08102A24
	}
	c.Thumb(0x2000)
	goto L_081029F4
L_08102A24:
	c.NT(6)
	c.Thumb(0x0022)
	c.Thumb(0x2000)
	goto L_081029F4
}

// 0x08102A30
func FillEastConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(40)
	c.Thumb(0xB530)
	c.Thumb(0x468C)
	c.Thumb(0xB083)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_08102A68
	}
	c.Thumb(0x680B)
	c.Thumb(0x6801)
	c.Thumb(0x685B)
	c.Thumb(0x6808)
	c.R[15] = 0x08102A46
	c.Thumb(0x4C11)
	c.Thumb(0x1DD1)
	c.Thumb(0x6864)
	c.Thumb(0x3007)
	c.Thumb(0x185D)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102A70
	}
	c.Thumb(0x2200)
	c.Thumb(0x42A5)
	if c.Cond(0xB) {
		goto L_08102A58
	}
	c.Thumb(0x1A63)
L_08102A58:
	c.NT(14)
	c.Thumb(0x9302)
	c.Thumb(0x2308)
	c.Thumb(0x9200)
	c.Thumb(0x9301)
	c.Thumb(0x4662)
	c.Thumb(0x2300)
	c.R[14] = 0x08102A69
	FillConnection(c)
	if c.U != 0 {
		if c.U != 0x08102A69 {
			return
		}
		c.U = 0
	}
L_08102A68:
	c.NT(8)
	c.Thumb(0xB003)
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102A70:
	c.NT(16)
	c.Thumb(0x2307)
	c.Thumb(0x425B)
	c.Thumb(0x1A9A)
	c.Thumb(0x002B)
	c.Thumb(0x42A5)
	if c.Cond(0xC) {
		goto L_08102A80
	}
	c.Thumb(0x2100)
	goto L_08102A58
L_08102A80:
	c.NT(6)
	c.Thumb(0x0023)
	c.Thumb(0x2100)
	goto L_08102A58
}

// 0x08102A8C
func MapGridGetElevationAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08102AA4
	}
	c.R[15] = 0x08102A94
	c.Thumb(0x4A16)
	c.Thumb(0x6813)
	c.Thumb(0x469C)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102AA4
	}
	c.Thumb(0x2301)
	c.Thumb(0x4584)
	if c.Cond(0xD) {
		goto L_08102AC8
	}
	c.Thumb(0x061B)
	if c.Cond(0x1) {
		goto L_08102ACE
	}
L_08102AA4:
	c.NT(32)
	c.R[15] = 0x08102AA8
	c.Thumb(0x4B12)
	c.Thumb(0x3101)
	c.Thumb(0x681A)
	c.Thumb(0x004B)
	c.Thumb(0x2102)
	c.Thumb(0x4019)
	c.Thumb(0x2301)
	c.Thumb(0x3001)
	c.Thumb(0x4003)
	c.Thumb(0x20C0)
	c.Thumb(0x4319)
	c.Thumb(0x6893)
	c.Thumb(0x0049)
	c.Thumb(0x5ACB)
	c.Thumb(0x0100)
	c.Thumb(0x4318)
L_08102AC4:
	c.NT(2)
	c.Thumb(0x0B00)
L_08102AC6:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102AC8:
	c.NT(6)
	c.Thumb(0x2300)
	c.Thumb(0x061B)
	if c.Cond(0x0) {
		goto L_08102AA4
	}
L_08102ACE:
	c.NT(30)
	c.Thumb(0x6853)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_08102AA4
	}
	c.Thumb(0x000B)
	c.Thumb(0x4661)
	c.Thumb(0x4359)
	c.Thumb(0x6893)
	c.Thumb(0x1809)
	c.Thumb(0x0049)
	c.Thumb(0x5AC8)
	c.R[15] = 0x08102AE6
	c.Thumb(0x4B04)
	c.Thumb(0x4298)
	if c.Cond(0x1) {
		goto L_08102AC4
	}
	c.Thumb(0x2000)
	goto L_08102AC6
}

// 0x08102AF8
func MapGridGetCollisionAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08102B10
	}
	c.R[15] = 0x08102B00
	c.Thumb(0x4A17)
	c.Thumb(0x6813)
	c.Thumb(0x469C)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102B10
	}
	c.Thumb(0x2301)
	c.Thumb(0x4584)
	if c.Cond(0xD) {
		goto L_08102B36
	}
	c.Thumb(0x061B)
	if c.Cond(0x1) {
		goto L_08102B3C
	}
L_08102B10:
	c.NT(32)
	c.R[15] = 0x08102B14
	c.Thumb(0x4B13)
	c.Thumb(0x3101)
	c.Thumb(0x681A)
	c.Thumb(0x004B)
	c.Thumb(0x2102)
	c.Thumb(0x4019)
	c.Thumb(0x2301)
	c.Thumb(0x3001)
	c.Thumb(0x4003)
	c.Thumb(0x20C0)
	c.Thumb(0x4319)
	c.Thumb(0x6893)
	c.Thumb(0x0049)
	c.Thumb(0x5ACB)
	c.Thumb(0x0100)
	c.Thumb(0x4318)
L_08102B30:
	c.NT(4)
	c.Thumb(0x0500)
	c.Thumb(0x0F80)
L_08102B34:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102B36:
	c.NT(6)
	c.Thumb(0x2300)
	c.Thumb(0x061B)
	if c.Cond(0x0) {
		goto L_08102B10
	}
L_08102B3C:
	c.NT(30)
	c.Thumb(0x6853)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_08102B10
	}
	c.Thumb(0x000B)
	c.Thumb(0x4661)
	c.Thumb(0x4359)
	c.Thumb(0x6893)
	c.Thumb(0x1809)
	c.Thumb(0x0049)
	c.Thumb(0x5AC8)
	c.R[15] = 0x08102B54
	c.Thumb(0x4B04)
	c.Thumb(0x4298)
	if c.Cond(0x1) {
		goto L_08102B30
	}
	c.Thumb(0x2001)
	goto L_08102B34
}

// 0x08102B68
func MapGridGetMetatileIdAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(24)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08102B80
	}
	c.R[15] = 0x08102B70
	c.Thumb(0x4B1F)
	c.Thumb(0x469C)
	c.Thumb(0x681A)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102B80
	}
	c.Thumb(0x2301)
	c.Thumb(0x4282)
	if c.Cond(0xD) {
		goto L_08102BA6
	}
	c.Thumb(0x061B)
	if c.Cond(0x1) {
		goto L_08102BAC
	}
L_08102B80:
	c.NT(32)
	c.R[15] = 0x08102B84
	c.Thumb(0x4B1B)
	c.Thumb(0x3101)
	c.Thumb(0x681A)
	c.Thumb(0x004B)
	c.Thumb(0x2102)
	c.Thumb(0x4019)
	c.Thumb(0x1C43)
	c.Thumb(0x2001)
	c.Thumb(0x4018)
	c.Thumb(0x4301)
	c.Thumb(0x6893)
	c.Thumb(0x0049)
	c.Thumb(0x5ACA)
	c.Thumb(0x23C0)
	c.Thumb(0x011B)
	c.Thumb(0x4313)
L_08102BA0:
	c.NT(4)
	c.Thumb(0x0598)
	c.Thumb(0x0D80)
L_08102BA4:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102BA6:
	c.NT(6)
	c.Thumb(0x2300)
	c.Thumb(0x061B)
	if c.Cond(0x0) {
		goto L_08102B80
	}
L_08102BAC:
	c.NT(62)
	c.Thumb(0x4663)
	c.Thumb(0x685B)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_08102B80
	}
	c.Thumb(0x4663)
	c.Thumb(0x434A)
	c.Thumb(0x689B)
	c.Thumb(0x1812)
	c.Thumb(0x0052)
	c.Thumb(0x5AD3)
	c.R[15] = 0x08102BC4
	c.Thumb(0x4A0C)
	c.Thumb(0x4293)
	if c.Cond(0x1) {
		goto L_08102BA0
	}
	c.R[15] = 0x08102BCA
	c.Thumb(0x4B0A)
	c.Thumb(0x681B)
	c.Thumb(0x2201)
	c.Thumb(0x469C)
	c.Thumb(0x2302)
	c.Thumb(0x3101)
	c.Thumb(0x3001)
	c.Thumb(0x0049)
	c.Thumb(0x4002)
	c.Thumb(0x400B)
	c.Thumb(0x4313)
	c.Thumb(0x4662)
	c.Thumb(0x6892)
	c.Thumb(0x005B)
	c.Thumb(0x5A98)
	c.Thumb(0x0580)
	c.Thumb(0x0D80)
	goto L_08102BA4
}

// 0x08102BF8
func MapGridGetMetatileBehaviorAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0xB500)
	c.R[14] = 0x08102BFF
	MapGridGetMetatileIdAt(c)
	if c.U != 0 {
		if c.U != 0x08102BFF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2280)
	c.R[15] = 0x08102C04
	c.Thumb(0x4B09)
	c.Thumb(0x0092)
	c.Thumb(0x681B)
	c.Thumb(0x4290)
	if c.Cond(0xB) {
		goto L_08102C1E
	}
	c.Thumb(0x695B)
	c.R[15] = 0x08102C10
	c.Thumb(0x4A07)
	c.Thumb(0x691B)
	c.Thumb(0x1880)
	c.Thumb(0x0040)
	c.Thumb(0x5AC3)
L_08102C16:
	c.NT(8)
	c.Thumb(0x20FF)
	c.Thumb(0x4018)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102C1E:
	c.NT(10)
	c.Thumb(0x691B)
	c.Thumb(0x691B)
	c.Thumb(0x0040)
	c.Thumb(0x5AC3)
	goto L_08102C16
}

// 0x08102C30
func MapGridGetMetatileLayerTypeAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0xB500)
	c.R[14] = 0x08102C37
	MapGridGetMetatileIdAt(c)
	if c.U != 0 {
		if c.U != 0x08102C37 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2280)
	c.R[15] = 0x08102C3C
	c.Thumb(0x4B09)
	c.Thumb(0x0092)
	c.Thumb(0x681B)
	c.Thumb(0x4290)
	if c.Cond(0xB) {
		goto L_08102C54
	}
	c.Thumb(0x695B)
	c.R[15] = 0x08102C48
	c.Thumb(0x4A07)
	c.Thumb(0x691B)
	c.Thumb(0x1880)
	c.Thumb(0x0040)
	c.Thumb(0x5AC0)
L_08102C4E:
	c.NT(6)
	c.Thumb(0x0B00)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102C54:
	c.NT(10)
	c.Thumb(0x691B)
	c.Thumb(0x691B)
	c.Thumb(0x0040)
	c.Thumb(0x5AC0)
	goto L_08102C4E
}

// 0x08102C68
func MapGridSetMetatileIdAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0x0412)
	c.Thumb(0xB510)
	c.Thumb(0x0C12)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08102C86
	}
	c.R[15] = 0x08102C76
	c.Thumb(0x4B11)
	c.Thumb(0x469C)
	c.Thumb(0x681C)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102C86
	}
	c.Thumb(0x2301)
	c.Thumb(0x4284)
	if c.Cond(0xD) {
		goto L_08102C8C
	}
	c.Thumb(0x061B)
	if c.Cond(0x1) {
		goto L_08102C92
	}
L_08102C86:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102C8C:
	c.NT(6)
	c.Thumb(0x2300)
	c.Thumb(0x061B)
	if c.Cond(0x0) {
		goto L_08102C86
	}
L_08102C92:
	c.NT(36)
	c.Thumb(0x4663)
	c.Thumb(0x685B)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_08102C86
	}
	c.Thumb(0x0023)
	c.Thumb(0x434B)
	c.Thumb(0x1819)
	c.Thumb(0x4663)
	c.Thumb(0x6898)
	c.Thumb(0x0049)
	c.Thumb(0x5A43)
	c.Thumb(0x0512)
	c.Thumb(0x0B1B)
	c.Thumb(0x031B)
	c.Thumb(0x0D12)
	c.Thumb(0x4313)
	c.Thumb(0x5243)
	goto L_08102C86
}

// 0x08102CBC
func MapGridSetMetatileEntryAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0x0412)
	c.Thumb(0xB510)
	c.Thumb(0x0C12)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08102CDA
	}
	c.R[15] = 0x08102CCA
	c.Thumb(0x4B0E)
	c.Thumb(0x469C)
	c.Thumb(0x681C)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08102CDA
	}
	c.Thumb(0x2301)
	c.Thumb(0x4284)
	if c.Cond(0xD) {
		goto L_08102CE0
	}
	c.Thumb(0x061B)
	if c.Cond(0x1) {
		goto L_08102CE6
	}
L_08102CDA:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102CE0:
	c.NT(6)
	c.Thumb(0x2300)
	c.Thumb(0x061B)
	if c.Cond(0x0) {
		goto L_08102CDA
	}
L_08102CE6:
	c.NT(24)
	c.Thumb(0x4663)
	c.Thumb(0x685B)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_08102CDA
	}
	c.Thumb(0x0023)
	c.Thumb(0x434B)
	c.Thumb(0x1819)
	c.Thumb(0x4663)
	c.Thumb(0x689B)
	c.Thumb(0x0049)
	c.Thumb(0x52CA)
	goto L_08102CDA
}

// 0x08102D04
func GetMetatileAttributesById(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(36)
	c.Thumb(0x2380)
	c.Thumb(0x0400)
	c.Thumb(0x0C00)
	c.Thumb(0x009B)
	c.Thumb(0x4298)
	if c.Cond(0x3) {
		goto L_08102D2E
	}
	c.Thumb(0x2380)
	c.Thumb(0x00DB)
	c.Thumb(0x4298)
	if c.Cond(0x2) {
		goto L_08102D2A
	}
	c.R[15] = 0x08102D1C
	c.Thumb(0x4B08)
	c.Thumb(0x681B)
	c.R[15] = 0x08102D20
	c.Thumb(0x4A08)
	c.Thumb(0x695B)
	c.Thumb(0x1880)
	c.Thumb(0x691B)
	c.Thumb(0x0040)
	c.Thumb(0x5AC0)
L_08102D28:
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102D2A:
	c.NT(4)
	c.Thumb(0x20FF)
	goto L_08102D28
L_08102D2E:
	c.NT(14)
	c.R[15] = 0x08102D32
	c.Thumb(0x4B03)
	c.Thumb(0x681B)
	c.Thumb(0x691B)
	c.Thumb(0x691B)
	c.Thumb(0x0040)
	c.Thumb(0x5AC0)
	goto L_08102D28
}

// 0x08102D44
func SaveMapView(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(38)
	c.R[15] = 0x08102D48
	c.Thumb(0x4B0F)
	c.Thumb(0xB530)
	c.Thumb(0x681C)
	c.Thumb(0x0021)
	c.R[15] = 0x08102D50
	c.Thumb(0x4B0E)
	c.Thumb(0x2002)
	c.Thumb(0x5E22)
	c.Thumb(0x681B)
	c.Thumb(0x005D)
	c.Thumb(0x4353)
	c.Thumb(0x2200)
	c.Thumb(0x5EA0)
	c.Thumb(0x1818)
	c.R[15] = 0x08102D62
	c.Thumb(0x4B0B)
	c.Thumb(0x0040)
	c.Thumb(0x34D9)
	c.Thumb(0x3134)
	c.Thumb(0x18C0)
	c.Thumb(0x34FF)
L_08102D6A:
	c.NT(2)
	c.Thumb(0x2300)
L_08102D6C:
	c.NT(24)
	c.Thumb(0x5AC2)
	c.Thumb(0x52CA)
	c.Thumb(0x3302)
	c.Thumb(0x2B1E)
	if c.Cond(0x1) {
		goto L_08102D6C
	}
	c.Thumb(0x311E)
	c.Thumb(0x1940)
	c.Thumb(0x42A1)
	if c.Cond(0x1) {
		goto L_08102D6A
	}
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102D90
func SavedMapViewIsEmpty(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(16)
	c.R[15] = 0x08102D94
	c.Thumb(0x4B07)
	c.Thumb(0x6819)
	c.Thumb(0x228D)
	c.Thumb(0x000B)
	c.Thumb(0x2000)
	c.Thumb(0x0092)
	c.Thumb(0x3334)
	c.Thumb(0x1889)
L_08102DA0:
	c.NT(16)
	c.Thumb(0x881A)
	c.Thumb(0x3302)
	c.Thumb(0x4310)
	c.Thumb(0x428B)
	if c.Cond(0x1) {
		goto L_08102DA0
	}
	c.Thumb(0x4243)
	c.Thumb(0x4158)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102DB4
func ClearSavedMapView(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB500)
	c.Thumb(0xB081)
	c.Thumb(0x466A)
	c.Thumb(0x2300)
	c.Thumb(0x8053)
	c.R[15] = 0x08102DC2
	c.Thumb(0x4B05)
	c.Thumb(0x6819)
	c.Thumb(0x466B)
	c.R[15] = 0x08102DC8
	c.Thumb(0x4A04)
	c.Thumb(0x3134)
	c.Thumb(0x1C98)
	c.R[14] = 0x08102DCF
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x08102DCF {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08102DDC
func LoadSavedMapView(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB5F0)
	c.Thumb(0x464E)
	c.Thumb(0x4645)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x228D)
	c.Thumb(0xB5E0)
	c.R[15] = 0x08102DEE
	c.Thumb(0x4D6C)
	c.Thumb(0x682E)
	c.Thumb(0x0092)
	c.Thumb(0x0033)
	c.Thumb(0x18B0)
	c.Thumb(0x2200)
	c.Thumb(0xB08A)
	c.Thumb(0x3334)
L_08102DFA:
	c.NT(16)
	c.Thumb(0x8819)
	c.Thumb(0x3302)
	c.Thumb(0x430A)
	c.Thumb(0x4283)
	if c.Cond(0x1) {
		goto L_08102DFA
	}
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_08102E0A
	}
	goto L_08102F5A
L_08102E0A:
	c.NT(78)
	c.Thumb(0x2202)
	c.Thumb(0x5EB1)
	c.Thumb(0x468C)
	c.Thumb(0x2200)
	c.Thumb(0x5EB4)
	c.Thumb(0x000A)
	c.R[15] = 0x08102E1A
	c.Thumb(0x4B62)
	c.Thumb(0x681B)
	c.Thumb(0x4660)
	c.Thumb(0x4358)
	c.Thumb(0x320D)
	c.Thumb(0x9204)
	c.Thumb(0x041A)
	c.Thumb(0x0C12)
	c.Thumb(0x0037)
	c.Thumb(0x9006)
	c.Thumb(0x9100)
	c.R[15] = 0x08102E30
	c.Thumb(0x485D)
	c.Thumb(0x18A1)
	c.Thumb(0x36F7)
	c.Thumb(0x36FF)
	c.Thumb(0x0049)
	c.Thumb(0x9601)
	c.Thumb(0x180E)
	c.Thumb(0x0051)
	c.Thumb(0x9806)
	c.Thumb(0x9602)
	c.Thumb(0x424E)
	c.Thumb(0x46B0)
	c.Thumb(0x46E2)
	c.Thumb(0x4683)
	c.Thumb(0x0092)
	c.Thumb(0x4691)
	c.R[15] = 0x08102E50
	c.Thumb(0x4A56)
	c.Thumb(0x9407)
	c.Thumb(0x9303)
	c.Thumb(0x9508)
	c.Thumb(0x9205)
	c.Thumb(0x3752)
L_08102E58:
	c.NT(12)
	c.Thumb(0x003D)
	c.Thumb(0x9B00)
	c.Thumb(0x3D1E)
	c.Thumb(0x4553)
	if c.Cond(0x0) {
		goto L_08102E64
	}
	goto L_08102F76
L_08102E64:
	c.NT(8)
	c.Thumb(0x2600)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_08102E6C
	}
	goto L_08102F76
L_08102E6C:
	c.NT(12)
	c.Thumb(0x465B)
	c.Thumb(0x005C)
	c.Thumb(0x9B02)
	c.Thumb(0x18E4)
	c.Thumb(0x2EFF)
	if c.Cond(0x0) {
		goto L_08102EA2
	}
L_08102E78:
	c.NT(10)
	c.Thumb(0x0023)
	c.Thumb(0x2E00)
	if c.Cond(0x1) {
		goto L_08102E82
	}
	c.Thumb(0x464B)
	c.Thumb(0x1AE3)
L_08102E82:
	c.NT(30)
	c.Thumb(0x8818)
	c.Thumb(0x0580)
	c.Thumb(0x0031)
	c.Thumb(0x0D80)
	c.R[14] = 0x08102E8F
	c.NCallT(0x08105E48)
	if c.U != 0 {
		if c.U != 0x08102E8F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2801)
	if c.Cond(0x0) {
		goto L_08102F6C
	}
	c.Thumb(0x4642)
	c.Thumb(0x882B)
	c.Thumb(0x3502)
	c.Thumb(0x52A3)
	c.Thumb(0x42BD)
	if c.Cond(0x0) {
		goto L_08102EC0
	}
	c.Thumb(0x3402)
	goto L_08102E78
L_08102EA2:
	c.NT(4)
	c.Thumb(0x4642)
	goto L_08102EB4
L_08102EA6:
	c.NT(14)
	c.Thumb(0x8869)
	c.Thumb(0x1CA3)
	c.Thumb(0x3504)
	c.Thumb(0x5299)
	c.Thumb(0x3404)
	c.Thumb(0x42BD)
	if c.Cond(0x0) {
		goto L_08102EBE
	}
L_08102EB4:
	c.NT(10)
	c.Thumb(0x882B)
	c.Thumb(0x52A3)
	c.Thumb(0x1CAB)
	c.Thumb(0x42BB)
	if c.Cond(0x1) {
		goto L_08102EA6
	}
L_08102EBE:
	c.NT(2)
	c.Thumb(0x4690)
L_08102EC0:
	c.NT(64)
	c.Thumb(0x2301)
	c.Thumb(0x449A)
	c.Thumb(0x9B03)
	c.Thumb(0x449B)
	c.Thumb(0x9B01)
	c.Thumb(0x371E)
	c.Thumb(0x429F)
	if c.Cond(0x1) {
		goto L_08102E58
	}
	c.Thumb(0x9B05)
	c.Thumb(0x469B)
	c.Thumb(0x23F0)
	c.Thumb(0x9A00)
	c.Thumb(0x0017)
	c.Thumb(0x9C07)
	c.Thumb(0x031B)
	c.Thumb(0x0424)
	c.Thumb(0x0C26)
	c.Thumb(0x18E4)
	c.Thumb(0x1E53)
	c.Thumb(0x041B)
	c.Thumb(0x141B)
	c.Thumb(0x4698)
	c.Thumb(0x9B04)
	c.Thumb(0x9D08)
	c.Thumb(0x041B)
	c.Thumb(0x141B)
	c.Thumb(0x46AA)
	c.Thumb(0x4699)
	c.Thumb(0x0C25)
	c.Thumb(0x370E)
	c.Thumb(0x0014)
	goto L_08102F16
L_08102F00:
	c.NT(12)
	c.Thumb(0x465B)
	c.Thumb(0x681B)
	c.Thumb(0x685B)
	c.Thumb(0x3B01)
	c.Thumb(0x42BB)
	if c.Cond(0xC) {
		goto L_08102F30
	}
L_08102F0C:
	c.NT(10)
	c.Thumb(0x3601)
	c.Thumb(0x0436)
	c.Thumb(0x0C36)
	c.Thumb(0x42B5)
	if c.Cond(0x0) {
		goto L_08102F44
	}
L_08102F16:
	c.NT(24)
	c.Thumb(0x2C00)
	if c.Cond(0x0) {
		goto L_08102F00
	}
	c.Thumb(0x0430)
	c.Thumb(0x4641)
	c.Thumb(0x1400)
	c.R[14] = 0x08102F25
	c.NCallT(0x08104300)
	if c.U != 0 {
		if c.U != 0x08102F25 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x465B)
	c.Thumb(0x681B)
	c.Thumb(0x685B)
	c.Thumb(0x3B01)
	c.Thumb(0x42BB)
	if c.Cond(0xD) {
		goto L_08102F0C
	}
L_08102F30:
	c.NT(18)
	c.Thumb(0x0430)
	c.Thumb(0x3601)
	c.Thumb(0x4649)
	c.Thumb(0x1400)
	c.Thumb(0x0436)
	c.R[14] = 0x08102F3F
	c.NCallT(0x08104394)
	if c.U != 0 {
		if c.U != 0x08102F3F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0C36)
	c.Thumb(0x42B5)
	if c.Cond(0x1) {
		goto L_08102F16
	}
L_08102F44:
	c.NT(20)
	c.Thumb(0x4655)
	c.Thumb(0x2300)
	c.Thumb(0xAA09)
	c.Thumb(0x6829)
	c.Thumb(0x8053)
	c.Thumb(0xAB09)
	c.R[15] = 0x08102F54
	c.Thumb(0x4A16)
	c.Thumb(0x3134)
	c.Thumb(0x1C98)
	c.R[14] = 0x08102F5B
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x08102F5B {
			return
		}
		c.U = 0
	}
L_08102F5A:
	c.NT(18)
	c.Thumb(0xB00A)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08102F6C:
	c.NT(10)
	c.Thumb(0x3502)
	c.Thumb(0x42BD)
	if c.Cond(0x0) {
		goto L_08102EC0
	}
	c.Thumb(0x3402)
	goto L_08102E78
L_08102F76:
	c.NT(10)
	c.Thumb(0x9B04)
	c.Thumb(0x26FF)
	c.Thumb(0x4553)
	if c.Cond(0x0) {
		goto L_08102F80
	}
	goto L_08102E6C
L_08102F80:
	c.NT(26)
	c.Thumb(0x9B05)
	c.Thumb(0x681B)
	c.Thumb(0x685E)
	c.Thumb(0x9B04)
	c.Thumb(0x3E01)
	c.Thumb(0x1AF6)
	c.Thumb(0x1E73)
	c.Thumb(0x419E)
	c.Thumb(0x23FD)
	c.Thumb(0x4276)
	c.Thumb(0x439E)
	c.Thumb(0x36FF)
	goto L_08102E6C
}

// 0x08102FB0
func MoveMapViewToBackup(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(60)
	c.R[15] = 0x08102FB4
	c.Thumb(0x4A34)
	c.Thumb(0x6811)
	c.Thumb(0x2234)
	c.Thumb(0xB5F0)
	c.Thumb(0x46C6)
	c.Thumb(0x4694)
	c.Thumb(0xB500)
	c.R[15] = 0x08102FC2
	c.Thumb(0x4A32)
	c.Thumb(0x0603)
	c.Thumb(0x448C)
	c.Thumb(0x2400)
	c.Thumb(0x5F08)
	c.Thumb(0x6812)
	c.Thumb(0x2402)
	c.Thumb(0x5F09)
	c.Thumb(0xB081)
	c.Thumb(0x0E1B)
	c.Thumb(0x2B03)
	if c.Cond(0x0) {
		goto L_08103056
	}
	if c.Cond(0x8) {
		goto L_08103048
	}
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_08103062
	}
	c.Thumb(0x2B02)
	if c.Cond(0x1) {
		goto L_08103078
	}
	c.Thumb(0x230D)
	c.Thumb(0x2400)
	c.Thumb(0x2500)
	c.Thumb(0x4698)
	c.Thumb(0x3101)
	c.Thumb(0x3302)
L_08102FEC:
	c.NT(40)
	c.Thumb(0x0057)
	c.Thumb(0x434A)
	c.Thumb(0x1810)
	c.R[15] = 0x08102FF6
	c.Thumb(0x4A26)
	c.Thumb(0x0040)
	c.Thumb(0x1880)
	c.Thumb(0x4642)
	c.Thumb(0x3B0E)
	c.Thumb(0x1911)
	c.Thumb(0x1E5A)
	c.Thumb(0x4193)
	c.Thumb(0x0126)
	c.Thumb(0x1B36)
	c.Thumb(0x19AD)
	c.Thumb(0x010C)
	c.Thumb(0x006D)
	c.Thumb(0x1A64)
	c.Thumb(0x0059)
	c.Thumb(0x4465)
	c.Thumb(0x311C)
L_08103014:
	c.NT(2)
	c.Thumb(0x2300)
L_08103016:
	c.NT(48)
	c.Thumb(0x5AEA)
	c.Thumb(0x52C2)
	c.Thumb(0x3302)
	c.Thumb(0x4299)
	if c.Cond(0x1) {
		goto L_08103016
	}
	c.Thumb(0x360F)
	c.Thumb(0x351E)
	c.Thumb(0x19C0)
	c.Thumb(0x42A6)
	if c.Cond(0x1) {
		goto L_08103014
	}
	c.Thumb(0x466A)
	c.Thumb(0x2300)
	c.Thumb(0x8053)
	c.Thumb(0x466B)
	c.Thumb(0x4661)
	c.R[15] = 0x08103038
	c.Thumb(0x4A16)
	c.Thumb(0x1C98)
	c.R[14] = 0x0810303D
	c.NCallT(0x082E4850)
	if c.U != 0 {
		if c.U != 0x0810303D {
			return
		}
		c.U = 0
	}
	c.Thumb(0xB001)
	c.Thumb(0xBC80)
	c.Thumb(0x46B8)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103048:
	c.NT(14)
	c.Thumb(0x2400)
	c.Thumb(0x2B04)
	if c.Cond(0x1) {
		goto L_0810306E
	}
	c.Thumb(0x230E)
	c.Thumb(0x2501)
	c.Thumb(0x4698)
	goto L_08102FEC
L_08103056:
	c.NT(12)
	c.Thumb(0x230E)
	c.Thumb(0x2400)
	c.Thumb(0x2500)
	c.Thumb(0x4698)
	c.Thumb(0x3001)
	goto L_08102FEC
L_08103062:
	c.NT(12)
	c.Thumb(0x230D)
	c.Thumb(0x2401)
	c.Thumb(0x4698)
	c.Thumb(0x2500)
	c.Thumb(0x3302)
	goto L_08102FEC
L_0810306E:
	c.NT(10)
	c.Thumb(0x230E)
	c.Thumb(0x2500)
	c.Thumb(0x4698)
	c.Thumb(0x3301)
	goto L_08102FEC
L_08103078:
	c.NT(12)
	c.Thumb(0x230E)
	c.Thumb(0x2400)
	c.Thumb(0x4698)
	c.Thumb(0x2500)
	c.Thumb(0x3301)
	goto L_08102FEC
}

// 0x08103094
func GetMapBorderIdAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.R[15] = 0x08103098
	c.Thumb(0x4A2E)
	c.Thumb(0xB530)
	c.Thumb(0x6813)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_081030F2
	}
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_081030B0
	}
	c.Thumb(0x2401)
	c.Thumb(0x46A4)
	c.Thumb(0x4298)
	if c.Cond(0xA) {
		goto L_0810310C
	}
	c.Thumb(0x4664)
	c.Thumb(0x0624)
	if c.Cond(0x1) {
		goto L_08103116
	}
L_081030B0:
	c.NT(6)
	c.Thumb(0x3B08)
	c.Thumb(0x4283)
	if c.Cond(0xC) {
		goto L_081030CE
	}
L_081030B6:
	c.NT(18)
	c.R[15] = 0x081030BA
	c.Thumb(0x4B27)
	c.Thumb(0x781A)
	c.Thumb(0x2308)
	c.Thumb(0x4013)
	c.Thumb(0x425A)
	c.Thumb(0x4153)
	c.Thumb(0x2004)
	c.Thumb(0x425B)
	c.Thumb(0x4318)
L_081030C8:
	c.NT(6)
	c.Thumb(0xBC30)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081030CE:
	c.NT(36)
	c.Thumb(0x2806)
	if c.Cond(0xD) {
		goto L_081030F8
	}
	c.Thumb(0x6853)
	c.Thumb(0x3B07)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_0810313A
	}
	c.Thumb(0x2906)
	if c.Cond(0xC) {
		goto L_0810314A
	}
	c.R[15] = 0x081030E2
	c.Thumb(0x4B1D)
	c.Thumb(0x7818)
	c.Thumb(0x2302)
	c.Thumb(0x4018)
	c.Thumb(0x4242)
	c.Thumb(0x4150)
	c.Thumb(0x4240)
	c.Thumb(0x4398)
	c.Thumb(0x3002)
	goto L_081030C8
L_081030F2:
	c.NT(6)
	c.Thumb(0x3B08)
	c.Thumb(0x4298)
	if c.Cond(0xA) {
		goto L_081030B6
	}
L_081030F8:
	c.NT(20)
	c.R[15] = 0x081030FC
	c.Thumb(0x4B16)
	c.Thumb(0x781A)
	c.Thumb(0x2304)
	c.Thumb(0x4013)
	c.Thumb(0x425A)
	c.Thumb(0x4153)
	c.Thumb(0x2003)
	c.Thumb(0x425B)
	c.Thumb(0x4318)
	goto L_081030C8
L_0810310C:
	c.NT(10)
	c.Thumb(0x2400)
	c.Thumb(0x46A4)
	c.Thumb(0x4664)
	c.Thumb(0x0624)
	if c.Cond(0x0) {
		goto L_081030B0
	}
L_08103116:
	c.NT(36)
	c.Thumb(0x6854)
	c.Thumb(0x428C)
	if c.Cond(0xD) {
		goto L_081030B0
	}
	c.Thumb(0x001C)
	c.Thumb(0x434C)
	c.Thumb(0x46A4)
	c.Thumb(0x4484)
	c.Thumb(0x4665)
	c.Thumb(0x6894)
	c.Thumb(0x006D)
	c.Thumb(0x5B2C)
	c.Thumb(0x46A4)
	c.R[15] = 0x08103132
	c.Thumb(0x4C0A)
	c.Thumb(0x45A4)
	if c.Cond(0x1) {
		goto L_081030B0
	}
	c.Thumb(0x2001)
	c.Thumb(0x4240)
	goto L_081030C8
L_0810313A:
	c.NT(16)
	c.R[15] = 0x0810313E
	c.Thumb(0x4B06)
	c.Thumb(0x7818)
	c.Thumb(0x2301)
	c.Thumb(0x4018)
	c.Thumb(0x3801)
	c.Thumb(0x4398)
	c.Thumb(0x3001)
	goto L_081030C8
L_0810314A:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_081030C8
}

// 0x0810315C
func GetPostCameraMoveMapBorderId(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB510)
	c.R[15] = 0x08103162
	c.Thumb(0x4B07)
	c.Thumb(0x681A)
	c.Thumb(0x2402)
	c.Thumb(0x5F13)
	c.Thumb(0x3307)
	c.Thumb(0x1859)
	c.Thumb(0x2300)
	c.Thumb(0x5ED3)
	c.Thumb(0x3307)
	c.Thumb(0x1818)
	c.R[14] = 0x08103177
	GetMapBorderIdAt(c)
	if c.U != 0 {
		if c.U != 0x08103177 {
			return
		}
		c.U = 0
	}
	c.Thumb(0xBC10)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08103180
func CanCameraMoveInDirection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(50)
	c.R[15] = 0x08103184
	c.Thumb(0x4B0C)
	c.Thumb(0x681B)
	c.Thumb(0x469C)
	c.Thumb(0xB510)
	c.Thumb(0x2102)
	c.Thumb(0x5E59)
	c.R[15] = 0x08103190
	c.Thumb(0x4B0A)
	c.Thumb(0x00C2)
	c.Thumb(0x1898)
	c.Thumb(0x6840)
	c.Thumb(0x3107)
	c.Thumb(0x1809)
	c.Thumb(0x4660)
	c.Thumb(0x2400)
	c.Thumb(0x5F00)
	c.Thumb(0x58D3)
	c.Thumb(0x3007)
	c.Thumb(0x18C0)
	c.R[14] = 0x081031A9
	GetMapBorderIdAt(c)
	if c.U != 0 {
		if c.U != 0x081031A9 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x3001)
	c.Thumb(0x1E43)
	c.Thumb(0x4198)
	c.Thumb(0xBC10)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081031BC
func SetPositionFromConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(50)
	c.Thumb(0xB5F0)
	c.Thumb(0x000C)
	c.Thumb(0x0005)
	c.Thumb(0x7A41)
	c.Thumb(0x7A00)
	c.Thumb(0x0016)
	c.Thumb(0x001F)
	c.R[14] = 0x081031CF
	c.NCallT(0x0813E778)
	if c.U != 0 {
		if c.U != 0x081031CF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2C03)
	if c.Cond(0x0) {
		goto L_0810321C
	}
	if c.Cond(0xC) {
		goto L_081031F0
	}
	c.Thumb(0x2C01)
	if c.Cond(0x0) {
		goto L_0810320A
	}
	c.Thumb(0x2C02)
	if c.Cond(0x1) {
		goto L_08103204
	}
	c.R[15] = 0x081031E0
	c.Thumb(0x4B14)
	c.Thumb(0x681B)
	c.Thumb(0x6869)
	c.Thumb(0x881A)
	c.Thumb(0x1A52)
	c.Thumb(0x801A)
	c.Thumb(0x6802)
	c.Thumb(0x6852)
	c.Thumb(0x805A)
	goto L_08103204
L_081031F0:
	c.NT(20)
	c.Thumb(0x2C04)
	if c.Cond(0x1) {
		goto L_08103204
	}
	c.R[15] = 0x081031F8
	c.Thumb(0x4B0E)
	c.Thumb(0x681A)
	c.Thumb(0x4273)
	c.Thumb(0x6869)
	c.Thumb(0x8013)
	c.Thumb(0x8853)
	c.Thumb(0x1A5B)
	c.Thumb(0x8053)
L_08103204:
	c.NT(6)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0810320A:
	c.NT(18)
	c.R[15] = 0x0810320E
	c.Thumb(0x4B09)
	c.Thumb(0x681A)
	c.Thumb(0x6869)
	c.Thumb(0x8813)
	c.Thumb(0x1A5B)
	c.Thumb(0x8013)
	c.Thumb(0x427B)
	c.Thumb(0x8053)
	goto L_08103204
L_0810321C:
	c.NT(20)
	c.Thumb(0x6802)
	c.R[15] = 0x08103222
	c.Thumb(0x4B04)
	c.Thumb(0x6812)
	c.Thumb(0x681B)
	c.Thumb(0x6869)
	c.Thumb(0x801A)
	c.Thumb(0x885A)
	c.Thumb(0x1A52)
	c.Thumb(0x805A)
	goto L_08103204
}

// 0x08103234
func CameraMove(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(94)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x4645)
	c.Thumb(0x464E)
	c.Thumb(0x2201)
	c.Thumb(0x468C)
	c.Thumb(0xB5E0)
	c.R[15] = 0x08103248
	c.Thumb(0x4C30)
	c.Thumb(0x7823)
	c.R[15] = 0x0810324C
	c.Thumb(0x4E30)
	c.Thumb(0x4393)
	c.Thumb(0xB083)
	c.Thumb(0x6835)
	c.Thumb(0x7023)
	c.Thumb(0x2300)
	c.Thumb(0x5EEF)
	c.Thumb(0x2202)
	c.Thumb(0x5EAB)
	c.Thumb(0x1DD9)
	c.Thumb(0x4461)
	c.Thumb(0x9302)
	c.Thumb(0x4663)
	c.Thumb(0x4684)
	c.Thumb(0x9000)
	c.Thumb(0x1DF8)
	c.Thumb(0x4460)
	c.Thumb(0x9301)
	c.R[14] = 0x08103271
	GetMapBorderIdAt(c)
	if c.U != 0 {
		if c.U != 0x08103271 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x9A00)
	c.Thumb(0x0413)
	c.Thumb(0x0C19)
	c.Thumb(0x9B01)
	c.Thumb(0x041B)
	c.Thumb(0x0C1A)
	c.Thumb(0x1C43)
	c.Thumb(0x4680)
	c.Thumb(0x468A)
	c.Thumb(0x4693)
	c.Thumb(0x2B01)
	if c.Cond(0x8) {
		goto L_081032A6
	}
	c.Thumb(0x2000)
	c.Thumb(0x9B02)
	c.Thumb(0x187F)
	c.Thumb(0x18D6)
	c.Thumb(0x802F)
	c.Thumb(0x806E)
L_08103294:
	c.NT(18)
	c.Thumb(0xB003)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081032A6:
	c.NT(86)
	c.R[14] = 0x081032AB
	SaveMapView(c)
	if c.U != 0 {
		if c.U != 0x081032AB {
			return
		}
		c.U = 0
	}
	c.R[14] = 0x081032AF
	c.NCallT(0x08133140)
	if c.U != 0 {
		if c.U != 0x081032AF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6833)
	c.Thumb(0x2200)
	c.Thumb(0x5E99)
	c.Thumb(0x2702)
	c.Thumb(0x5FDF)
	c.Thumb(0x4640)
	c.Thumb(0x003A)
	c.Thumb(0x4689)
	c.R[14] = 0x081032C3
	GetIncomingConnection(c)
	if c.U != 0 {
		if c.U != 0x081032C3 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x0005)
	c.Thumb(0x9B01)
	c.Thumb(0x9A00)
	c.Thumb(0x4641)
	c.R[14] = 0x081032CF
	SetPositionFromConnection(c)
	if c.U != 0 {
		if c.U != 0x081032CF {
			return
		}
		c.U = 0
	}
	c.Thumb(0x7A69)
	c.Thumb(0x7A28)
	c.R[14] = 0x081032D7
	c.NCallT(0x0813ECF8)
	if c.U != 0 {
		if c.U != 0x081032D7 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2201)
	c.Thumb(0x464D)
	c.Thumb(0x7823)
	c.Thumb(0x4313)
	c.Thumb(0x6832)
	c.Thumb(0x7023)
	c.Thumb(0x2600)
	c.Thumb(0x5F93)
	c.Thumb(0x1AEE)
	c.Thumb(0x6066)
	c.Thumb(0x2502)
	c.Thumb(0x5F51)
	c.Thumb(0x4453)
	c.Thumb(0x1A7F)
	c.Thumb(0x4459)
	c.Thumb(0x60A7)
	c.Thumb(0x4640)
	c.Thumb(0x8013)
	c.Thumb(0x8051)
	c.R[14] = 0x08103301
	MoveMapViewToBackup(c)
	if c.U != 0 {
		if c.U != 0x08103301 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2301)
	c.Thumb(0x7820)
	c.Thumb(0x4018)
	goto L_08103294
}

// 0x08103310
func GetIncomingConnection(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(40)
	c.Thumb(0xB5F0)
	c.Thumb(0x46CE)
	c.Thumb(0x4647)
	c.R[15] = 0x0810331A
	c.Thumb(0x4B14)
	c.Thumb(0x68DB)
	c.Thumb(0x0600)
	c.Thumb(0x4688)
	c.Thumb(0x4691)
	c.Thumb(0xB580)
	c.Thumb(0x0E06)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_08103364
	}
	c.Thumb(0x685C)
	c.Thumb(0x2C00)
	if c.Cond(0x0) {
		goto L_08103364
	}
	c.Thumb(0x681F)
	c.Thumb(0x2F00)
	if c.Cond(0xD) {
		goto L_08103364
	}
	c.Thumb(0x2500)
	goto L_08103340
L_08103338:
	c.NT(8)
	c.Thumb(0x3501)
	c.Thumb(0x340C)
	c.Thumb(0x42AF)
	if c.Cond(0x0) {
		goto L_08103364
	}
L_08103340:
	c.NT(20)
	c.Thumb(0x7823)
	c.Thumb(0x42B3)
	if c.Cond(0x1) {
		goto L_08103338
	}
	c.Thumb(0x0023)
	c.Thumb(0x464A)
	c.Thumb(0x4641)
	c.Thumb(0x0030)
	c.R[14] = 0x08103353
	IsPosInIncomingConnectingMap(c)
	if c.U != 0 {
		if c.U != 0x08103353 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2801)
	if c.Cond(0x1) {
		goto L_08103338
	}
L_08103356:
	c.NT(14)
	c.Thumb(0x0020)
	c.Thumb(0xBCC0)
	c.Thumb(0x46B9)
	c.Thumb(0x46B0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103364:
	c.NT(4)
	c.Thumb(0x2400)
	goto L_08103356
}

// 0x0810336C
func IsPosInIncomingConnectingMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(50)
	c.Thumb(0xB5F0)
	c.Thumb(0x0600)
	c.Thumb(0x0E04)
	c.Thumb(0x000F)
	c.Thumb(0x7A18)
	c.Thumb(0x7A59)
	c.Thumb(0x0015)
	c.Thumb(0x001E)
	c.R[14] = 0x08103381
	c.NCallT(0x0813E778)
	if c.U != 0 {
		if c.U != 0x08103381 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2C02)
	if c.Cond(0x9) {
		goto L_081033C8
	}
	c.Thumb(0x3C03)
	c.Thumb(0x0624)
	c.Thumb(0x0E24)
	c.Thumb(0x2C01)
	if c.Cond(0x8) {
		goto L_081033C4
	}
	c.R[15] = 0x08103392
	c.Thumb(0x491E)
	c.Thumb(0x6802)
	c.Thumb(0x6809)
	c.Thumb(0x6873)
	c.Thumb(0x6852)
	c.Thumb(0x6849)
	c.Thumb(0x189A)
	c.Thumb(0x428A)
	if c.Cond(0xC) {
		goto L_08103402
	}
L_081033A0:
	c.NT(30)
	c.Thumb(0x17D0)
	c.Thumb(0x0FE9)
	c.Thumb(0x42AA)
	c.Thumb(0x4141)
	c.Thumb(0x000A)
	c.Thumb(0x43D9)
	c.Thumb(0x17C9)
	c.Thumb(0x400B)
	c.Thumb(0x17E8)
	c.Thumb(0x0FD9)
	c.Thumb(0x429D)
	c.Thumb(0x4148)
	c.Thumb(0x4010)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
L_081033BE:
	c.NT(6)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081033C4:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_081033BE
L_081033C8:
	c.NT(22)
	c.Thumb(0x2C00)
	if c.Cond(0x0) {
		goto L_081033C4
	}
	c.R[15] = 0x081033D0
	c.Thumb(0x490E)
	c.Thumb(0x6802)
	c.Thumb(0x6809)
	c.Thumb(0x6873)
	c.Thumb(0x6812)
	c.Thumb(0x6809)
	c.Thumb(0x189A)
	c.Thumb(0x428A)
	if c.Cond(0xC) {
		goto L_081033FE
	}
L_081033DE:
	c.NT(32)
	c.Thumb(0x17D0)
	c.Thumb(0x0FF9)
	c.Thumb(0x42BA)
	c.Thumb(0x4141)
	c.Thumb(0x000A)
	c.Thumb(0x43D9)
	c.Thumb(0x17C9)
	c.Thumb(0x400B)
	c.Thumb(0x17F8)
	c.Thumb(0x0FD9)
	c.Thumb(0x429F)
	c.Thumb(0x4148)
	c.Thumb(0x4010)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
	goto L_081033BE
L_081033FE:
	c.NT(4)
	c.Thumb(0x000A)
	goto L_081033DE
L_08103402:
	c.NT(4)
	c.Thumb(0x000A)
	goto L_081033A0
}

// 0x0810340C
func IsCoordInIncomingConnectingMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0x189A)
	c.Thumb(0xB510)
	c.Thumb(0x0004)
	c.Thumb(0x428A)
	if c.Cond(0xD) {
		goto L_08103418
	}
	c.Thumb(0x000A)
L_08103418:
	c.NT(36)
	c.Thumb(0x0FE0)
	c.Thumb(0x17D1)
	c.Thumb(0x42A2)
	c.Thumb(0x4141)
	c.Thumb(0x000A)
	c.Thumb(0x43D9)
	c.Thumb(0x17C9)
	c.Thumb(0x400B)
	c.Thumb(0x0FD8)
	c.Thumb(0x17E1)
	c.Thumb(0x429C)
	c.Thumb(0x4148)
	c.Thumb(0x4010)
	c.Thumb(0x0600)
	c.Thumb(0x0E00)
	c.Thumb(0xBC10)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x0810343C
func IsCoordInConnectingMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(12)
	c.Thumb(0x43C3)
	c.Thumb(0x2201)
	c.Thumb(0x0FDB)
	c.Thumb(0x4288)
	if c.Cond(0xB) {
		goto L_08103448
	}
	c.Thumb(0x2200)
L_08103448:
	c.NT(6)
	c.Thumb(0x4013)
	c.Thumb(0x0018)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x08103450
func IsPosInConnectingMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(44)
	c.Thumb(0xB570)
	c.Thumb(0x0004)
	c.Thumb(0x000D)
	c.Thumb(0x7A41)
	c.Thumb(0x7A00)
	c.Thumb(0x0016)
	c.R[14] = 0x08103461
	c.NCallT(0x0813E778)
	if c.U != 0 {
		if c.U != 0x08103461 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x7823)
	c.Thumb(0x2B02)
	if c.Cond(0x9) {
		goto L_0810348E
	}
	c.Thumb(0x3B03)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x2B01)
	if c.Cond(0x8) {
		goto L_0810348A
	}
	c.Thumb(0x6801)
	c.Thumb(0x6863)
	c.Thumb(0x6849)
	c.Thumb(0x2201)
	c.Thumb(0x1AF3)
	c.Thumb(0x428B)
	if c.Cond(0xA) {
		goto L_081034B2
	}
L_0810347E:
	c.NT(6)
	c.Thumb(0x43D8)
	c.Thumb(0x0FC0)
	c.Thumb(0x4010)
L_08103484:
	c.NT(6)
	c.Thumb(0xBC70)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0810348A:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_08103484
L_0810348E:
	c.NT(26)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0810348A
	}
	c.Thumb(0x6802)
	c.Thumb(0x6861)
	c.Thumb(0x6812)
	c.Thumb(0x2301)
	c.Thumb(0x1A69)
	c.Thumb(0x4291)
	if c.Cond(0xA) {
		goto L_081034A8
	}
	c.Thumb(0x43C8)
	c.Thumb(0x0FC0)
	c.Thumb(0x4018)
	goto L_08103484
L_081034A8:
	c.NT(10)
	c.Thumb(0x43C8)
	c.Thumb(0x2300)
	c.Thumb(0x0FC0)
	c.Thumb(0x4018)
	goto L_08103484
L_081034B2:
	c.NT(4)
	c.Thumb(0x2200)
	goto L_0810347E
}

// 0x081034B8
func GetMapConnectionAtPos(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(64)
	c.Thumb(0xB5F0)
	c.Thumb(0x46DE)
	c.Thumb(0x4657)
	c.Thumb(0x4645)
	c.Thumb(0x464E)
	c.Thumb(0x0403)
	c.Thumb(0x141B)
	c.Thumb(0x469B)
	c.Thumb(0x040B)
	c.Thumb(0x141B)
	c.Thumb(0xB5E0)
	c.Thumb(0x469A)
	c.R[15] = 0x081034D4
	c.Thumb(0x4B31)
	c.Thumb(0x4698)
	c.Thumb(0x68DB)
	c.Thumb(0xB082)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0810357E
	}
	c.Thumb(0x681D)
	c.Thumb(0x2D00)
	if c.Cond(0xD) {
		goto L_0810357E
	}
	c.Thumb(0x685C)
	c.Thumb(0x4653)
	c.Thumb(0x2601)
	c.Thumb(0x2B06)
	if c.Cond(0xD) {
		goto L_08103586
	}
	c.Thumb(0x465A)
	c.Thumb(0x0636)
	c.Thumb(0x2301)
	c.Thumb(0x0E36)
	c.Thumb(0x2A06)
	if c.Cond(0xD) {
		goto L_08103582
	}
L_081034F8:
	c.NT(22)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x4699)
	c.Thumb(0x4653)
	c.Thumb(0x3B07)
	c.Thumb(0x9300)
	c.Thumb(0x465B)
	c.Thumb(0x3B07)
	c.Thumb(0x2700)
	c.Thumb(0x9301)
	goto L_08103520
L_0810350E:
	c.NT(10)
	c.Thumb(0x2A03)
	if c.Cond(0x1) {
		goto L_08103566
	}
	c.Thumb(0x464B)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_08103566
	}
L_08103518:
	c.NT(8)
	c.Thumb(0x3701)
	c.Thumb(0x340C)
	c.Thumb(0x42BD)
	if c.Cond(0x0) {
		goto L_0810357E
	}
L_08103520:
	c.NT(20)
	c.Thumb(0x7822)
	c.Thumb(0x1F53)
	c.Thumb(0x061B)
	c.Thumb(0x0E1B)
	c.Thumb(0x2B01)
	if c.Cond(0x9) {
		goto L_08103518
	}
	c.Thumb(0x2A02)
	if c.Cond(0x1) {
		goto L_08103534
	}
	c.Thumb(0x2E00)
	if c.Cond(0x1) {
		goto L_08103518
	}
L_08103534:
	c.NT(16)
	c.Thumb(0x2A01)
	if c.Cond(0x1) {
		goto L_0810350E
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x685B)
	c.Thumb(0x3306)
	c.Thumb(0x4553)
	if c.Cond(0xA) {
		goto L_08103518
	}
L_08103544:
	c.NT(12)
	c.Thumb(0x0020)
	c.Thumb(0x9A00)
	c.Thumb(0x9901)
	c.R[14] = 0x0810354F
	IsPosInConnectingMap(c)
	if c.U != 0 {
		if c.U != 0x0810354F {
			return
		}
		c.U = 0
	}
	c.Thumb(0x2801)
	if c.Cond(0x1) {
		goto L_08103518
	}
L_08103552:
	c.NT(20)
	c.Thumb(0x0020)
	c.Thumb(0xB002)
	c.Thumb(0xBCF0)
	c.Thumb(0x46BB)
	c.Thumb(0x46B2)
	c.Thumb(0x46A9)
	c.Thumb(0x46A0)
	c.Thumb(0xBCF0)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103566:
	c.NT(24)
	c.Thumb(0x2A04)
	if c.Cond(0x1) {
		goto L_08103544
	}
	c.Thumb(0x4643)
	c.Thumb(0x681B)
	c.Thumb(0x681B)
	c.Thumb(0x3306)
	c.Thumb(0x455B)
	if c.Cond(0xB) {
		goto L_08103544
	}
	c.Thumb(0x3701)
	c.Thumb(0x340C)
	c.Thumb(0x42BD)
	if c.Cond(0x1) {
		goto L_08103520
	}
L_0810357E:
	c.NT(4)
	c.Thumb(0x2400)
	goto L_08103552
L_08103582:
	c.NT(4)
	c.Thumb(0x2300)
	goto L_081034F8
L_08103586:
	c.NT(16)
	c.Thumb(0x2600)
	c.Thumb(0x465A)
	c.Thumb(0x0636)
	c.Thumb(0x2301)
	c.Thumb(0x0E36)
	c.Thumb(0x2A06)
	if c.Cond(0xC) {
		goto L_081034F8
	}
	goto L_08103582
}

// 0x0810359C
func SetCameraFocusCoords(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.R[15] = 0x081035A0
	c.Thumb(0x4B03)
	c.Thumb(0x681B)
	c.Thumb(0x3807)
	c.Thumb(0x3907)
	c.Thumb(0x8018)
	c.Thumb(0x8059)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081035B0
func GetCameraFocusCoords(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(18)
	c.R[15] = 0x081035B4
	c.Thumb(0x4B04)
	c.Thumb(0x681A)
	c.Thumb(0x8813)
	c.Thumb(0x3307)
	c.Thumb(0x8003)
	c.Thumb(0x8853)
	c.Thumb(0x3307)
	c.Thumb(0x800B)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081035C8
func SetCameraCoords(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(10)
	c.R[15] = 0x081035CC
	c.Thumb(0x4B02)
	c.Thumb(0x681B)
	c.Thumb(0x8018)
	c.Thumb(0x8059)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081035D8
func GetCameraCoords(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(14)
	c.R[15] = 0x081035DC
	c.Thumb(0x4B03)
	c.Thumb(0x681B)
	c.Thumb(0x881A)
	c.Thumb(0x8002)
	c.Thumb(0x885B)
	c.Thumb(0x800B)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081035EC
func MapGridSetMetatileImpassabilityAt(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(26)
	c.Thumb(0xB510)
	c.Thumb(0x2800)
	if c.Cond(0xB) {
		goto L_08103606
	}
	c.R[15] = 0x081035F6
	c.Thumb(0x4B13)
	c.Thumb(0x469C)
	c.Thumb(0x681C)
	c.Thumb(0x2900)
	if c.Cond(0xB) {
		goto L_08103606
	}
	c.Thumb(0x2301)
	c.Thumb(0x4284)
	if c.Cond(0xD) {
		goto L_0810360C
	}
	c.Thumb(0x061B)
	if c.Cond(0x1) {
		goto L_08103612
	}
L_08103606:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_0810360C:
	c.NT(6)
	c.Thumb(0x2300)
	c.Thumb(0x061B)
	if c.Cond(0x0) {
		goto L_08103606
	}
L_08103612:
	c.NT(38)
	c.Thumb(0x4663)
	c.Thumb(0x685B)
	c.Thumb(0x428B)
	if c.Cond(0xD) {
		goto L_08103606
	}
	c.Thumb(0x0023)
	c.Thumb(0x434B)
	c.Thumb(0x1819)
	c.Thumb(0x4663)
	c.Thumb(0x689B)
	c.Thumb(0x0049)
	c.Thumb(0x1858)
	c.Thumb(0x5A5B)
	c.Thumb(0x2A00)
	if c.Cond(0x0) {
		goto L_08103638
	}
	c.Thumb(0x22C0)
	c.Thumb(0x0112)
	c.Thumb(0x4313)
	c.Thumb(0x8003)
	goto L_08103606
L_08103638:
	c.NT(8)
	c.R[15] = 0x0810363C
	c.Thumb(0x4A02)
	c.Thumb(0x4013)
	c.Thumb(0x8003)
	goto L_08103606
}

// 0x08103648
func SkipCopyingMetatileFromSavedMap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.Thumb(0x0409)
	c.Thumb(0x0C0B)
	c.Thumb(0x0611)
	c.Thumb(0xB500)
	c.Thumb(0x0E09)
	c.Thumb(0x29FF)
	if c.Cond(0x0) {
		goto L_08103676
	}
	c.Thumb(0x005B)
	c.Thumb(0x18C2)
	c.Thumb(0x2900)
	if c.Cond(0x0) {
		goto L_08103672
	}
L_0810365E:
	c.NT(14)
	c.Thumb(0x8810)
	c.Thumb(0x0580)
	c.Thumb(0x0D80)
	c.R[14] = 0x08103669
	c.NCallT(0x08105E48)
	if c.U != 0 {
		if c.U != 0x08103669 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x3801)
	c.Thumb(0x4243)
	c.Thumb(0x4158)
L_0810366E:
	c.NT(4)
	c.Thumb(0xBC02)
	{
		t := c.R[1]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103672:
	c.NT(4)
	c.Thumb(0x1AC2)
	goto L_0810365E
L_08103676:
	c.NT(4)
	c.Thumb(0x2000)
	goto L_0810366E
}

// 0x0810367C
func CopyTilesetToVram(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0xB500)
	c.Thumb(0x0409)
	c.Thumb(0x0412)
	c.Thumb(0xB081)
	c.Thumb(0x0C09)
	c.Thumb(0x0C13)
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_0810369E
	}
	c.Thumb(0x7802)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_081036A4
	}
	c.Thumb(0x0549)
	c.Thumb(0x0C0A)
	c.Thumb(0x6841)
	c.Thumb(0x2002)
	c.R[14] = 0x0810369F
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x0810369F {
			return
		}
		c.U = 0
	}
L_0810369E:
	c.NT(6)
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081036A4:
	c.NT(14)
	c.Thumb(0x014A)
	c.Thumb(0x6841)
	c.Thumb(0x2000)
	c.Thumb(0x9000)
	c.Thumb(0x3002)
	c.R[14] = 0x081036B3
	c.NCallT(0x08131314)
	if c.U != 0 {
		if c.U != 0x081036B3 {
			return
		}
		c.U = 0
	}
	goto L_0810369E
}

// 0x081036B4
func CopyTilesetToVramUsingHeap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(32)
	c.Thumb(0xB500)
	c.Thumb(0x0409)
	c.Thumb(0x0412)
	c.Thumb(0xB081)
	c.Thumb(0x0C09)
	c.Thumb(0x0C13)
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_081036D6
	}
	c.Thumb(0x7802)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_081036DC
	}
	c.Thumb(0x0549)
	c.Thumb(0x0C0A)
	c.Thumb(0x6841)
	c.Thumb(0x2002)
	c.R[14] = 0x081036D7
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x081036D7 {
			return
		}
		c.U = 0
	}
L_081036D6:
	c.NT(6)
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081036DC:
	c.NT(14)
	c.Thumb(0x014A)
	c.Thumb(0x6841)
	c.Thumb(0x2000)
	c.Thumb(0x9000)
	c.Thumb(0x3002)
	c.R[14] = 0x081036EB
	c.NCallT(0x081313C0)
	if c.U != 0 {
		if c.U != 0x081036EB {
			return
		}
		c.U = 0
	}
	goto L_081036D6
}

// 0x081036EC
func ApplyGlobalTintToPaletteEntries(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081036F0
func ApplyGlobalTintToPaletteSlot(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(2)
	{
		t := c.R[14]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}

// 0x081036F4
func LoadTilesetPalette(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(42)
	c.Thumb(0x0409)
	c.Thumb(0x0C0B)
	c.Thumb(0x469C)
	c.Thumb(0x2300)
	c.Thumb(0xB530)
	c.Thumb(0x0412)
	c.Thumb(0xB082)
	c.Thumb(0x0C15)
	c.Thumb(0xAA01)
	c.Thumb(0x1E04)
	c.Thumb(0x8053)
	if c.Cond(0x0) {
		goto L_08103720
	}
	c.Thumb(0x7843)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_08103728
	}
	c.Thumb(0x6880)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_0810374E
	}
	c.Thumb(0x002A)
	c.Thumb(0x4661)
	c.R[14] = 0x08103721
	c.NCallT(0x08142C2C)
	if c.U != 0 {
		if c.U != 0x08103721 {
			return
		}
		c.U = 0
	}
L_08103720:
	c.NT(8)
	c.Thumb(0xB002)
	c.Thumb(0xBC30)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103728:
	c.NT(34)
	c.Thumb(0x4661)
	c.Thumb(0xAB01)
	c.Thumb(0x1C98)
	c.Thumb(0x2202)
	c.Thumb(0x9100)
	c.R[14] = 0x08103737
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08103737 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x9B00)
	c.Thumb(0x68A0)
	c.Thumb(0x1EAA)
	c.Thumb(0x1C59)
	c.Thumb(0x0412)
	c.Thumb(0x0409)
	c.Thumb(0x0C12)
	c.Thumb(0x0C09)
	c.Thumb(0x3002)
	c.R[14] = 0x0810374D
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x0810374D {
			return
		}
		c.U = 0
	}
	goto L_08103720
L_0810374E:
	c.NT(10)
	c.Thumb(0x002A)
	c.Thumb(0x4661)
	c.Thumb(0x30C0)
	c.R[14] = 0x08103759
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08103759 {
			return
		}
		c.U = 0
	}
	goto L_08103720
}

// 0x0810375C
func CopyPrimaryTilesetToVram(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(28)
	c.Thumb(0xB500)
	c.Thumb(0x6903)
	c.Thumb(0xB081)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_0810377A
	}
	c.Thumb(0x781A)
	c.Thumb(0x6859)
	c.Thumb(0x2300)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_08103780
	}
	c.Thumb(0x2280)
	c.Thumb(0x2002)
	c.Thumb(0x01D2)
	c.R[14] = 0x0810377B
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x0810377B {
			return
		}
		c.U = 0
	}
L_0810377A:
	c.NT(6)
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103780:
	c.NT(12)
	c.Thumb(0x2280)
	c.Thumb(0x9300)
	c.Thumb(0x01D2)
	c.Thumb(0x2002)
	c.R[14] = 0x0810378D
	c.NCallT(0x08131314)
	if c.U != 0 {
		if c.U != 0x0810378D {
			return
		}
		c.U = 0
	}
	goto L_0810377A
}

// 0x08103790
func CopySecondaryTilesetToVram(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB500)
	c.Thumb(0x6943)
	c.Thumb(0xB081)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_081037B0
	}
	c.Thumb(0x781A)
	c.Thumb(0x6859)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_081037B6
	}
	c.Thumb(0x2380)
	c.Thumb(0x2280)
	c.Thumb(0x2002)
	c.Thumb(0x009B)
	c.Thumb(0x01D2)
	c.R[14] = 0x081037B1
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x081037B1 {
			return
		}
		c.U = 0
	}
L_081037B0:
	c.NT(6)
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081037B6:
	c.NT(18)
	c.Thumb(0x2300)
	c.Thumb(0x2280)
	c.Thumb(0x9300)
	c.Thumb(0x2380)
	c.Thumb(0x01D2)
	c.Thumb(0x009B)
	c.Thumb(0x2002)
	c.R[14] = 0x081037C9
	c.NCallT(0x08131314)
	if c.U != 0 {
		if c.U != 0x081037C9 {
			return
		}
		c.U = 0
	}
	goto L_081037B0
}

// 0x081037CC
func CopySecondaryTilesetToVramUsingHeap(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(30)
	c.Thumb(0xB500)
	c.Thumb(0x6943)
	c.Thumb(0xB081)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_081037EC
	}
	c.Thumb(0x781A)
	c.Thumb(0x6859)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_081037F2
	}
	c.Thumb(0x2380)
	c.Thumb(0x2280)
	c.Thumb(0x2002)
	c.Thumb(0x009B)
	c.Thumb(0x01D2)
	c.R[14] = 0x081037ED
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x081037ED {
			return
		}
		c.U = 0
	}
L_081037EC:
	c.NT(6)
	c.Thumb(0xB001)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081037F2:
	c.NT(18)
	c.Thumb(0x2300)
	c.Thumb(0x2280)
	c.Thumb(0x9300)
	c.Thumb(0x2380)
	c.Thumb(0x2002)
	c.Thumb(0x009B)
	c.Thumb(0x01D2)
	c.R[14] = 0x08103805
	c.NCallT(0x081313C0)
	if c.U != 0 {
		if c.U != 0x08103805 {
			return
		}
		c.U = 0
	}
	goto L_081037EC
}

// 0x08103808
func LoadPrimaryTilesetPalette(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(34)
	c.Thumb(0xB510)
	c.Thumb(0xB081)
	c.Thumb(0x2300)
	c.Thumb(0x466A)
	c.Thumb(0x6904)
	c.Thumb(0x8053)
	c.Thumb(0x2C00)
	if c.Cond(0x0) {
		goto L_0810382C
	}
	c.Thumb(0x7863)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_08103834
	}
	c.Thumb(0x68A0)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_0810384E
	}
	c.Thumb(0x22C0)
	c.Thumb(0x2100)
	c.R[14] = 0x0810382D
	c.NCallT(0x08142C2C)
	if c.U != 0 {
		if c.U != 0x0810382D {
			return
		}
		c.U = 0
	}
L_0810382C:
	c.NT(8)
	c.Thumb(0xB001)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103834:
	c.NT(22)
	c.Thumb(0x466B)
	c.Thumb(0x2202)
	c.Thumb(0x1C98)
	c.Thumb(0x2100)
	c.R[14] = 0x08103841
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08103841 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x68A0)
	c.Thumb(0x22BE)
	c.Thumb(0x2101)
	c.Thumb(0x3002)
	c.R[14] = 0x0810384D
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x0810384D {
			return
		}
		c.U = 0
	}
	goto L_0810382C
L_0810384E:
	c.NT(10)
	c.Thumb(0x22C0)
	c.Thumb(0x2100)
	c.Thumb(0x30C0)
	c.R[14] = 0x08103859
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08103859 {
			return
		}
		c.U = 0
	}
	goto L_0810382C
}

// 0x0810385C
func LoadSecondaryTilesetPalette(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(34)
	c.Thumb(0xB510)
	c.Thumb(0xB081)
	c.Thumb(0x2300)
	c.Thumb(0x466A)
	c.Thumb(0x6944)
	c.Thumb(0x8053)
	c.Thumb(0x2C00)
	if c.Cond(0x0) {
		goto L_08103880
	}
	c.Thumb(0x7863)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_08103888
	}
	c.Thumb(0x68A0)
	c.Thumb(0x2B01)
	if c.Cond(0x0) {
		goto L_081038A2
	}
	c.Thumb(0x22E0)
	c.Thumb(0x2160)
	c.R[14] = 0x08103881
	c.NCallT(0x08142C2C)
	if c.U != 0 {
		if c.U != 0x08103881 {
			return
		}
		c.U = 0
	}
L_08103880:
	c.NT(8)
	c.Thumb(0xB001)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_08103888:
	c.NT(22)
	c.Thumb(0x466B)
	c.Thumb(0x2202)
	c.Thumb(0x1C98)
	c.Thumb(0x2160)
	c.R[14] = 0x08103895
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x08103895 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x68A0)
	c.Thumb(0x22DE)
	c.Thumb(0x2161)
	c.Thumb(0x3002)
	c.R[14] = 0x081038A1
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x081038A1 {
			return
		}
		c.U = 0
	}
	goto L_08103880
L_081038A2:
	c.NT(10)
	c.Thumb(0x22E0)
	c.Thumb(0x2160)
	c.Thumb(0x30C0)
	c.R[14] = 0x081038AD
	c.NCallT(0x08142C68)
	if c.U != 0 {
		if c.U != 0x081038AD {
			return
		}
		c.U = 0
	}
	goto L_08103880
}

// 0x081038B0
func CopyMapTilesetsToVram(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(34)
	c.Thumb(0xB510)
	c.Thumb(0x0004)
	c.Thumb(0xB081)
	c.Thumb(0x2800)
	if c.Cond(0x0) {
		goto L_081038F0
	}
	c.Thumb(0x6903)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_081038D4
	}
	c.Thumb(0x781A)
	c.Thumb(0x6859)
	c.Thumb(0x2300)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_081038F8
	}
	c.Thumb(0x2280)
	c.Thumb(0x2002)
	c.Thumb(0x01D2)
	c.R[14] = 0x081038D5
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x081038D5 {
			return
		}
		c.U = 0
	}
L_081038D4:
	c.NT(6)
	c.Thumb(0x6963)
	c.Thumb(0x2B00)
	if c.Cond(0x0) {
		goto L_081038F0
	}
L_081038DA:
	c.NT(20)
	c.Thumb(0x781A)
	c.Thumb(0x6859)
	c.Thumb(0x2A00)
	if c.Cond(0x1) {
		goto L_0810390C
	}
	c.Thumb(0x2380)
	c.Thumb(0x2280)
	c.Thumb(0x2002)
	c.Thumb(0x009B)
	c.Thumb(0x01D2)
	c.R[14] = 0x081038F1
	c.NCallT(0x080A7934)
	if c.U != 0 {
		if c.U != 0x081038F1 {
			return
		}
		c.U = 0
	}
L_081038F0:
	c.NT(8)
	c.Thumb(0xB001)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
L_081038F8:
	c.NT(18)
	c.Thumb(0x2280)
	c.Thumb(0x9300)
	c.Thumb(0x2002)
	c.Thumb(0x01D2)
	c.R[14] = 0x08103905
	c.NCallT(0x081313C0)
	if c.U != 0 {
		if c.U != 0x08103905 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x6963)
	c.Thumb(0x2B00)
	if c.Cond(0x1) {
		goto L_081038DA
	}
	goto L_081038F0
L_0810390C:
	c.NT(18)
	c.Thumb(0x2300)
	c.Thumb(0x2280)
	c.Thumb(0x9300)
	c.Thumb(0x2380)
	c.Thumb(0x2002)
	c.Thumb(0x009B)
	c.Thumb(0x01D2)
	c.R[14] = 0x0810391F
	c.NCallT(0x081313C0)
	if c.U != 0 {
		if c.U != 0x0810391F {
			return
		}
		c.U = 0
	}
	goto L_081038F0
}

// 0x08103920
func LoadMapTilesetPalettes(c *g.CPU) {
	lr := c.R[14]
	_ = lr
	c.NT(22)
	c.Thumb(0xB510)
	c.Thumb(0x1E04)
	if c.Cond(0x0) {
		goto L_0810393A
	}
	c.Thumb(0x22C0)
	c.Thumb(0x2100)
	c.Thumb(0x6900)
	c.R[14] = 0x08103931
	LoadTilesetPalette(c)
	if c.U != 0 {
		if c.U != 0x08103931 {
			return
		}
		c.U = 0
	}
	c.Thumb(0x22E0)
	c.Thumb(0x2160)
	c.Thumb(0x6960)
	c.R[14] = 0x0810393B
	LoadTilesetPalette(c)
	if c.U != 0 {
		if c.U != 0x0810393B {
			return
		}
		c.U = 0
	}
L_0810393A:
	c.NT(6)
	c.Thumb(0xBC10)
	c.Thumb(0xBC01)
	{
		t := c.R[0]
		if t&^1 == lr&^1 {
			return
		}
		if !c.NReg(t) {
			c.U = t
			return
		}
		ret := c.R[14]
		c.NCallA(t)
		if c.U != 0 {
			return
		}
		if ret&^1 == lr&^1 {
			return
		}
		if !c.NReg(ret) {
			c.U = ret
			return
		}
		c.NCallA(ret)
		return
	}
}
